// Seed configuration for the mock API server
// This file is used by seed.ts to generate SQL statements

export const seedConfig = {
  // Client configurations for seed data
  clients: [
    {
      ticker: "WEN",
      companyName: "The Wendy's Company",
      shortName: "Wendy's",
      industry: "Restaurants",
      description: "Quick-service restaurant chain",
      website: "https://www.wendys.com",
      primaryContact: "Mike Chen",
      primaryContactEmail: "mike.chen@wendys.com",
      isActive: true,
      brandingId: 966152,
    },
    {
      ticker: "FOC",
      companyName: "FocalPoint",
      shortName: "FocalPoint",
      industry: "Restaurants",
      description: "Demo issuer using Wendy's proxy voting seed data",
      website: "https://www.focalpoint.com",
      primaryContact: "Tim Morgan",
      primaryContactEmail: "tim@focalpoint.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "PAYC",
      companyName: "Paycom Software, Inc.",
      shortName: "Paycom",
      industry: "Software",
      description: "Cloud-based human capital management software",
      website: "https://www.paycom.com",
      primaryContact: "Lisa Rodriguez",
      primaryContactEmail: "lisa.rodriguez@paycom.com",
      isActive: true,
      brandingId: 963998,
    },
    {
      ticker: "WWD",
      companyName: "Woodward, Inc.",
      shortName: "Woodward",
      industry: "Aerospace & Defense",
      description: "Aerospace and industrial control systems",
      website: "https://www.woodward.com",
      primaryContact: "David Kim",
      primaryContactEmail: "david.kim@woodward.com",
      isActive: true,
      brandingId: 962713,
    },
    {
      ticker: "ELVN",
      companyName: "Enliven Therapeutics, Inc.",
      shortName: "Enliven",
      industry: "Biotechnology",
      description: "Clinical-stage biopharmaceutical company",
      website: "https://www.enliven.com",
      primaryContact: "Jenny Patel",
      primaryContactEmail: "jenny.patel@enliven.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "JPMR",
      companyName: "J.P. Morgan Real Estate Income Trust, Inc.",
      shortName: "J.P. Morgan REIT",
      industry: "Real Estate",
      description: "Non-traded real estate investment trust",
      website: "https://www.jpmorgan.com",
      primaryContact: "Amanda Clarke",
      primaryContactEmail: "amanda.clarke@jpmorgan.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ETWO",
      companyName: "E2open Parent Holdings Inc.",
      shortName: "e2open",
      industry: "Software",
      description: "Cloud-based supply chain management platform",
      website: "https://www.e2open.com",
      primaryContact: "Marcus Webb",
      primaryContactEmail: "marcus.webb@e2open.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "CHH",
      companyName: "Champion Homes, Inc.",
      shortName: "Champion Homes",
      industry: "Residential Construction",
      description: "Manufactured and modular housing manufacturer",
      website: "https://www.championhomes.com",
      primaryContact: "Rachel Torres",
      primaryContactEmail: "rachel.torres@championhomes.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "BCSF",
      companyName: "Bain Capital Specialty Finance, Inc.",
      shortName: "Bain Capital",
      industry: "Financial Services",
      description: "Specialty finance business development company",
      website: "https://www.baincapital.com",
      primaryContact: "Steven Park",
      primaryContactEmail: "steven.park@baincapital.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "STTK",
      companyName: "Shattuck Labs, Inc.",
      shortName: "Shattuck Labs",
      industry: "Biotechnology",
      description: "Clinical-stage immunology oncology company",
      website: "https://www.shattucklabs.com",
      primaryContact: "Olivia Grant",
      primaryContactEmail: "olivia.grant@shattucklabs.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "NOMD",
      companyName: "Nomad Foods Limited",
      shortName: "Nomad Foods",
      industry: "Consumer Staples",
      description: "Frozen food company operating across Europe",
      website: "https://www.nomadfoods.com",
      primaryContact: "Thomas Hardy",
      primaryContactEmail: "thomas.hardy@nomadfoods.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "QRHC",
      companyName: "Quest Resource Holding Corporation",
      shortName: "Quest Resource",
      industry: "Environmental Services",
      description: "Sustainability and environmental management solutions",
      website: "https://www.questrmg.com",
      primaryContact: "Diana Foster",
      primaryContactEmail: "diana.foster@questrmg.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ICU",
      companyName: "SeaStar Medical Holding Corporation",
      shortName: "SeaStar Medical",
      industry: "Medical Devices",
      description: "Developing selective cytopheretic device therapies",
      website: "https://www.seastarmedical.com",
      primaryContact: "Brian Nguyen",
      primaryContactEmail: "brian.nguyen@seastarmedical.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "CTNM",
      companyName: "Contineum Therapeutics, Inc.",
      shortName: "Contineum",
      industry: "Biotechnology",
      description: "Clinical-stage biopharmaceutical company focused on CNS",
      website: "https://www.contineum.com",
      primaryContact: "Priya Sharma",
      primaryContactEmail: "priya.sharma@contineum.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "FULC",
      companyName: "Fulcrum Therapeutics, Inc.",
      shortName: "FulcrumTx",
      industry: "Biotechnology",
      description: "Disease-modifying medicines for genetically defined rare diseases",
      website: "https://www.fulcrumtx.com",
      primaryContact: "Kevin Walsh",
      primaryContactEmail: "kevin.walsh@fulcrumtx.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "LCTX",
      companyName: "Lineage Cell Therapeutics, Inc.",
      shortName: "Lineage Cell",
      industry: "Biotechnology",
      description: "Cell therapy company for degenerative diseases",
      website: "https://www.lineagecell.com",
      primaryContact: "Sarah Quinn",
      primaryContactEmail: "sarah.quinn@lineagecell.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "INZY",
      companyName: "Inozyme Pharma, Inc.",
      shortName: "Inozyme",
      industry: "Biotechnology",
      description: "Rare metabolic disease biopharmaceutical company",
      website: "https://www.inozyme.com",
      primaryContact: "Robert Ellis",
      primaryContactEmail: "robert.ellis@inozyme.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "SPRY",
      companyName: "ARS Pharmaceuticals, Inc.",
      shortName: "ARS Pharma",
      industry: "Pharmaceuticals",
      description: "Commercial-stage specialty pharmaceutical company",
      website: "https://www.ars-pharma.com",
      primaryContact: "Nina Carroll",
      primaryContactEmail: "nina.carroll@ars-pharma.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "GOSS",
      companyName: "Gossamer Bio, Inc.",
      shortName: "Gossamer Bio",
      industry: "Biotechnology",
      description: "Clinical-stage biopharmaceutical company",
      website: "https://www.gossamerbio.com",
      primaryContact: "Ethan Murphy",
      primaryContactEmail: "ethan.murphy@gossamerbio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "AFRM",
      companyName: "Affirm Holdings Inc.",
      shortName: "Affirm",
      industry: "Financial Technology",
      description: "Buy now, pay later financial services platform",
      website: "https://www.affirm.com",
      primaryContact: "Megan Lawson",
      primaryContactEmail: "megan.lawson@affirm.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ALGS",
      companyName: "Aligos Therapeutics, Inc.",
      shortName: "Aligos",
      industry: "Biotechnology",
      description: "Clinical-stage biopharmaceutical company targeting liver diseases",
      website: "https://www.aligos.com",
      primaryContact: "James Norton",
      primaryContactEmail: "james.norton@aligos.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ERAS",
      companyName: "Erasca, Inc.",
      shortName: "Erasca",
      industry: "Biotechnology",
      description: "Clinical-stage oncology company focused on RAS/MAPK pathway",
      website: "https://www.erasca.com",
      primaryContact: "Laura Peterson",
      primaryContactEmail: "laura.peterson@erasca.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "IDYA",
      companyName: "IDEAYA Biosciences, Inc.",
      shortName: "IDEAYA",
      industry: "Biotechnology",
      description: "Oncology-focused precision medicine company",
      website: "https://www.ideayabio.com",
      primaryContact: "Carlos Reyes",
      primaryContactEmail: "carlos.reyes@ideayabio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "CALC",
      companyName: "CalciMedica, Inc.",
      shortName: "CalciMedica",
      industry: "Biotechnology",
      description: "Developing therapies for calcium release-activated calcium disorders",
      website: "https://www.calcimedica.com",
      primaryContact: "Angela Brooks",
      primaryContactEmail: "angela.brooks@calcimedica.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ARTV",
      companyName: "Artiva Biotherapeutics, Inc.",
      shortName: "ArtivaBio",
      industry: "Biotechnology",
      description: "NK cell therapy company for blood cancers and solid tumors",
      website: "https://www.artivabio.com",
      primaryContact: "Daniel Cho",
      primaryContactEmail: "daniel.cho@artivabio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "HLVX",
      companyName: "HilleVax, Inc.",
      shortName: "HilleVax",
      industry: "Biotechnology",
      description: "Vaccine-focused clinical-stage biopharmaceutical company",
      website: "https://www.hillevax.com",
      primaryContact: "Michelle Adams",
      primaryContactEmail: "michelle.adams@hillevax.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "TBIO",
      companyName: "Telesis Bio Inc.",
      shortName: "Telesis Bio",
      industry: "Life Sciences",
      description: "Synthetic biology automation tools and services",
      website: "https://www.telesisbio.com",
      primaryContact: "Jason Powell",
      primaryContactEmail: "jason.powell@telesisbio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "BBIO",
      companyName: "Boundless Big Inc.",
      shortName: "Boundless Bio",
      industry: "Biotechnology",
      description: "Oncology company targeting gene amplification-driven cancers",
      website: "https://www.boundlessbio.com",
      primaryContact: "Stephanie Lee",
      primaryContactEmail: "stephanie.lee@boundlessbio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "LAC",
      companyName: "Lithium Americas Corp.",
      shortName: "Lithium Americas",
      industry: "Mining & Metals",
      description: "Lithium mining and development company",
      website: "https://www.lithiumamericas.com",
      primaryContact: "Gregory Stone",
      primaryContactEmail: "gregory.stone@lithiumamericas.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "WAL",
      companyName: "Western Alliance Bancorporation",
      shortName: "Western Alliance",
      industry: "Banking",
      description: "Regional bank serving commercial businesses and consumers",
      website: "https://www.westernalliancebank.com",
      primaryContact: "Patricia Young",
      primaryContactEmail: "patricia.young@westernalliancebank.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "PTLO",
      companyName: "Portillo's Inc.",
      shortName: "Portillo's",
      industry: "Restaurants",
      description: "Fast casual restaurant chain known for Chicago-style food",
      website: "https://www.portillos.com",
      primaryContact: "Christopher Hall",
      primaryContactEmail: "christopher.hall@portillos.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "MDLZ",
      companyName: "Mondelez International, Inc.",
      shortName: "Mondelēz",
      industry: "Consumer Staples",
      description: "Global snacking powerhouse with iconic brands",
      website: "https://www.mondelezinternational.com",
      primaryContact: "Frances Mitchell",
      primaryContactEmail: "frances.mitchell@mdlz.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "INAB",
      companyName: "IN8bio, Inc.",
      shortName: "IN8bio",
      industry: "Biotechnology",
      description: "Clinical-stage biopharmaceutical company focused on gamma-delta T cells",
      website: "https://www.in8bio.com",
      primaryContact: "Jonathan White",
      primaryContactEmail: "jonathan.white@in8bio.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "TOI",
      companyName: "The Oncology Institute, Inc.",
      shortName: "Oncology Institute",
      industry: "Healthcare",
      description: "Value-based oncology management services organization",
      website: "https://www.theoncologyinstitute.com",
      primaryContact: "Katherine Brown",
      primaryContactEmail: "katherine.brown@theoncologyinstitute.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "AZTR",
      companyName: "Azitra, Inc.",
      shortName: "Azitra",
      industry: "Biotechnology",
      description: "Microbiome-based therapeutics for inflammatory skin diseases",
      website: "https://www.azitra.com",
      primaryContact: "William Turner",
      primaryContactEmail: "william.turner@azitra.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "SONM",
      companyName: "Sonim Technologies, Inc.",
      shortName: "Sonim",
      industry: "Technology Hardware",
      description: "Ultra-rugged mobile phones for industrial workers",
      website: "https://www.sonimtech.com",
      primaryContact: "Sandra Rivera",
      primaryContactEmail: "sandra.rivera@sonimtech.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "PCOR",
      companyName: "Procore Technologies, Inc.",
      shortName: "Procore",
      industry: "Software",
      description: "Construction management software platform",
      website: "https://www.procore.com",
      primaryContact: "Timothy Evans",
      primaryContactEmail: "timothy.evans@procore.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "PHX",
      companyName: "PHX Minerals Inc.",
      shortName: "PHX Minerals",
      industry: "Oil & Gas",
      description: "Minerals and royalties company focused on natural gas",
      website: "https://www.phxmin.com",
      primaryContact: "Dorothy Collins",
      primaryContactEmail: "dorothy.collins@phxmin.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "AMTB",
      companyName: "Amerant Bancorp Inc.",
      shortName: "Amerant Bank",
      industry: "Banking",
      description: "Commercial banking services in Florida and Texas",
      website: "https://www.amerantbank.com",
      primaryContact: "Harold Stewart",
      primaryContactEmail: "harold.stewart@amerantbank.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "SLGC",
      companyName: "SomaLogic, Inc.",
      shortName: "SomaLogic",
      industry: "Life Sciences",
      description: "Protein biomarker discovery and clinical diagnostics",
      website: "https://www.somalogic.com",
      primaryContact: "Rebecca Morris",
      primaryContactEmail: "rebecca.morris@somalogic.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "CD",
      companyName: "Chindata Group Holdings Ltd.",
      shortName: "Chindata Group",
      industry: "Data Centers",
      description: "Carrier-neutral hyperscale data center operator in Asia",
      website: "https://www.chindatagroup.com",
      primaryContact: "Andrew Huang",
      primaryContactEmail: "andrew.huang@chindatagroup.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "FREQ",
      companyName: "Frequency Therapeutics Inc.",
      shortName: "Korro Bio",
      industry: "Biotechnology",
      description: "RNA editing therapeutics for genetic diseases",
      website: "https://www.frequencytx.com",
      primaryContact: "Natalie Scott",
      primaryContactEmail: "natalie.scott@frequencytx.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "AMAM",
      companyName: "Ambrx Biopharma, Inc.",
      shortName: "Ambrx",
      industry: "Biotechnology",
      description: "Engineered precision biologics for oncology",
      website: "https://www.ambrx.com",
      primaryContact: "Vincent Cooper",
      primaryContactEmail: "vincent.cooper@ambrx.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ILG",
      companyName: "ILG Acquisition One Corp.",
      shortName: "ILG Acquisition",
      industry: "Special Purpose Acquisition",
      description: "Blank check company for business combination",
      website: "https://www.ilg.com",
      primaryContact: "Margaret Bell",
      primaryContactEmail: "margaret.bell@ilg.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ENRS",
      companyName: "EnerSa",
      shortName: "EnerSa",
      industry: "Energy",
      description: "Energy storage and solutions company",
      website: "https://www.enersa.com",
      primaryContact: "Thomas Grant",
      primaryContactEmail: "thomas.grant@enersa.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "EHAB",
      companyName: "Enhabit, Inc.",
      shortName: "Enhabit",
      industry: "Healthcare",
      description: "Home health and hospice services provider",
      website: "https://www.enhabit.com",
      primaryContact: "Sandra Diaz",
      primaryContactEmail: "sandra.diaz@enhabit.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "VANI",
      companyName: "Vivani Medical, Inc.",
      shortName: "Vivani Medical",
      industry: "Medical Devices",
      description: "Implantable miniaturized drug delivery devices",
      website: "https://www.vivani.com",
      primaryContact: "Christine Huang",
      primaryContactEmail: "christine.huang@vivani.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "MDGL",
      companyName: "Madrigal Pharmaceuticals, Inc.",
      shortName: "Madrigal",
      industry: "Biotechnology",
      description: "Biopharmaceutical company focused on liver disease",
      website: "https://www.madrigalpharma.com",
      primaryContact: "Brian Walsh",
      primaryContactEmail: "brian.walsh@madrigalpharma.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "CBNA",
      companyName: "Chain Bridge Bancorp, Inc.",
      shortName: "Chain Bridge Bank",
      industry: "Banking",
      description: "Community bank serving the Washington DC metropolitan area",
      website: "https://www.chainbridgebank.com",
      primaryContact: "Patricia Lane",
      primaryContactEmail: "patricia.lane@chainbridgebank.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "INTT",
      companyName: "inTEST Corporation",
      shortName: "inTEST",
      industry: "Technology",
      description: "Semiconductor test and industrial process equipment",
      website: "https://www.intest.com",
      primaryContact: "Robert Nguyen",
      primaryContactEmail: "robert.nguyen@intest.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "DFIN",
      companyName: "Donnelley Financial Solutions, Inc.",
      shortName: "DFIN",
      industry: "Financial Technology",
      description: "Regulatory compliance and financial reporting solutions",
      website: "https://www.dfinsolutions.com",
      primaryContact: "Katherine Owens",
      primaryContactEmail: "katherine.owens@dfinsolutions.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "VAPO",
      companyName: "Vapotherm, Inc.",
      shortName: "Vapotherm",
      industry: "Medical Devices",
      description: "High-velocity therapy respiratory care products",
      website: "https://www.vapotherm.com",
      primaryContact: "James Thornton",
      primaryContactEmail: "james.thornton@vapotherm.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "SQZ",
      companyName: "SQZ Biotech",
      shortName: "SQZ Biotech",
      industry: "Biotechnology",
      description: "Cell therapy platform for oncology and infectious disease",
      website: "https://www.sqzbiotech.com",
      primaryContact: "Allison Murphy",
      primaryContactEmail: "allison.murphy@sqzbiotech.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "NEX",
      companyName: "NexTier Oilfield Solutions Inc.",
      shortName: "NexTier",
      industry: "Oil & Gas Services",
      description: "Completion services for unconventional oil and gas",
      website: "https://www.nextierofs.com",
      primaryContact: "Derek Simmons",
      primaryContactEmail: "derek.simmons@nextierofs.com",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "MNMD",
      companyName: "Mind Medicine (MindMed) Inc.",
      shortName: "MindMed",
      industry: "Biotechnology",
      description: "Psychedelic-inspired medicines for brain health disorders",
      website: "https://www.mindmed.co",
      primaryContact: "Olivia Reyes",
      primaryContactEmail: "olivia.reyes@mindmed.co",
      isActive: true,
      brandingId: null,
    },
    {
      ticker: "ADPT",
      companyName: "Adaptive Biotechnologies Corporation",
      shortName: "Adaptive Biotech",
      industry: "Biotechnology",
      description: "Immune-driven medicine using sequencing and machine learning",
      website: "https://www.adaptivebiotech.com",
      primaryContact: "Francis Kim",
      primaryContactEmail: "francis.kim@adaptivebiotech.com",
      isActive: true,
      brandingId: null,
    },
  ],

  // Account configurations (now separated from clients)
  accounts: [
    {
      clientTicker: "WEN",
      accountName: "The Wendy's Company",
      primaryContact: "Mike Chen",
      cusip: "95058W100",
      totalSharesOutstanding: 196234142,
      quorumRequirement: 50.0,
      brokerNonVote: 22480600.0,
    },
    {
      clientTicker: "FOC",
      accountName: "FocalPoint",
      primaryContact: "Tim Morgan",
      cusip: "95058W100",
      totalSharesOutstanding: 196234142,
      quorumRequirement: 50.0,
      brokerNonVote: 22480600.0,
    },
    {
      clientTicker: "PAYC",
      accountName: "Paycom Software, Inc.",
      primaryContact: "Lisa Rodriguez",
      cusip: "70432V102",
      totalSharesOutstanding: 57852318,
      quorumRequirement: 33.33,
      brokerNonVote: 7412199.85,
    },
    {
      clientTicker: "WWD",
      accountName: "Woodward, Inc.",
      primaryContact: "David Kim",
      cusip: "980745103",
      totalSharesOutstanding: 59402491,
      quorumRequirement: 50.0,
      brokerNonVote: 5855516.89,
    },
    {
      clientTicker: "ELVN",
      accountName: "Enliven Therapeutics, Inc.",
      primaryContact: "Jenny Patel",
      cusip: "29337E102",
      totalSharesOutstanding: 49066008,
      quorumRequirement: 50.0,
      brokerNonVote: 3635711.0,
    },
    {
      clientTicker: "JPMR",
      accountName: "J.P. Morgan Real Estate Income Trust, Inc.",
      primaryContact: "Amanda Clarke",
      cusip: "46625H100",
      totalSharesOutstanding: 210000000,
      quorumRequirement: 33.33,
      brokerNonVote: 21000000.0,
    },
    {
      clientTicker: "ETWO",
      accountName: "E2open Parent Holdings Inc.",
      primaryContact: "Marcus Webb",
      cusip: "29089A109",
      totalSharesOutstanding: 348000000,
      quorumRequirement: 33.33,
      brokerNonVote: 34800000.0,
    },
    {
      clientTicker: "CHH",
      accountName: "Champion Homes, Inc.",
      primaryContact: "Rachel Torres",
      cusip: "12589K105",
      totalSharesOutstanding: 58600000,
      quorumRequirement: 33.33,
      brokerNonVote: 5860000.0,
    },
    {
      clientTicker: "BCSF",
      accountName: "Bain Capital Specialty Finance, Inc.",
      primaryContact: "Steven Park",
      cusip: "05683Q106",
      totalSharesOutstanding: 23400000,
      quorumRequirement: 33.33,
      brokerNonVote: 2340000.0,
    },
    {
      clientTicker: "STTK",
      accountName: "Shattuck Labs, Inc.",
      primaryContact: "Olivia Grant",
      cusip: "82082C109",
      totalSharesOutstanding: 44800000,
      quorumRequirement: 50.0,
      brokerNonVote: 4480000.0,
    },
    {
      clientTicker: "NOMD",
      accountName: "Nomad Foods Limited",
      primaryContact: "Thomas Hardy",
      cusip: "G6518J109",
      totalSharesOutstanding: 240000000,
      quorumRequirement: 33.33,
      brokerNonVote: 24000000.0,
    },
    {
      clientTicker: "QRHC",
      accountName: "Quest Resource Holding Corporation",
      primaryContact: "Diana Foster",
      cusip: "74842P100",
      totalSharesOutstanding: 23200000,
      quorumRequirement: 33.33,
      brokerNonVote: 2320000.0,
    },
    {
      clientTicker: "ICU",
      accountName: "SeaStar Medical Holding Corporation",
      primaryContact: "Brian Nguyen",
      cusip: "81115A103",
      totalSharesOutstanding: 12500000,
      quorumRequirement: 50.0,
      brokerNonVote: 1250000.0,
    },
    {
      clientTicker: "CTNM",
      accountName: "Contineum Therapeutics, Inc.",
      primaryContact: "Priya Sharma",
      cusip: "20569D106",
      totalSharesOutstanding: 58200000,
      quorumRequirement: 50.0,
      brokerNonVote: 5820000.0,
    },
    {
      clientTicker: "FULC",
      accountName: "Fulcrum Therapeutics, Inc.",
      primaryContact: "Kevin Walsh",
      cusip: "35953G101",
      totalSharesOutstanding: 50100000,
      quorumRequirement: 50.0,
      brokerNonVote: 5010000.0,
    },
    {
      clientTicker: "LCTX",
      accountName: "Lineage Cell Therapeutics, Inc.",
      primaryContact: "Sarah Quinn",
      cusip: "53593Q101",
      totalSharesOutstanding: 60400000,
      quorumRequirement: 33.33,
      brokerNonVote: 6040000.0,
    },
    {
      clientTicker: "INZY",
      accountName: "Inozyme Pharma, Inc.",
      primaryContact: "Robert Ellis",
      cusip: "45736Y100",
      totalSharesOutstanding: 35800000,
      quorumRequirement: 50.0,
      brokerNonVote: 3580000.0,
    },
    {
      clientTicker: "SPRY",
      accountName: "ARS Pharmaceuticals, Inc.",
      primaryContact: "Nina Carroll",
      cusip: "00212H107",
      totalSharesOutstanding: 75200000,
      quorumRequirement: 33.33,
      brokerNonVote: 7520000.0,
    },
    {
      clientTicker: "GOSS",
      accountName: "Gossamer Bio, Inc.",
      primaryContact: "Ethan Murphy",
      cusip: "38388L100",
      totalSharesOutstanding: 50600000,
      quorumRequirement: 50.0,
      brokerNonVote: 5060000.0,
    },
    {
      clientTicker: "AFRM",
      accountName: "Affirm Holdings Inc.",
      primaryContact: "Megan Lawson",
      cusip: "00827B106",
      totalSharesOutstanding: 352000000,
      quorumRequirement: 33.33,
      brokerNonVote: 35200000.0,
    },
    {
      clientTicker: "ALGS",
      accountName: "Aligos Therapeutics, Inc.",
      primaryContact: "James Norton",
      cusip: "01626T107",
      totalSharesOutstanding: 40300000,
      quorumRequirement: 50.0,
      brokerNonVote: 4030000.0,
    },
    {
      clientTicker: "ERAS",
      accountName: "Erasca, Inc.",
      primaryContact: "Laura Peterson",
      cusip: "29602M102",
      totalSharesOutstanding: 175000000,
      quorumRequirement: 33.33,
      brokerNonVote: 17500000.0,
    },
    {
      clientTicker: "IDYA",
      accountName: "IDEAYA Biosciences, Inc.",
      primaryContact: "Carlos Reyes",
      cusip: "45168D104",
      totalSharesOutstanding: 74800000,
      quorumRequirement: 50.0,
      brokerNonVote: 7480000.0,
    },
    {
      clientTicker: "CALC",
      accountName: "CalciMedica, Inc.",
      primaryContact: "Angela Brooks",
      cusip: "12812A100",
      totalSharesOutstanding: 25100000,
      quorumRequirement: 50.0,
      brokerNonVote: 2510000.0,
    },
    {
      clientTicker: "ARTV",
      accountName: "Artiva Biotherapeutics, Inc.",
      primaryContact: "Daniel Cho",
      cusip: "04316A103",
      totalSharesOutstanding: 70200000,
      quorumRequirement: 33.33,
      brokerNonVote: 7020000.0,
    },
    {
      clientTicker: "HLVX",
      accountName: "HilleVax, Inc.",
      primaryContact: "Michelle Adams",
      cusip: "43230T107",
      totalSharesOutstanding: 35400000,
      quorumRequirement: 50.0,
      brokerNonVote: 3540000.0,
    },
    {
      clientTicker: "TBIO",
      accountName: "Telesis Bio Inc.",
      primaryContact: "Jason Powell",
      cusip: "87972K107",
      totalSharesOutstanding: 30800000,
      quorumRequirement: 50.0,
      brokerNonVote: 3080000.0,
    },
    {
      clientTicker: "BBIO",
      accountName: "Boundless Big Inc.",
      primaryContact: "Stephanie Lee",
      cusip: "10213B109",
      totalSharesOutstanding: 40500000,
      quorumRequirement: 50.0,
      brokerNonVote: 4050000.0,
    },
    {
      clientTicker: "LAC",
      accountName: "Lithium Americas Corp.",
      primaryContact: "Gregory Stone",
      cusip: "53668G102",
      totalSharesOutstanding: 295000000,
      quorumRequirement: 33.33,
      brokerNonVote: 29500000.0,
    },
    {
      clientTicker: "WAL",
      accountName: "Western Alliance Bancorporation",
      primaryContact: "Patricia Young",
      cusip: "95828W101",
      totalSharesOutstanding: 102000000,
      quorumRequirement: 33.33,
      brokerNonVote: 10200000.0,
    },
    {
      clientTicker: "PTLO",
      accountName: "Portillo's Inc.",
      primaryContact: "Christopher Hall",
      cusip: "73739P109",
      totalSharesOutstanding: 50300000,
      quorumRequirement: 33.33,
      brokerNonVote: 5030000.0,
    },
    {
      clientTicker: "MDLZ",
      accountName: "Mondelez International, Inc.",
      primaryContact: "Frances Mitchell",
      cusip: "609207105",
      totalSharesOutstanding: 1310000000,
      quorumRequirement: 33.33,
      brokerNonVote: 131000000.0,
    },
    {
      clientTicker: "INAB",
      accountName: "IN8bio, Inc.",
      primaryContact: "Jonathan White",
      cusip: "45268H105",
      totalSharesOutstanding: 40800000,
      quorumRequirement: 50.0,
      brokerNonVote: 4080000.0,
    },
    {
      clientTicker: "TOI",
      accountName: "The Oncology Institute, Inc.",
      primaryContact: "Katherine Brown",
      cusip: "87340G100",
      totalSharesOutstanding: 35200000,
      quorumRequirement: 50.0,
      brokerNonVote: 3520000.0,
    },
    {
      clientTicker: "AZTR",
      accountName: "Azitra, Inc.",
      primaryContact: "William Turner",
      cusip: "05464R105",
      totalSharesOutstanding: 15600000,
      quorumRequirement: 50.0,
      brokerNonVote: 1560000.0,
    },
    {
      clientTicker: "SONM",
      accountName: "Sonim Technologies, Inc.",
      primaryContact: "Sandra Rivera",
      cusip: "83543D109",
      totalSharesOutstanding: 20400000,
      quorumRequirement: 50.0,
      brokerNonVote: 2040000.0,
    },
    {
      clientTicker: "PCOR",
      accountName: "Procore Technologies, Inc.",
      primaryContact: "Timothy Evans",
      cusip: "74275T101",
      totalSharesOutstanding: 402000000,
      quorumRequirement: 33.33,
      brokerNonVote: 40200000.0,
    },
    {
      clientTicker: "PHX",
      accountName: "PHX Minerals Inc.",
      primaryContact: "Dorothy Collins",
      cusip: "69327L101",
      totalSharesOutstanding: 40100000,
      quorumRequirement: 33.33,
      brokerNonVote: 4010000.0,
    },
    {
      clientTicker: "AMTB",
      accountName: "Amerant Bancorp Inc.",
      primaryContact: "Harold Stewart",
      cusip: "02363E108",
      totalSharesOutstanding: 30200000,
      quorumRequirement: 33.33,
      brokerNonVote: 3020000.0,
    },
    {
      clientTicker: "SLGC",
      accountName: "SomaLogic, Inc.",
      primaryContact: "Rebecca Morris",
      cusip: "83484E106",
      totalSharesOutstanding: 180000000,
      quorumRequirement: 33.33,
      brokerNonVote: 18000000.0,
    },
    {
      clientTicker: "CD",
      accountName: "Chindata Group Holdings Ltd.",
      primaryContact: "Andrew Huang",
      cusip: "16948Q103",
      totalSharesOutstanding: 500000000,
      quorumRequirement: 33.33,
      brokerNonVote: 50000000.0,
    },
    {
      clientTicker: "FREQ",
      accountName: "Frequency Therapeutics Inc.",
      primaryContact: "Natalie Scott",
      cusip: "35842L102",
      totalSharesOutstanding: 50900000,
      quorumRequirement: 50.0,
      brokerNonVote: 5090000.0,
    },
    {
      clientTicker: "AMAM",
      accountName: "Ambrx Biopharma, Inc.",
      primaryContact: "Vincent Cooper",
      cusip: "02316A100",
      totalSharesOutstanding: 100000000,
      quorumRequirement: 33.33,
      brokerNonVote: 10000000.0,
    },
    {
      clientTicker: "ILG",
      accountName: "ILG Acquisition One Corp.",
      primaryContact: "Margaret Bell",
      cusip: "45006C107",
      totalSharesOutstanding: 10000000,
      quorumRequirement: 50.0,
      brokerNonVote: 1000000.0,
    },
    {
      clientTicker: "ENRS",
      accountName: "EnerSa",
      primaryContact: "Thomas Grant",
      cusip: "29278N100",
      totalSharesOutstanding: 75000000,
      quorumRequirement: 33.33,
      brokerNonVote: 7500000.0,
    },
    {
      clientTicker: "EHAB",
      accountName: "Enhabit, Inc.",
      primaryContact: "Sandra Diaz",
      cusip: "29255V100",
      totalSharesOutstanding: 32000000,
      quorumRequirement: 33.33,
      brokerNonVote: 3200000.0,
    },
    {
      clientTicker: "VANI",
      accountName: "Vivani Medical, Inc.",
      primaryContact: "Christine Huang",
      cusip: "92847V103",
      totalSharesOutstanding: 18000000,
      quorumRequirement: 33.33,
      brokerNonVote: 1800000.0,
    },
    {
      clientTicker: "MDGL",
      accountName: "Madrigal Pharmaceuticals, Inc.",
      primaryContact: "Brian Walsh",
      cusip: "55826T103",
      totalSharesOutstanding: 28000000,
      quorumRequirement: 33.33,
      brokerNonVote: 2800000.0,
    },
    {
      clientTicker: "CBNA",
      accountName: "Chain Bridge Bancorp, Inc.",
      primaryContact: "Patricia Lane",
      cusip: "15734M108",
      totalSharesOutstanding: 12000000,
      quorumRequirement: 50.0,
      brokerNonVote: 1200000.0,
    },
    {
      clientTicker: "INTT",
      accountName: "inTEST Corporation",
      primaryContact: "Robert Nguyen",
      cusip: "46071W104",
      totalSharesOutstanding: 14000000,
      quorumRequirement: 33.33,
      brokerNonVote: 1400000.0,
    },
    {
      clientTicker: "DFIN",
      accountName: "Donnelley Financial Solutions, Inc.",
      primaryContact: "Katherine Owens",
      cusip: "25788G100",
      totalSharesOutstanding: 33000000,
      quorumRequirement: 33.33,
      brokerNonVote: 3300000.0,
    },
    {
      clientTicker: "VAPO",
      accountName: "Vapotherm, Inc.",
      primaryContact: "James Thornton",
      cusip: "921745102",
      totalSharesOutstanding: 22000000,
      quorumRequirement: 33.33,
      brokerNonVote: 2200000.0,
    },
    {
      clientTicker: "SQZ",
      accountName: "SQZ Biotech",
      primaryContact: "Allison Murphy",
      cusip: "78470H103",
      totalSharesOutstanding: 16000000,
      quorumRequirement: 33.33,
      brokerNonVote: 1600000.0,
    },
    {
      clientTicker: "NEX",
      accountName: "NexTier Oilfield Solutions Inc.",
      primaryContact: "Derek Simmons",
      cusip: "65342V105",
      totalSharesOutstanding: 185000000,
      quorumRequirement: 50.0,
      brokerNonVote: 18500000.0,
    },
    {
      clientTicker: "MNMD",
      accountName: "Mind Medicine (MindMed) Inc.",
      primaryContact: "Olivia Reyes",
      cusip: "60255P108",
      totalSharesOutstanding: 175000000,
      quorumRequirement: 33.33,
      brokerNonVote: 17500000.0,
    },
    {
      clientTicker: "ADPT",
      accountName: "Adaptive Biotechnologies Corporation",
      primaryContact: "Francis Kim",
      cusip: "00648M102",
      totalSharesOutstanding: 120000000,
      quorumRequirement: 33.33,
      brokerNonVote: 12000000.0,
    },
  ],

  // User configurations
  users: {
    developer: {
      username: "dev.user",
      firstName: "Dev",
      lastName: "User",
      email: "dev@betanxt.com",
      type: "ADMIN",
    },
    test: {
      username: "test.user",
      firstName: "Test",
      lastName: "User",
      email: "test@betanxt.com",
      type: "ADMIN",
    },
    relationshipManager: {
      username: "sarah.johnson",
      firstName: "Sarah",
      lastName: "Johnson",
      email: "sarah.johnson@betanxt.com",
      type: "RELATIONSHIP_MANAGER",
    },
    /** Must match issuer-portal/auth.ts mockUsers["csm.user"].id */
    csm: {
      id: "h7c1628g-65hc-1ji7-h74i-9e66i1596kgh",
      username: "csm.user",
      firstName: "Casey",
      lastName: "Smith",
      email: "csm.user@betanxt.com",
      type: "CSM",
    },
    issuerUsers: [
      {
        username: "mike.chen",
        firstName: "Mike",
        lastName: "Chen",
        email: "mike.chen@wendys.com",
        type: "ADMIN",
        company: "The Wendy's Company",
      },
      {
        username: "tim",
        firstName: "Tim",
        lastName: "Morgan",
        email: "tim@focalpoint.com",
        type: "ISSUER",
        company: "FocalPoint",
      },
      {
        username: "lisa.rodriguez",
        firstName: "Lisa",
        lastName: "Rodriguez",
        email: "lisa.rodriguez@paycom.com",
        type: "ISSUER",
        company: "Paycom Software, Inc.",
      },
      {
        username: "david.kim",
        firstName: "David",
        lastName: "Kim",
        email: "david.kim@woodward.com",
        type: "ADMIN",
        company: "Woodward, Inc.",
      },
      {
        username: "jenny.patel",
        firstName: "Jenny",
        lastName: "Patel",
        email: "jenny.patel@enliven.com",
        type: "ISSUER",
        company: "Enliven Therapeutics, Inc.",
      },
    ],
  },

  // Seed data parameters
  seedParams: {
    positionCount: 15000,
    userActivityVariation: true,
    includeHistoricalPatterns: true,
    randomSeed: 12345,
    generateVotes: true,
  },

  // CSV data files - Three files per company minimum
  csvFiles: {
    // Wendy's data files
    wendysMeetingInfo: "../data/wendys_meeting_info.csv",
    wendysProposals: "../data/wendys_proposals.csv",
    wendysPositions: "../data/wendys_positions_2025.csv",
    wendysDTC: "../data/wendys_dtc_vote_status.csv",
    wendysNonDTC: "../data/wendys_non_dtc_vote_status.csv",
    // Enliven data files
    enlivenMeetingInfo: "../data/enliven_meeting_info.csv",
    enlivenProposals: "../data/enliven_proposals_2025.csv",
    enlivenPositions: "../data/enliven_positions_2025.csv",
    enlivenDTC: "../data/enliven_dtc_vote_status.csv",
    enlivenNonDTC: "../data/enliven_non_dtc_vote_status.csv",
    // Paycom data files
    paycomMeetingInfo: "../data/paycom_meeting_info.csv",
    paycomProposals: "../data/paycom_proposals_2025.csv",
    paycomPositions: "../data/paycom_positions_2025.csv",
    paycomDTC: "../data/paycom_dtc_vote_status.csv",
    paycomNonDTC: "../data/paycom_non_dtc_vote_status.csv",
    // Woodward data files
    woodwardMeetingInfo: "../data/woodward_meeting_info.csv",
    woodwardProposals: "../data/woodward_proposals_2025.csv",
    woodwardPositions: "../data/woodward_positions_2025.csv",
    woodwardDTC: "../data/woodward_dtc_vote_status.csv",
    woodwardNonDTC: "../data/woodward_non_dtc_vote_status.csv",
  },
};
