/**
 * Auto-generated brand configuration for event companies.
 * Generated by: npx tsx issuer-portal/scripts/fetch-brands.ts
 * Do not edit manually — re-run the script to update.
 */

export interface BrandConfig {
  companyName: string
  domain: string
  logoPath: string
  iconPath: string
  primaryColor: string
  secondaryColor: string
}

export const brandConfigs: Record<string, BrandConfig> = {

}

/** Look up brand config by event/company name */
export function getBrandConfig(companyName: string): BrandConfig | null {
  return brandConfigs[companyName] ?? null
}

/** Get the logo path for a company, with fallback */
export function getBrandLogoPath(companyName: string, fallback = '/images/logo.svg'): string {
  return brandConfigs[companyName]?.logoPath || fallback
}

/** Get the icon path for a company, with fallback */
export function getBrandIconPath(companyName: string, fallback = '/images/logo.svg'): string {
  return brandConfigs[companyName]?.iconPath || fallback
}
