/**
 * Auto-generated brand configuration for event companies.
 * Generated by: npx tsx issuer-portal/scripts/fetch-brands.ts
 * Do not edit manually — re-run the script to update.
 */

export interface BrandConfig {
  companyName: string
  domain: string
  logoPath: string
  iconPath: string
  primaryColor: string
  secondaryColor: string
}

export const brandConfigs: Record<string, BrandConfig> = {
  'J.P. Morgan Real Estate Income Trust, Inc.': {
    companyName: 'J.P. Morgan',
    domain: 'jpmorgan.com',
    logoPath: '/logos/brands/j-p-morgan-real-estate-income-trust-inc_logo.svg',
    iconPath: '/logos/brands/j-p-morgan-real-estate-income-trust-inc_icon.png',
    primaryColor: '#936845',
    secondaryColor: '#31373D',
  },
  'E2open Parent Holdings Inc.': {
    companyName: 'e2open',
    domain: 'e2open.com',
    logoPath: '/logos/brands/e2open-parent-holdings-inc_logo.svg',
    iconPath: '/logos/brands/e2open-parent-holdings-inc_icon.png',
    primaryColor: '#A3CA8C',
    secondaryColor: '#282828',
  },
  'Champion Homes, Inc.': {
    companyName: 'Champion Homes',
    domain: 'championhomes.com',
    logoPath: '/logos/brands/champion-homes-inc_logo.png',
    iconPath: '/logos/brands/champion-homes-inc_icon.png',
    primaryColor: '#19516c',
    secondaryColor: '#02426e',
  },
  'Bain Capital Specialty Finance, Inc': {
    companyName: 'Bain Capital',
    domain: 'baincapital.com',
    logoPath: '/logos/brands/bain-capital-specialty-finance-inc_logo.svg',
    iconPath: '/logos/brands/bain-capital-specialty-finance-inc_icon.png',
    primaryColor: '#e52823',
    secondaryColor: '#1b215a',
  },
  'Shattuck Labs, Inc.': {
    companyName: 'Shattuck Labs',
    domain: 'shattucklabs.com',
    logoPath: '/logos/brands/shattuck-labs-inc_logo.svg',
    iconPath: '/logos/brands/shattuck-labs-inc_icon.png',
    primaryColor: '#0ea9c5',
    secondaryColor: '#006885',
  },
  'Nomad Foods Limited': {
    companyName: 'Nomad Foods',
    domain: 'nomadfoods.com',
    logoPath: '/logos/brands/nomad-foods-limited_logo.png',
    iconPath: '/logos/brands/nomad-foods-limited_icon.png',
    primaryColor: '#005186',
    secondaryColor: '#4f3e2c',
  },
  'Quest Resource Holding Corporation': {
    companyName: 'Quest Resource Management Group',
    domain: 'questrmg.com',
    logoPath: '/logos/brands/quest-resource-holding-corporation_logo.png',
    iconPath: '/logos/brands/quest-resource-holding-corporation_icon.png',
    primaryColor: '#0067b1',
    secondaryColor: '#0d3966',
  },
  'SeaStar Medical Holding Corporation': {
    companyName: 'SeaStarMedical',
    domain: 'seastarmedical.com',
    logoPath: '/logos/brands/seastar-medical-holding-corporation_logo.png',
    iconPath: '/logos/brands/seastar-medical-holding-corporation_icon.png',
    primaryColor: '#316b7f',
    secondaryColor: '#035c67',
  },
  'Contineum Therapeutics, Inc.': {
    companyName: 'Contineum Therapeutics, Inc.',
    domain: 'contineum.com',
    logoPath: '',
    iconPath: '',
    primaryColor: '#333333',
    secondaryColor: '#333333',
  },
  'Fulcrum Therapeutics, InG.': {
    companyName: 'FulcrumTx',
    domain: 'fulcrumtx.com',
    logoPath: '/logos/brands/fulcrum-therapeutics-ing_logo.svg',
    iconPath: '/logos/brands/fulcrum-therapeutics-ing_icon.png',
    primaryColor: '#49c7ed',
    secondaryColor: '#42453a',
  },
  'Lineage Cell Therapeutics, Inc.': {
    companyName: 'Lineage Cell Therapeutics',
    domain: 'lineagecell.com',
    logoPath: '/logos/brands/lineage-cell-therapeutics-inc_logo.svg',
    iconPath: '/logos/brands/lineage-cell-therapeutics-inc_icon.png',
    primaryColor: '#339ef0',
    secondaryColor: '#000a2b',
  },
  'Inozyme Pharma, Ins.': {
    companyName: 'Inozyme Pharma',
    domain: 'inozyme.com',
    logoPath: '/logos/brands/inozyme-pharma-ins_logo.png',
    iconPath: '/logos/brands/inozyme-pharma-ins_icon.png',
    primaryColor: '#1f355c',
    secondaryColor: '#285d7f',
  },
  'ARS Pharmaceuticals, Inc.': {
    companyName: 'ARS Pharmaceuticals',
    domain: 'ars-pharma.com',
    logoPath: '/logos/brands/ars-pharmaceuticals-inc_logo.png',
    iconPath: '/logos/brands/ars-pharmaceuticals-inc_icon.png',
    primaryColor: '#72b8cd',
    secondaryColor: '#003d68',
  },
  'Gossamer Bio, Inc.': {
    companyName: 'Gossamer Bio',
    domain: 'gossamerbio.com',
    logoPath: '/logos/brands/gossamer-bio-inc_logo.png',
    iconPath: '/logos/brands/gossamer-bio-inc_icon.png',
    primaryColor: '#b6e3d4',
    secondaryColor: '#2b5563',
  },
  'Affirm Holdings Inc.': {
    companyName: 'Affirm',
    domain: 'affirm.com',
    logoPath: '/logos/brands/affirm-holdings-inc_logo.svg',
    iconPath: '/logos/brands/affirm-holdings-inc_icon.png',
    primaryColor: '#2F2FC1',
    secondaryColor: '#101820',
  },
  'Aligos Therapeutics, Inc.': {
    companyName: 'Aligos Therapeutics',
    domain: 'aligos.com',
    logoPath: '/logos/brands/aligos-therapeutics-inc_logo.png',
    iconPath: '/logos/brands/aligos-therapeutics-inc_icon.png',
    primaryColor: '#7fa9d1',
    secondaryColor: '#524220',
  },
  'Enliven Therapeutics, Inc.': {
    companyName: 'Enliven TX',
    domain: 'enliventx.com',
    logoPath: '/logos/brands/enliven-therapeutics-inc_logo.png',
    iconPath: '/logos/brands/enliven-therapeutics-inc_icon.png',
    primaryColor: '#0f95d6',
    secondaryColor: '#013e74',
  },
  'Erasca, Inc.': {
    companyName: 'Erasca',
    domain: 'erasca.com',
    logoPath: '/logos/brands/erasca-inc_logo.svg',
    iconPath: '/logos/brands/erasca-inc_icon.png',
    primaryColor: '#33a7b5',
    secondaryColor: '#004a59',
  },
  'IDEAYA Biosciences, Inc': {
    companyName: 'IDEAYA Biosciences',
    domain: 'ideayabio.com',
    logoPath: '/logos/brands/ideaya-biosciences-inc_logo.svg',
    iconPath: '/logos/brands/ideaya-biosciences-inc_icon.png',
    primaryColor: '#e82c26',
    secondaryColor: '#2e294e',
  },
  'CalciMedica, Inc.': {
    companyName: 'CalciMedica',
    domain: 'calcimedica.com',
    logoPath: '/logos/brands/calcimedica-inc_logo.png',
    iconPath: '/logos/brands/calcimedica-inc_icon.png',
    primaryColor: '#472f91',
    secondaryColor: '#070101',
  },
  'Artiva Biotherapeutics, Inc.': {
    companyName: 'ArtivaBio',
    domain: 'artivabio.com',
    logoPath: '/logos/brands/artiva-biotherapeutics-inc_logo.png',
    iconPath: '/logos/brands/artiva-biotherapeutics-inc_icon.png',
    primaryColor: '#c63563',
    secondaryColor: '#0c3c53',
  },
  'HilleVax, Inc.': {
    companyName: 'HilleVax',
    domain: 'hillevax.com',
    logoPath: '/logos/brands/hillevax-inc_logo.png',
    iconPath: '/logos/brands/hillevax-inc_icon.png',
    primaryColor: '#20b66d',
    secondaryColor: '#163957',
  },
  'Telesis Bio Inc.': {
    companyName: 'Telesis Bio',
    domain: 'telesisbio.com',
    logoPath: '/logos/brands/telesis-bio-inc_logo.svg',
    iconPath: '/logos/brands/telesis-bio-inc_icon.png',
    primaryColor: '#d7176f',
    secondaryColor: '#255fc0',
  },
  'Boundless Big Inc.': {
    companyName: 'Boundless Bio',
    domain: 'boundlessbio.com',
    logoPath: '/logos/brands/boundless-big-inc_logo.png',
    iconPath: '/logos/brands/boundless-big-inc_icon.png',
    primaryColor: '#ff4d29',
    secondaryColor: '#ff4d29',
  },
  'Lithium Americas Corp.': {
    companyName: 'Lithium Americas',
    domain: 'lithiumamericas.com',
    logoPath: '/logos/brands/lithium-americas-corp_logo.svg',
    iconPath: '/logos/brands/lithium-americas-corp_icon.png',
    primaryColor: '#00638D',
    secondaryColor: '#231F20',
  },
  'Western Alliance Bancorporation': {
    companyName: 'Western Alliance Bank',
    domain: 'westernalliancebank.com',
    logoPath: '/logos/brands/western-alliance-bancorporation_logo.svg',
    iconPath: '/logos/brands/western-alliance-bancorporation_icon.png',
    primaryColor: '#003256',
    secondaryColor: '#05233d',
  },
  "Portillo's Inc.": {
    companyName: "Portillo's",
    domain: 'portillos.com',
    logoPath: '/logos/brands/portillo-s-inc_logo.svg',
    iconPath: '/logos/brands/portillo-s-inc_icon.png',
    primaryColor: '#DD0B17',
    secondaryColor: '#000000',
  },
  'Mondelez International, Inc.': {
    companyName: 'Mondelēz International',
    domain: 'mondelezinternational.com',
    logoPath: '/logos/brands/mondelez-international-inc_logo.svg',
    iconPath: '/logos/brands/mondelez-international-inc_icon.png',
    primaryColor: '#287819',
    secondaryColor: '#4F2170',
  },
  'Donnelley Financial Solutions, Inc.': {
    companyName: 'Donnelley Financial Solutions (DFIN)',
    domain: 'dfinsolutions.com',
    logoPath: '/logos/brands/donnelley-financial-solutions-inc_logo.svg',
    iconPath: '/logos/brands/donnelley-financial-solutions-inc_icon.png',
    primaryColor: '#00FFBC',
    secondaryColor: '#2d235a',
  },
  'IN8bio, Inc.': {
    companyName: 'IN8bio',
    domain: 'in8bio.com',
    logoPath: '/logos/brands/in8bio-inc_logo.png',
    iconPath: '/logos/brands/in8bio-inc_icon.png',
    primaryColor: '#0693e3',
    secondaryColor: '#1a35aa',
  },
  'The Oncology Institute, Inc.': {
    companyName: 'Oncology Institute',
    domain: 'theoncologyinstitute.com',
    logoPath: '/logos/brands/the-oncology-institute-inc_logo.png',
    iconPath: '/logos/brands/the-oncology-institute-inc_icon.png',
    primaryColor: '#479ab8',
    secondaryColor: '#203d4d',
  },
  'Azitra, Inc.': {
    companyName: 'Azitra',
    domain: 'azitra.com',
    logoPath: '/logos/brands/azitra-inc_logo.png',
    iconPath: '/logos/brands/azitra-inc_icon.png',
    primaryColor: '#325ca2',
    secondaryColor: '#111111',
  },
  'Woodward, Inc.': {
    companyName: 'Woodward',
    domain: 'woodward.com',
    logoPath: '/logos/brands/woodward-inc_logo.svg',
    iconPath: '/logos/brands/woodward-inc_icon.png',
    primaryColor: '#6d6e71',
    secondaryColor: '#800001',
  },
  'Sonim Technologies, Inc.': {
    companyName: 'Sonim Technologies',
    domain: 'sonimtech.com',
    logoPath: '/logos/brands/sonim-technologies-inc_logo.png',
    iconPath: '/logos/brands/sonim-technologies-inc_icon.png',
    primaryColor: '#d12030',
    secondaryColor: '#000000',
  },
  'PROCORE TECHNOLOGIES, INC': {
    companyName: 'Procore',
    domain: 'procore.com',
    logoPath: '/logos/brands/procore-technologies-inc_logo.svg',
    iconPath: '/logos/brands/procore-technologies-inc_icon.png',
    primaryColor: '#FF5201',
    secondaryColor: '#1A202C',
  },
  'PHX Minerals Inc.': {
    companyName: 'PHX Minerals Inc.',
    domain: 'phxmin.com',
    logoPath: '/logos/brands/phx-minerals-inc_logo.svg',
    iconPath: '/logos/brands/phx-minerals-inc_icon.svg',
    primaryColor: '#67737a',
    secondaryColor: '#111921',
  },
  'Donnelley Financial Solutions Inc.': {
    companyName: 'Donnelley Financial Solutions (DFIN)',
    domain: 'dfinsolutions.com',
    logoPath: '/logos/brands/donnelley-financial-solutions-inc_logo.svg',
    iconPath: '/logos/brands/donnelley-financial-solutions-inc_icon.png',
    primaryColor: '#00FFBC',
    secondaryColor: '#2d235a',
  },
  'Amerant Bancorp Inc.': {
    companyName: 'Amerant Bank',
    domain: 'amerantbank.com',
    logoPath: '/logos/brands/amerant-bancorp-inc_logo.png',
    iconPath: '/logos/brands/amerant-bancorp-inc_icon.png',
    primaryColor: '#e6631e',
    secondaryColor: '#003c71',
  },
  'SomaLogic, Inc.': {
    companyName: 'SomaLogic',
    domain: 'somalogic.com',
    logoPath: '/logos/brands/somalogic-inc_logo.png',
    iconPath: '/logos/brands/somalogic-inc_icon.png',
    primaryColor: '#3f3479',
    secondaryColor: '#24135f',
  },
  'Chindata Group Holdings Ltd': {
    companyName: 'Chindata Group',
    domain: 'chindatagroup.com',
    logoPath: '/logos/brands/chindata-group-holdings-ltd_logo.png',
    iconPath: '/logos/brands/chindata-group-holdings-ltd_icon.png',
    primaryColor: '#e60012',
    secondaryColor: '#1959c2',
  },
  'Frequency Therapeutics Inc.': {
    companyName: 'Korro Bio',
    domain: 'frequencytx.com',
    logoPath: '/logos/brands/frequency-therapeutics-inc_logo.png',
    iconPath: '/logos/brands/frequency-therapeutics-inc_icon.png',
    primaryColor: '#f93802',
    secondaryColor: '#121c52',
  },
  'Ambrx Biopharma, Inc.': {
    companyName: 'Ambrx',
    domain: 'ambrx.com',
    logoPath: '/logos/brands/ambrx-biopharma-inc_logo.png',
    iconPath: '/logos/brands/ambrx-biopharma-inc_icon.png',
    primaryColor: '#0c5198',
    secondaryColor: '#0b4f9a',
  },
  'ILG Acquisition One Corp.': {
    companyName: 'ILG Acquisition One Corp.',
    domain: 'ilg.com',
    logoPath: '/logos/brands/ilg-acquisition-one-corp_logo.png',
    iconPath: '/logos/brands/ilg-acquisition-one-corp_icon.png',
    primaryColor: '#017dc7',
    secondaryColor: '#017dc7',
  },
}

/** Look up brand config by event/company name */
export function getBrandConfig(companyName: string): BrandConfig | null {
  return brandConfigs[companyName] ?? null
}

/** Get the logo path for a company, with fallback */
export function getBrandLogoPath(
  companyName: string,
  fallback = '/images/logo.svg'
): string {
  return brandConfigs[companyName]?.logoPath || fallback
}

/** Get the icon path for a company, with fallback */
export function getBrandIconPath(
  companyName: string,
  fallback = '/images/logo.svg'
): string {
  return brandConfigs[companyName]?.iconPath || fallback
}
