/**
 * Brand configuration for event companies.
 * headerLogoPath / headerIconPath: dark-theme assets from Brandfetch (light logos on primary headers).
 * Refresh: npx tsx scripts/fetch-dark-logos.ts
 */

export interface BrandConfig {
  companyName: string;
  ticker?: string;
  domain: string;
  logoPath: string;
  iconPath: string;
  headerLogoPath?: string;
  headerIconPath?: string;
  primaryColor: string;
  secondaryColor: string;
}

export const brandConfigs: Record<string, BrandConfig> = {
  "J.P. Morgan Real Estate Income Trust, Inc.": {
    companyName: "J.P. Morgan",
    domain: "jpmorgan.com",
    iconPath: "/logos/brands/j-p-morgan-real-estate-income-trust-inc_icon.png",
    headerLogoPath:
      "/logos/brands/j-p-morgan-real-estate-income-trust-inc_logo-dark.svg",
    headerIconPath:
      "/logos/brands/j-p-morgan-real-estate-income-trust-inc_icon-dark.png",
    logoPath: "/logos/brands/j-p-morgan-real-estate-income-trust-inc_logo.svg",
    primaryColor: "#936845",
    secondaryColor: "#31373D",
    ticker: "JPMR",
  },
  "E2open Parent Holdings Inc.": {
    companyName: "e2open",
    ticker: "ETWO",
    domain: "e2open.com",
    logoPath: "/logos/brands/e2open-parent-holdings-inc_logo.svg",
    iconPath: "/logos/brands/e2open-parent-holdings-inc_icon.png",
    headerLogoPath: "/logos/brands/e2open-parent-holdings-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/e2open-parent-holdings-inc_icon-dark.png",
    primaryColor: "#A3CA8C",
    secondaryColor: "#282828",
  },
  "Champion Homes, Inc.": {
    companyName: "Champion Homes",
    ticker: "CHH",
    domain: "championhomes.com",
    logoPath: "/logos/brands/champion-homes-inc_logo.png",
    iconPath: "/logos/brands/champion-homes-inc_icon.png",
    headerLogoPath: "/logos/brands/champion-homes-inc_logo-dark.png",
    headerIconPath: "/logos/brands/champion-homes-inc_icon-dark.png",
    primaryColor: "#19516c",
    secondaryColor: "#02426e",
  },
  "Bain Capital Specialty Finance, Inc.": {
    companyName: "Bain Capital",
    ticker: "BCSF",
    domain: "baincapital.com",
    logoPath: "/logos/brands/bain-capital-specialty-finance-inc_logo.svg",
    iconPath: "/logos/brands/bain-capital-specialty-finance-inc_icon.png",
    headerLogoPath:
      "/logos/brands/bain-capital-specialty-finance-inc_logo-dark.svg",
    headerIconPath:
      "/logos/brands/bain-capital-specialty-finance-inc_icon-dark.png",
    primaryColor: "#e52823",
    secondaryColor: "#1b215a",
  },
  "Shattuck Labs, Inc.": {
    companyName: "Shattuck Labs",
    ticker: "STTK",
    domain: "shattucklabs.com",
    logoPath: "/logos/brands/shattuck-labs-inc_logo.svg",
    iconPath: "/logos/brands/shattuck-labs-inc_icon.png",
    headerLogoPath: "/logos/brands/shattuck-labs-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/shattuck-labs-inc_icon-dark.png",
    primaryColor: "#0ea9c5",
    secondaryColor: "#006885",
  },
  "Nomad Foods Limited": {
    companyName: "Nomad Foods",
    ticker: "NOMD",
    domain: "nomadfoods.com",
    logoPath: "/logos/brands/nomad-foods-limited_logo.png",
    iconPath: "/logos/brands/nomad-foods-limited_icon.png",
    headerLogoPath: "/logos/brands/nomad-foods-limited_logo-dark.png",
    headerIconPath: "/logos/brands/nomad-foods-limited_icon-dark.png",
    primaryColor: "#005186",
    secondaryColor: "#4f3e2c",
  },
  "Quest Resource Holding Corporation": {
    companyName: "Quest Resource Management Group",
    ticker: "QRHC",
    domain: "questrmg.com",
    logoPath: "/logos/brands/quest-resource-holding-corporation_logo.png",
    iconPath: "/logos/brands/quest-resource-holding-corporation_icon.png",
    headerLogoPath:
      "/logos/brands/quest-resource-holding-corporation_logo-dark.png",
    headerIconPath:
      "/logos/brands/quest-resource-holding-corporation_icon-dark.png",
    primaryColor: "#0067b1",
    secondaryColor: "#0d3966",
  },
  "SeaStar Medical Holding Corporation": {
    companyName: "SeaStarMedical",
    ticker: "ICU",
    domain: "seastarmedical.com",
    logoPath: "/logos/brands/seastar-medical-holding-corporation_logo.png",
    iconPath: "/logos/brands/seastar-medical-holding-corporation_icon.png",
    headerLogoPath:
      "/logos/brands/seastar-medical-holding-corporation_logo-dark.png",
    headerIconPath:
      "/logos/brands/seastar-medical-holding-corporation_icon-dark.png",
    primaryColor: "#316b7f",
    secondaryColor: "#035c67",
  },
  "Contineum Therapeutics, Inc.": {
    companyName: "Contineum Therapeutics",
    ticker: "CTNM",
    domain: "contineum-tx.com",
    logoPath: "/logos/brands/contineum-therapeutics-inc_logo.svg",
    iconPath: "/logos/brands/contineum-therapeutics-inc_icon.png",
    primaryColor: "#2c5282",
    secondaryColor: "#1a365d",
  },
  "Fulcrum Therapeutics, Inc.": {
    companyName: "FulcrumTx",
    ticker: "FULC",
    domain: "fulcrumtx.com",
    logoPath: "/logos/brands/fulcrum-therapeutics-ing_logo.svg",
    iconPath: "/logos/brands/fulcrum-therapeutics-ing_icon.png",
    headerLogoPath: "/logos/brands/fulcrum-therapeutics-ing_logo-dark.svg",
    headerIconPath: "/logos/brands/fulcrum-therapeutics-ing_icon-dark.png",
    primaryColor: "#49c7ed",
    secondaryColor: "#42453a",
  },
  "Lineage Cell Therapeutics, Inc.": {
    companyName: "Lineage Cell Therapeutics",
    ticker: "LCTX",
    domain: "lineagecell.com",
    logoPath: "/logos/brands/lineage-cell-therapeutics-inc_logo.svg",
    iconPath: "/logos/brands/lineage-cell-therapeutics-inc_icon.png",
    headerLogoPath: "/logos/brands/lineage-cell-therapeutics-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/lineage-cell-therapeutics-inc_icon-dark.png",
    primaryColor: "#339ef0",
    secondaryColor: "#3465CC",
  },
  "Inozyme Pharma, Inc.": {
    companyName: "Inozyme Pharma",
    ticker: "INZY",
    domain: "inozyme.com",
    logoPath: "/logos/brands/inozyme-pharma-ins_logo.png",
    iconPath: "/logos/brands/inozyme-pharma-ins_icon.png",
    headerLogoPath: "/logos/brands/inozyme-pharma-ins_logo-dark.png",
    headerIconPath: "/logos/brands/inozyme-pharma-ins_icon-dark.png",
    primaryColor: "#1f355c",
    secondaryColor: "#285d7f",
  },
  "ARS Pharmaceuticals, Inc.": {
    companyName: "ARS Pharmaceuticals",
    ticker: "SPRY",
    domain: "ars-pharma.com",
    logoPath: "/logos/brands/ars-pharmaceuticals-inc_logo.png",
    iconPath: "/logos/brands/ars-pharmaceuticals-inc_icon.png",
    headerLogoPath: "/logos/brands/ars-pharmaceuticals-inc_logo-dark.png",
    headerIconPath: "/logos/brands/ars-pharmaceuticals-inc_icon-dark.png",
    primaryColor: "#72b8cd",
    secondaryColor: "#003d68",
  },
  "Gossamer Bio, Inc.": {
    companyName: "Gossamer Bio",
    ticker: "GOSS",
    domain: "gossamerbio.com",
    logoPath: "/logos/brands/gossamer-bio-inc_logo.png",
    iconPath: "/logos/brands/gossamer-bio-inc_icon.png",
    headerLogoPath: "/logos/brands/gossamer-bio-inc_logo-dark.png",
    headerIconPath: "/logos/brands/gossamer-bio-inc_icon-dark.png",
    primaryColor: "#2B5563",
    secondaryColor: "#B6E3D4",
  },
  "Affirm Holdings Inc.": {
    companyName: "Affirm",
    ticker: "AFRM",
    domain: "affirm.com",
    logoPath: "/logos/brands/affirm-holdings-inc_logo.svg",
    iconPath: "/logos/brands/affirm-holdings-inc_icon.png",
    headerLogoPath: "/logos/brands/affirm-holdings-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/affirm-holdings-inc_icon-dark.png",
    primaryColor: "#2F2FC1",
    secondaryColor: "#101820",
  },
  "Aligos Therapeutics, Inc.": {
    companyName: "Aligos Therapeutics",
    ticker: "ALGS",
    domain: "aligos.com",
    logoPath: "/logos/brands/aligos-therapeutics-inc_logo.png",
    iconPath: "/logos/brands/aligos-therapeutics-inc_icon.png",
    headerLogoPath: "/logos/brands/aligos-therapeutics-inc_logo-dark.png",
    headerIconPath: "/logos/brands/aligos-therapeutics-inc_icon-dark.png",
    primaryColor: "#7fa9d1",
    secondaryColor: "#524220",
  },
  "Enliven Therapeutics, Inc.": {
    companyName: "Enliven TX",
    ticker: "ELVN",
    domain: "enliventx.com",
    logoPath: "/logos/brands/enliven-therapeutics-inc_logo.png",
    iconPath: "/logos/brands/enliven-therapeutics-inc_icon.png",
    headerLogoPath: "/logos/brands/enliven-therapeutics-inc_logo-dark.png",
    headerIconPath: "/logos/brands/enliven-therapeutics-inc_icon-dark.png",
    primaryColor: "#0f95d6",
    secondaryColor: "#013e74",
  },
  "Erasca, Inc.": {
    companyName: "Erasca",
    ticker: "ERAS",
    domain: "erasca.com",
    logoPath: "/logos/brands/erasca-inc_logo.svg",
    iconPath: "/logos/brands/erasca-inc_icon.png",
    headerLogoPath: "/logos/brands/erasca-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/erasca-inc_icon-dark.png",
    primaryColor: "#33a7b5",
    secondaryColor: "#004a59",
  },
  "IDEAYA Biosciences, Inc.": {
    companyName: "IDEAYA Biosciences",
    ticker: "IDYA",
    domain: "ideayabio.com",
    logoPath: "/logos/brands/ideaya-biosciences-inc_logo.svg",
    iconPath: "/logos/brands/ideaya-biosciences-inc_icon.png",
    headerLogoPath: "/logos/brands/ideaya-biosciences-inc_logo-dark.png",
    headerIconPath: "/logos/brands/ideaya-biosciences-inc_icon-dark.png",
    primaryColor: "#e82c26",
    secondaryColor: "#2e294e",
  },
  "CalciMedica, Inc.": {
    companyName: "CalciMedica",
    ticker: "CALC",
    domain: "calcimedica.com",
    logoPath: "/logos/brands/calcimedica-inc_logo.png",
    iconPath: "/logos/brands/calcimedica-inc_icon.png",
    headerLogoPath: "/logos/brands/calcimedica-inc_logo-dark.png",
    headerIconPath: "/logos/brands/calcimedica-inc_icon-dark.png",
    primaryColor: "#472f91",
    secondaryColor: "#F25B28",
  },
  "Artiva Biotherapeutics, Inc.": {
    companyName: "ArtivaBio",
    ticker: "ARTV",
    domain: "artivabio.com",
    logoPath: "/logos/brands/artiva-biotherapeutics-inc_logo.png",
    iconPath: "/logos/brands/artiva-biotherapeutics-inc_icon.png",
    headerLogoPath: "/logos/brands/artiva-biotherapeutics-inc_logo-dark.png",
    headerIconPath: "/logos/brands/artiva-biotherapeutics-inc_icon-dark.png",
    primaryColor: "#c63563",
    secondaryColor: "#0c3c53",
  },
  "HilleVax, Inc.": {
    companyName: "HilleVax",
    ticker: "HLVX",
    domain: "hillevax.com",
    logoPath: "/logos/brands/hillevax-inc_logo.png",
    iconPath: "/logos/brands/hillevax-inc_icon.png",
    headerLogoPath: "/logos/brands/hillevax-inc_logo-dark.png",
    headerIconPath: "/logos/brands/hillevax-inc_icon-dark.png",
    primaryColor: "#20b66d",
    secondaryColor: "#163957",
  },
  "Telesis Bio Inc.": {
    companyName: "Telesis Bio",
    ticker: "TBIO",
    domain: "telesisbio.com",
    logoPath: "/logos/brands/telesis-bio-inc_logo.svg",
    iconPath: "/logos/brands/telesis-bio-inc_icon.png",
    headerLogoPath: "/logos/brands/telesis-bio-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/telesis-bio-inc_icon-dark.png",
    primaryColor: "#d7176f",
    secondaryColor: "#255fc0",
  },
  "Boundless Big Inc.": {
    companyName: "Boundless Bio",
    ticker: "BBIO",
    domain: "boundlessbio.com",
    logoPath: "/logos/brands/boundless-big-inc_logo.png",
    iconPath: "/logos/brands/boundless-big-inc_icon.png",
    headerLogoPath: "/logos/brands/boundless-big-inc_logo-dark.png",
    headerIconPath: "/logos/brands/boundless-big-inc_icon-dark.png",
    primaryColor: "#FA4D28",
    secondaryColor: "#FA4D28",
  },
  "Lithium Americas Corp.": {
    companyName: "Lithium Americas",
    ticker: "LAC",
    domain: "lithiumamericas.com",
    logoPath: "/logos/brands/lithium-americas-corp_logo.svg",
    iconPath: "/logos/brands/lithium-americas-corp_icon.png",
    headerLogoPath: "/logos/brands/lithium-americas-corp_logo-dark.svg",
    headerIconPath: "/logos/brands/lithium-americas-corp_icon-dark.png",
    primaryColor: "#00638D",
    secondaryColor: "#231F20",
  },
  "Western Alliance Bancorporation": {
    companyName: "Western Alliance Bank",
    ticker: "WAL",
    domain: "westernalliancebank.com",
    logoPath: "/logos/brands/western-alliance-bancorporation_logo.svg",
    iconPath: "/logos/brands/western-alliance-bancorporation_icon.png",
    headerLogoPath:
      "/logos/brands/western-alliance-bancorporation_logo-dark.svg",
    headerIconPath:
      "/logos/brands/western-alliance-bancorporation_icon-dark.png",
    primaryColor: "#003256",
    secondaryColor: "#05233d",
  },
  "Portillo's Inc.": {
    companyName: "Portillo's",
    ticker: "PTLO",
    domain: "portillos.com",
    logoPath: "/logos/brands/portillo-s-inc_logo.svg",
    iconPath: "/logos/brands/portillo-s-inc_icon.png",
    headerLogoPath: "/logos/brands/portillo-s-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/portillo-s-inc_icon-dark.png",
    primaryColor: "#DD0B17",
    secondaryColor: "#000000",
  },
  "Mondelez International, Inc.": {
    companyName: "Mondelēz International",
    ticker: "MDLZ",
    domain: "mondelezinternational.com",
    logoPath: "/logos/brands/mondelez-international-inc_logo.svg",
    iconPath: "/logos/brands/mondelez-international-inc_icon.png",
    headerLogoPath: "/logos/brands/mondelez-international-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/mondelez-international-inc_icon-dark.png",
    primaryColor: "#287819",
    secondaryColor: "#4F2170",
  },
  "IN8bio, Inc.": {
    companyName: "IN8bio",
    ticker: "INAB",
    domain: "in8bio.com",
    logoPath: "/logos/brands/in8bio-inc_logo.png",
    iconPath: "/logos/brands/in8bio-inc_icon.png",
    headerLogoPath: "/logos/brands/in8bio-inc_logo-dark.png",
    headerIconPath: "/logos/brands/in8bio-inc_icon-dark.png",
    primaryColor: "#0693e3",
    secondaryColor: "#1a35aa",
  },
  "The Oncology Institute, Inc.": {
    companyName: "Oncology Institute",
    ticker: "TOI",
    domain: "theoncologyinstitute.com",
    logoPath: "/logos/brands/the-oncology-institute-inc_logo.png",
    iconPath: "/logos/brands/the-oncology-institute-inc_icon.png",
    headerLogoPath: "/logos/brands/the-oncology-institute-inc_logo-dark.png",
    headerIconPath: "/logos/brands/the-oncology-institute-inc_icon-dark.png",
    primaryColor: "#479ab8",
    secondaryColor: "#203d4d",
  },
  "Azitra, Inc.": {
    companyName: "Azitra",
    ticker: "AZTR",
    domain: "azitra.com",
    logoPath: "/logos/brands/azitra-inc_logo.png",
    iconPath: "/logos/brands/azitra-inc_icon.png",
    headerLogoPath: "/logos/brands/azitra-inc_logo-dark.png",
    headerIconPath: "/logos/brands/azitra-inc_icon-dark.png",
    primaryColor: "#325ca2",
    secondaryColor: "#111111",
  },
  "Woodward, Inc.": {
    companyName: "Woodward",
    ticker: "WWD",
    domain: "woodward.com",
    logoPath: "/logos/brands/woodward-inc_logo.svg",
    iconPath: "/logos/brands/woodward-inc_icon.png",
    headerLogoPath: "/logos/brands/woodward-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/woodward-inc_icon-dark.png",
    primaryColor: "#6d6e71",
    secondaryColor: "#800001",
  },
  "Sonim Technologies, Inc.": {
    companyName: "Sonim Technologies",
    ticker: "SONM",
    domain: "sonimtech.com",
    logoPath: "/logos/brands/sonim-technologies-inc_logo.png",
    iconPath: "/logos/brands/sonim-technologies-inc_icon.png",
    headerLogoPath: "/logos/brands/sonim-technologies-inc_logo-dark.png",
    headerIconPath: "/logos/brands/sonim-technologies-inc_icon-dark.png",
    primaryColor: "#d12030",
    secondaryColor: "#000000",
  },
  "Procore Technologies, Inc.": {
    companyName: "Procore",
    ticker: "PCOR",
    domain: "procore.com",
    logoPath: "/logos/brands/procore-technologies-inc_logo.svg",
    iconPath: "/logos/brands/procore-technologies-inc_icon.png",
    headerLogoPath: "/logos/brands/procore-technologies-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/procore-technologies-inc_icon-dark.png",
    primaryColor: "#FF5201",
    secondaryColor: "#1A202C",
  },
  "PHX Minerals Inc.": {
    companyName: "PHX Minerals Inc.",
    ticker: "PHX",
    domain: "phxmin.com",
    logoPath: "/logos/brands/phx-minerals-inc_logo.svg",
    iconPath: "/logos/brands/phx-minerals-inc_icon.svg",
    headerLogoPath: "/logos/brands/phx-minerals-inc_logo-dark.svg",
    headerIconPath: "/logos/brands/phx-minerals-inc_icon-dark.svg",
    primaryColor: "#67737a",
    secondaryColor: "#111921",
  },
  "Donnelley Financial Solutions, Inc.": {
    companyName: "Donnelley Financial Solutions (DFIN)",
    ticker: "DFIN",
    domain: "dfinsolutions.com",
    logoPath: "/logos/brands/donnelley-financial-solutions-inc_logo.svg",
    iconPath: "/logos/brands/donnelley-financial-solutions-inc_icon.png",
    headerLogoPath:
      "/logos/brands/donnelley-financial-solutions-inc_logo-dark.svg",
    headerIconPath:
      "/logos/brands/donnelley-financial-solutions-inc_icon-dark.png",
    primaryColor: "#00FFBC",
    secondaryColor: "#2d235a",
  },
  FocalPoint: {
    companyName: "FocalPoint",
    ticker: "FOC",
    domain: "focalpoint.com",
    logoPath: "/logos/brands/focal-point.svg",
    iconPath: "/logos/brands/focal-point.svg",
    headerLogoPath: "/logos/brands/focal-point_logo-dark.png",
    headerIconPath: "/logos/brands/focal-point_icon-dark.png",
    primaryColor: "#6E28D9",
    secondaryColor: "#28d9b3",
  },
  "Amerant Bancorp Inc.": {
    companyName: "Amerant Bank",
    ticker: "AMTB",
    domain: "amerantbank.com",
    logoPath: "/logos/brands/amerant-bancorp-inc_logo.png",
    iconPath: "/logos/brands/amerant-bancorp-inc_icon.png",
    headerLogoPath: "/logos/brands/amerant-bancorp-inc_logo-dark.png",
    headerIconPath: "/logos/brands/amerant-bancorp-inc_icon-dark.png",
    primaryColor: "#e6631e",
    secondaryColor: "#003c71",
  },
  "SomaLogic, Inc.": {
    companyName: "SomaLogic",
    ticker: "SLGC",
    domain: "somalogic.com",
    logoPath: "/logos/brands/somalogic-inc_logo.png",
    iconPath: "/logos/brands/somalogic-inc_icon.png",
    headerLogoPath: "/logos/brands/somalogic-inc_logo-dark.png",
    headerIconPath: "/logos/brands/somalogic-inc_icon-dark.png",
    primaryColor: "#3f3479",
    secondaryColor: "#24135f",
  },
  "Chindata Group Holdings Ltd.": {
    companyName: "Chindata Group",
    ticker: "CD",
    domain: "chindatagroup.com",
    logoPath: "/logos/brands/chindata-group-holdings-ltd_logo.png",
    iconPath: "/logos/brands/chindata-group-holdings-ltd_icon.png",
    headerLogoPath: "/logos/brands/chindata-group-holdings-ltd_logo-dark.png",
    headerIconPath: "/logos/brands/chindata-group-holdings-ltd_icon-dark.png",
    primaryColor: "#e60012",
    secondaryColor: "#1959c2",
  },
  "Frequency Therapeutics Inc.": {
    companyName: "Korro Bio",
    ticker: "FREQ",
    domain: "frequencytx.com",
    logoPath: "/logos/brands/frequency-therapeutics-inc_logo.png",
    iconPath: "/logos/brands/frequency-therapeutics-inc_icon.png",
    primaryColor: "#f93802",
    secondaryColor: "#121c52",
  },
  "Ambrx Biopharma, Inc.": {
    companyName: "Ambrx",
    ticker: "AMAM",
    domain: "ambrx.com",
    logoPath: "/logos/brands/ambrx-biopharma-inc_logo.png",
    iconPath: "/logos/brands/ambrx-biopharma-inc_icon.png",
    headerLogoPath: "/logos/brands/ambrx-biopharma-inc_logo-dark.png",
    headerIconPath: "/logos/brands/ambrx-biopharma-inc_icon-dark.png",
    primaryColor: "#0c5198",
    secondaryColor: "#0b4f9a",
  },
  "ILG Acquisition One Corp.": {
    companyName: "ILG Acquisition One Corp.",
    ticker: "ILG",
    domain: "ilg.com",
    logoPath: "/logos/brands/ilg-acquisition-one-corp_logo.png",
    iconPath: "/logos/brands/ilg-acquisition-one-corp_icon.png",
    headerLogoPath: "/logos/brands/ilg-acquisition-one-corp_logo-dark.png",
    headerIconPath: "/logos/brands/ilg-acquisition-one-corp_icon-dark.png",
    primaryColor: "#017dc7",
    secondaryColor: "#017dc7",
  },
  "The Wendy's Company": {
    companyName: "Wendy's",
    ticker: "WEN",
    domain: "wendys.com",
    logoPath: "/logos/WEN_logo-full.svg",
    iconPath: "/logos/WEN_logo.png",
    headerLogoPath: "/logos/WEN_logo-dark.svg",
    headerIconPath: "/logos/WEN_icon-dark.png",
    primaryColor: "#0078A3",
    secondaryColor: "#DAD55E",
  },
  "Paycom Software, Inc.": {
    companyName: "Paycom",
    ticker: "PAYC",
    domain: "paycom.com",
    logoPath: "/logos/PAYC_logo-full.svg",
    iconPath: "/logos/PAYC_logo.png",
    headerLogoPath: "/logos/PAYC_logo-dark.svg",
    headerIconPath: "/logos/PAYC_icon-dark.png",
    primaryColor: "#005C2B",
    secondaryColor: "#193E2D",
  },
  "Enliven Therapeutics Inc.": {
    companyName: "Enliven Therapeutics",
    ticker: "ELVN",
    domain: "enliventx.com",
    logoPath: "/logos/ELVN_logo-full.svg",
    iconPath: "/logos/ELVN_logo.png",
    headerLogoPath: "/logos/ELVN_logo-dark.png",
    headerIconPath: "/logos/ELVN_icon-dark.png",
    primaryColor: "#243E89",
    secondaryColor: "#1A1C45",
  },
  "Morrow Sodali": {
    companyName: "Morrow Sodali",
    ticker: "MRSO",
    domain: "morrowsodali.com",
    logoPath: "/logos/MRSO_logo.png",
    iconPath: "/logos/MRSO_icon.png",
    headerLogoPath: "/logos/MRSO_logo-dark.svg",
    headerIconPath: "/logos/MRSO_icon-dark.svg",
    primaryColor: "#ff6400",
    secondaryColor: "#0b232d",
  },
  EnerSa: {
    companyName: "EnerSa",
    ticker: "ENRS",
    domain: "enersa.com.ar",
    logoPath: "/logos/brands/enersa_logo.png",
    iconPath: "/logos/brands/enersa_icon.png",
    primaryColor: "#1a6b3c",
    secondaryColor: "#0d4025",
  },
  "Enhabit, Inc.": {
    companyName: "Enhabit",
    ticker: "EHAB",
    domain: "enhabit.com",
    logoPath: "/logos/ehab_logo.svg",
    iconPath: "/logos/ehab_icon.png",
    headerLogoPath: "/logos/ehab_logo-dark.svg",
    headerIconPath: "/logos/ehab_icon-dark.png",
    primaryColor: "#005eb8",
    secondaryColor: "#003d7a",
  },
  "Vivani Medical, Inc.": {
    companyName: "Vivani Medical",
    ticker: "VANI",
    domain: "vivani.com",
    logoPath: "/logos/vani_logo.png",
    iconPath: "/logos/vani_icon.png",
    headerLogoPath: "/logos/vani_logo-dark.png",
    headerIconPath: "/logos/vani_icon-dark.png",
    primaryColor: "#00a3e0",
    secondaryColor: "#005f8e",
  },
  "Madrigal Pharmaceuticals, Inc.": {
    companyName: "Madrigal Pharmaceuticals",
    ticker: "MDGL",
    domain: "madrigalpharma.com",
    logoPath: "/logos/mdgl_logo.svg",
    iconPath: "/logos/mdgl_icon.png",
    headerLogoPath: "/logos/mdgl_logo-dark.png",
    headerIconPath: "/logos/mdgl_icon-dark.png",
    primaryColor: "#7b2d8b",
    secondaryColor: "#4a1a54",
  },
  "Chain Bridge Bancorp, Inc.": {
    companyName: "Chain Bridge Bancorp",
    ticker: "CBNA",
    domain: "chainbridgebank.com",
    logoPath: "/logos/cbna_logo.svg",
    iconPath: "/logos/cbna_icon.png",
    headerLogoPath: "/logos/cbna_logo-dark.svg",
    headerIconPath: "/logos/cbna_icon-dark.png",
    primaryColor: "#1a3a6b",
    secondaryColor: "#0d2045",
  },
  "InTest Corporation": {
    companyName: "inTEST",
    ticker: "INTT",
    domain: "intest.com",
    logoPath: "",
    iconPath: "",
    primaryColor: "#c8102e",
    secondaryColor: "#1a1a1a",
  },
  "Vapotherm, Inc.": {
    companyName: "Vapotherm",
    ticker: "VAPO",
    domain: "vapotherm.com",
    logoPath: "/logos/vapo_logo.svg",
    iconPath: "/logos/vapo_icon.png",
    headerLogoPath: "/logos/vapo_logo-dark.svg",
    headerIconPath: "/logos/vapo_icon-dark.png",
    primaryColor: "#0085c3",
    secondaryColor: "#005a87",
  },
  "SQZ Biotechnologies Company": {
    companyName: "SQZ Biotech",
    ticker: "SQZ",
    domain: "sqzbiotech.com",
    logoPath: "",
    iconPath: "",
    primaryColor: "#00b5ad",
    secondaryColor: "#007b7a",
  },
  "NexTier Oilfield Solutions Inc.": {
    companyName: "NexTier",
    ticker: "NEX",
    domain: "nextieroilfield.com",
    logoPath: "",
    iconPath: "",
    primaryColor: "#f7941d",
    secondaryColor: "#1a1a1a",
  },
  "Mind Medicine (MindMed) Inc.": {
    companyName: "MindMed",
    ticker: "MNMD",
    domain: "mindmed.com",
    logoPath: "/logos/mnmd_logo.png",
    iconPath: "/logos/mnmd_icon.png",
    headerLogoPath: "/logos/mnmd_logo-dark.png",
    headerIconPath: "/logos/mnmd_icon-dark.png",
    primaryColor: "#6A994E",
    secondaryColor: "#3A3A3A",
  },
  "Adaptive Biotechnologies Corporation": {
    companyName: "Adaptive Biotechnologies",
    ticker: "ADPT",
    domain: "adaptivebiotech.com",
    logoPath: "/logos/adpt_logo.svg",
    iconPath: "/logos/adpt_icon.png",
    headerLogoPath: "/logos/adpt_logo-dark.svg",
    headerIconPath: "/logos/adpt_icon-dark.png",
    primaryColor: "#e53e3e",
    secondaryColor: "#742a2a",
  },
};

/**
 * Secondary index keyed by ticker for reliable logo lookup.
 * Use this when you have a ticker but not a company name — avoids
 * brittle exact-string key matching on company names.
 */
export const brandConfigsByTicker: Record<string, BrandConfig> = Object.values(
  brandConfigs
).reduce<Record<string, BrandConfig>>((accumulator, config) => {
  if (config.ticker) {
    accumulator[config.ticker] = config;
  }
  return accumulator;
}, {});

/** Look up brand config by event/company name */
export function getBrandConfig(companyName: string): BrandConfig | null {
  return brandConfigs[companyName] ?? null;
}

/** Look up brand config by stock ticker (more reliable than company name) */
export function getBrandConfigByTicker(ticker: string): BrandConfig | null {
  return brandConfigsByTicker[ticker] ?? null;
}

/** Get the logo path for a company, with fallback */
export function getBrandLogoPath(
  companyName: string,
  fallback = "/images/logo.svg"
): string {
  return brandConfigs[companyName]?.logoPath || fallback;
}

/** Get the icon path for a company, with fallback */
export function getBrandIconPath(
  companyName: string,
  fallback = "/images/logo.svg"
): string {
  return brandConfigs[companyName]?.iconPath || fallback;
}
