/**
 * Shared event data for PARENT_CLIENT and SOLICITOR users.
 * Each event maps a display company name to a real database meeting.
 * Used by the Events page and the ClientAppSwitcher dropdown.
 */

export interface EventRow {
  id: string
  event: string
  cusip: string
  eventDate: string
  eventType: 'Annual Meeting' | 'Special Meeting'
  meetingId: string
  clientTicker: string
  meetingStatus: 'ACTIVE' | 'COMPLETE'
}

export const parentClientEvents: EventRow[] = [
  {
    id: 'dfin-1',
    event: 'J.P. Morgan Real Estate Income Trust, Inc.',
    cusip: '536813103',
    eventDate: '06/11/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2026',
    clientTicker: 'WEN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-2',
    event: 'EnerSve',
    cusip: '957638109',
    eventDate: '06/11/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2026',
    clientTicker: 'PAYC',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-3',
    event: 'E2open Parent Holdings Inc.',
    cusip: '73642K106',
    eventDate: '06/10/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2026',
    clientTicker: 'WWD',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-4',
    event: 'Champion Homes, Inc.',
    cusip: '609207105',
    eventDate: '05/21/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2026',
    clientTicker: 'ELVN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-5',
    event: 'Bain Capital Specialty Finance, Inc',
    cusip: '609207105',
    eventDate: '05/21/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2025',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-6',
    event: 'Shattuck Labs, Inc.',
    cusip: '609207105',
    eventDate: '05/21/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2025',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-7',
    event: 'Nomad Foods Limited',
    cusip: '609207105',
    eventDate: '05/21/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2025',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-8',
    event: 'Quest Resource Holding Corporation',
    cusip: '25787G100',
    eventDate: '05/14/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2025',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-9',
    event: 'SeaStar Medical Holding Corporation',
    cusip: '45674E109',
    eventDate: '05/08/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2024',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-10',
    event: 'Contineum Therapeutics, Inc.',
    cusip: '68236X100',
    eventDate: '05/07/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2024',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-11',
    event: 'Enhabit, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'wen-special-meeting-2026',
    clientTicker: 'WEN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-12',
    event: 'Fulcrum Therapeutics, InG.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'payc-special-meeting-2026',
    clientTicker: 'PAYC',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-13',
    event: 'Lineage Cell Therapeutics, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'wwd-special-meeting-2026',
    clientTicker: 'WWD',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-14',
    event: 'Inozyme Pharma, Ins.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'elvn-special-meeting-2026',
    clientTicker: 'ELVN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'dfin-15',
    event: 'ARS Pharmaceuticals, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'wen-special-meeting-2025',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-16',
    event: 'Gossamer Bio, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'payc-special-meeting-2025',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-17',
    event: 'Affirm Holdings Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'wwd-special-meeting-2025',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-18',
    event: 'Aligos Therapeutics, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'elvn-special-meeting-2025',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-19',
    event: 'Enliven Therapeutics, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'wen-special-meeting-2024',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-20',
    event: 'Erasca, Inc.',
    cusip: '05479L203',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'payc-special-meeting-2024',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-21',
    event: 'IDEAYA Biosciences, Inc',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2024',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-22',
    event: 'Vivani Medical, Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2024',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-23',
    event: 'CalciMedica, Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2023',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-24',
    event: 'Artiva Biotherapeutics, Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2023',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-25',
    event: 'HilleVax, Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2023',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-26',
    event: 'Telesis Bio Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2023',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'dfin-27',
    event: 'Boundless Big Inc.',
    cusip: '980745103',
    eventDate: '01/29/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2022',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
]

export const solicitorEvents: EventRow[] = [
  {
    id: 'mrso-1',
    event: 'Lithium Americas Corp.',
    cusip: '536813103',
    eventDate: '06/15/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2026',
    clientTicker: 'ELVN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-2',
    event: 'Western Alliance Bancorporation',
    cusip: '957638109',
    eventDate: '06/11/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2026',
    clientTicker: 'WEN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-3',
    event: "Portillo's Inc.",
    cusip: '73642K106',
    eventDate: '06/10/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2026',
    clientTicker: 'PAYC',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-4',
    event: 'Mondelez International, Inc.',
    cusip: '609207105',
    eventDate: '05/21/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2026',
    clientTicker: 'WWD',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-5',
    event: 'Donnelley Financial Solutions, Inc.',
    cusip: '25787G100',
    eventDate: '05/14/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2025',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-6',
    event: 'IN8bio, Inc.',
    cusip: '45674E109',
    eventDate: '05/08/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2025',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-7',
    event: 'The Oncology Institute, Inc.',
    cusip: '68236X100',
    eventDate: '05/07/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-annual-meeting-2025',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-8',
    event: 'Azitra, Inc.',
    cusip: '05479L203',
    eventDate: '04/15/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-annual-meeting-2025',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-9',
    event: 'Woodward, Inc.',
    cusip: '980745103',
    eventDate: '03/20/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2024',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-10',
    event: 'Yapotherm, Inc.',
    cusip: '536813103',
    eventDate: '03/15/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-annual-meeting-2024',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-11',
    event: 'Sonim Technologies, Inc.',
    cusip: '957638109',
    eventDate: '03/10/2025',
    eventType: 'Special Meeting',
    meetingId: 'payc-special-meeting-2026',
    clientTicker: 'PAYC',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-12',
    event: 'Western Alliance Bancorporation',
    cusip: '73642K106',
    eventDate: '02/28/2025',
    eventType: 'Special Meeting',
    meetingId: 'wwd-special-meeting-2026',
    clientTicker: 'WWD',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-13',
    event: 'PROCORE TECHNOLOGIES, INC',
    cusip: '609207105',
    eventDate: '02/20/2025',
    eventType: 'Special Meeting',
    meetingId: 'elvn-special-meeting-2026',
    clientTicker: 'ELVN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-14',
    event: 'Mondelez International, Inc.',
    cusip: '25787G100',
    eventDate: '02/15/2025',
    eventType: 'Special Meeting',
    meetingId: 'wen-special-meeting-2026',
    clientTicker: 'WEN',
    meetingStatus: 'ACTIVE',
  },
  {
    id: 'mrso-15',
    event: 'PHX Minerals Inc.',
    cusip: '45674E109',
    eventDate: '02/10/2025',
    eventType: 'Special Meeting',
    meetingId: 'payc-special-meeting-2025',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-16',
    event: 'Donnelley Financial Solutions Inc.',
    cusip: '68236X100',
    eventDate: '02/05/2025',
    eventType: 'Special Meeting',
    meetingId: 'wwd-special-meeting-2025',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-17',
    event: 'Amerant Bancorp Inc.',
    cusip: '05479L203',
    eventDate: '01/30/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-special-meeting-2025',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-18',
    event: 'SQZ Biotechnologies Company',
    cusip: '980745103',
    eventDate: '01/25/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wen-special-meeting-2024',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-19',
    event: 'Woodward, Inc.',
    cusip: '536813103',
    eventDate: '01/20/2025',
    eventType: 'Annual Meeting',
    meetingId: 'payc-special-meeting-2024',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-20',
    event: 'SomaLogic, Inc.',
    cusip: '957638109',
    eventDate: '01/15/2025',
    eventType: 'Annual Meeting',
    meetingId: 'wwd-special-meeting-2024',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-21',
    event: 'Chindata Group Holdings Ltd',
    cusip: '73642K106',
    eventDate: '01/10/2025',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-special-meeting-2024',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-22',
    event: 'Frequency Therapeutics Inc.',
    cusip: '609207105',
    eventDate: '01/05/2025',
    eventType: 'Special Meeting',
    meetingId: 'wen-annual-meeting-2023',
    clientTicker: 'WEN',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-23',
    event: 'Ambrx Biopharma, Inc.',
    cusip: '25787G100',
    eventDate: '12/20/2024',
    eventType: 'Special Meeting',
    meetingId: 'payc-annual-meeting-2023',
    clientTicker: 'PAYC',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-24',
    event: 'NexTier Oilfield Solutions Inc.',
    cusip: '45674E109',
    eventDate: '12/15/2024',
    eventType: 'Special Meeting',
    meetingId: 'wwd-annual-meeting-2023',
    clientTicker: 'WWD',
    meetingStatus: 'COMPLETE',
  },
  {
    id: 'mrso-25',
    event: 'ILG Acquisition One Corp.',
    cusip: '68236X100',
    eventDate: '12/10/2024',
    eventType: 'Annual Meeting',
    meetingId: 'elvn-annual-meeting-2023',
    clientTicker: 'ELVN',
    meetingStatus: 'COMPLETE',
  },
]

export const allEvents: EventRow[] = [...parentClientEvents, ...solicitorEvents]

/** Build a meeting URL for an event row, including issuer display name override */
export function getMeetingUrl(row: EventRow): string {
  const routePrefix = row.meetingStatus === 'ACTIVE' ? 'meeting' : 'past-meeting'
  const issuerParam = encodeURIComponent(row.event)
  return `/${row.clientTicker}/${routePrefix}/${row.meetingId}?issuer=${issuerParam}`
}
