default_stages: [pre-commit]
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        entry: pnpm run fmt
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: true
