"use client";

import { useMemo, useState } from "react";

import type { FetchedFile } from "./download";
import type { ClientPalette, DerivedRole } from "./theme-pipeline";

import { downloadText, fetchRepoFile, toSourceBundle } from "./download";
import {
  brandedTickers,
  buildClientPalette,
  darkThemeSurfaceColor,
  themePipeline,
  themeSourceFiles,
  wasLightenedForDark,
} from "./theme-pipeline";
import { getCurrentScheme, toHex } from "./tokens";

/** `--ticker-role: #hex;` for every value the pipeline derived. */
const toPaletteCss = (palette: ClientPalette): string => {
  const section = (title: string, roles: readonly DerivedRole[]): string[] => [
    `  /* ${title} */`,
    ...roles.map((role) => {
      const hex = toHex(role.value);
      return `  --${palette.ticker.toLowerCase()}-${role.label}: ${hex ?? role.value};`;
    }),
    "",
  ];

  return [
    `/* ${palette.ticker} — derived by the portal's client-theme pipeline */`,
    "/* Authored values are color-mix()/oklch() expressions; these are resolved. */",
    ":root {",
    ...section("Approved brand colors", palette.seeds),
    ...section("Primary as a palette role", palette.primaryRole),
    ...section("Dark-mode accents", palette.darkSeeds),
    ...section("Vote-chart roles", palette.chartRoles),
    "}",
  ].join("\n");
};

const SwatchChip = ({
  onCopy,
  role,
}: {
  readonly onCopy: (text: string) => void;
  readonly role: DerivedRole;
}) => {
  // Expressions such as color-mix() and oklch() are the authored value; the hex
  // is what the browser paints, and is what a designer asks for.
  const hex = toHex(role.value);

  return (
    <button
      className="ipdev-chip"
      onClick={() => {
        onCopy(role.value);
      }}
      title={role.value}
      type="button"
    >
      <span className="ipdev-chip-swatch" style={{ background: role.value }} />
      <span>
        {role.label}
        <br />
        <span className="ipdev-chip-hex">{hex ?? role.value}</span>
      </span>
    </button>
  );
};

const RoleRow = ({
  onCopy,
  roles,
  title,
}: {
  readonly onCopy: (text: string) => void;
  readonly roles: readonly DerivedRole[];
  readonly title: string;
}) => (
  <>
    <h4>{title}</h4>
    <div className="ipdev-swatch-grid">
      {roles.map((role) => (
        <SwatchChip key={role.label} onCopy={onCopy} role={role} />
      ))}
    </div>
  </>
);

/**
 * Shows how a client's colors are produced, not just what they came out as.
 *
 * @remarks
 * The swatches are generated by calling the real derivation functions, so the
 * panel is a live demonstration of the pipeline rather than a description of it.
 * Switching ticker re-runs the whole chain for that client without touching the
 * app's own theme, which makes it possible to check a brand before it ships.
 */
export const ThemePanel = ({
  activeTicker,
  onClose,
}: {
  readonly activeTicker: string;
  readonly onClose: () => void;
}) => {
  const [ticker, setTicker] = useState(() =>
    brandedTickers.includes(activeTicker)
      ? activeTicker
      : (brandedTickers[0] ?? "DFIN")
  );
  const [flash, setFlash] = useState<string | null>(null);
  const scheme = useMemo(() => getCurrentScheme(), []);
  const palette = useMemo<ClientPalette | null>(
    () => buildClientPalette(ticker),
    [ticker]
  );

  const announce = (message: string): void => {
    setFlash(message);
    window.setTimeout(() => {
      setFlash(null);
    }, 1600);
  };

  const copy = (text: string): void => {
    void navigator.clipboard?.writeText(text);
    announce(`${text} copied`);
  };

  const downloadGeneratorSource = async (): Promise<void> => {
    announce("reading pipeline source…");
    const files = await Promise.all(themeSourceFiles.map(fetchRepoFile));
    const found = files.filter((file): file is FetchedFile => file !== null);

    if (found.length === 0) {
      announce("could not read the pipeline source");
      return;
    }

    downloadText(
      "issuer-portal-client-theme-pipeline.md",
      toSourceBundle(
        "Issuer Portal — client color theme pipeline",
        [
          "Everything that turns a client ticker into a rendered theme, in reading order.",
          ...themePipeline.map((step) => `- **${step.title}** — ${step.detail}`),
        ],
        found
      ),
      "text/markdown"
    );
    announce(`${found.length} files downloaded`);
  };

  const lightenedSeeds =
    palette === null
      ? []
      : palette.seeds.filter((seed, index) =>
          wasLightenedForDark(
            seed.value,
            palette.darkSeeds[index]?.value ?? seed.value
          )
        );

  return (
    <div className="ipdev-panel">
      <div className="ipdev-panel-head">
        <strong>Client color themes</strong>
        <span className="ipdev-mono">
          {ticker} · page is {scheme}
        </span>
        <button
          aria-label="Close"
          className="ipdev-close"
          onClick={onClose}
          type="button"
        >
          ✕
        </button>
      </div>

      <div className="ipdev-panel-bar">
        <div className="ipdev-tickers">
          {brandedTickers.map((candidate) => (
            <button
              aria-pressed={candidate === ticker}
              className="ipdev-btn"
              key={candidate}
              onClick={() => {
                setTicker(candidate);
              }}
              type="button"
            >
              {candidate}
            </button>
          ))}
        </div>
        <button
          className="ipdev-btn"
          onClick={() => {
            void downloadGeneratorSource();
          }}
          title="Download every file that builds a client theme, as one annotated Markdown bundle"
          type="button"
        >
          ⬇ generator source
        </button>
        {palette === null ? null : (
          <button
            className="ipdev-btn"
            onClick={() => {
              downloadText(
                `${palette.ticker.toLowerCase()}-palette.css`,
                toPaletteCss(palette),
                "text/css"
              );
              announce(`${palette.ticker} palette downloaded`);
            }}
            title="Download this client's derived palette as resolved CSS custom properties"
            type="button"
          >
            ⬇ {palette.ticker} palette CSS
          </button>
        )}
        {flash === null ? null : <span className="ipdev-mono">{flash}</span>}
      </div>

      <div className="ipdev-panel-body">
        <h4>How a theme is built</h4>
        {themePipeline.map((step) => (
          <div className="ipdev-step" key={step.title}>
            <div className="ipdev-step-title">{step.title}</div>
            <div className="ipdev-step-file">{step.file}</div>
            <div className="ipdev-step-detail">{step.detail}</div>
          </div>
        ))}

        {palette === null ? (
          <p className="ipdev-empty">No branding on file for {ticker}.</p>
        ) : (
          <>
            <RoleRow
              onCopy={copy}
              roles={palette.seeds}
              title="Step 2 · Approved brand colors"
            />

            <RoleRow
              onCopy={copy}
              roles={palette.primaryRole}
              title="Step 3 · Primary as a MUI palette role"
            />
            <p className="ipdev-note">
              `light` and `dark` stay as `color-mix()` expressions so they track
              the theme; `contrastText` is measured, never assumed.
            </p>

            <RoleRow
              onCopy={copy}
              roles={palette.darkSeeds}
              title={`Step 4 · Dark-mode accents (canvas ${darkThemeSurfaceColor})`}
            />
            <p className="ipdev-note">
              {lightenedSeeds.length === 0
                ? `Every ${ticker} brand color already clears 3:1 against the dark canvas, so all three are used unchanged.`
                : `Lightened to clear 3:1 on the dark canvas: ${lightenedSeeds
                    .map((seed) => seed.label)
                    .join(", ")}.`}
            </p>

            <RoleRow
              onCopy={copy}
              roles={palette.chartRoles}
              title="Step 5 · Vote-chart roles"
            />
            <p className="ipdev-note">
              Registered and Beneficial are the brand colors themselves. Web,
              Print and IVR rotate the primary hue by fixed offsets. For,
              Against, Abstain and Withhold are fixed across every client — the
              donuts merge Abstain and Withhold into one arc.
              <span className="ipdev-flag">brand-independent</span>
            </p>
          </>
        )}
      </div>
    </div>
  );
};
