import type { paths } from '@/types/api'

type CreateMeetingBody =
  paths['/meetings']['post']['requestBody']['content']['application/json']

export const toDbMeeting = (b: CreateMeetingBody) => ({
  id: b.id,
  title: b.title,
  cusip: b.cusip,
  ticker: b.ticker,
  record_date: b.recordDate,
  mailing_date: b.mailingDate,
  meeting_date: b.meetingDate,
  meeting_type: b.meetingType,
  meeting_year: b.meetingYear,
  distribution_type: b.distributionType,
  transfer_agent: b.transferAgent,
  employee_stock_plans: b.employeeStockPlans ?? null,
  plan_administrator: b.planAdministrator ?? null,
  plan_administrator_contact: b.planAdministratorContact ?? null,
  plan_administrator_contact_email: b.planAdministratorContactEmail ?? null,
  solicitor: b.solicitor ?? null,
  solicitor_email: b.solicitorEmail ?? null,
  document_hosting_site_label: b.documentHostingSiteLabel ?? null,
  document_hosting_site_url: b.documentHostingSiteUrl ?? null,
  e_vote_site_label: b.eVoteSiteLabel ?? null,
  e_vote_site_url: b.eVoteSiteUrl ?? null,
  ivr_dial_in_number: b.ivrDialInNumber ?? null,
  total_shares_outstanding: b.totalSharesOutstanding,
  quorum_requirement: b.quorumRequirement,
  client_id: b.clientId,
})

export const fromDbMeeting = (m: any) => ({
  id: m.id,
  title: m.title,
  cusip: m.cusip,
  ticker: m.ticker,
  preFilingDate: m.pre_filing_date ?? null,
  filingDate: m.filing_date ?? null,
  brokerSearchDate: m.broker_search_date ?? null,
  recordDate: m.record_date,
  mailingDate: m.mailing_date,
  meetingDate: m.meeting_date,
  meetingType: m.meeting_type,
  meetingYear: m.meeting_year,
  status: m.status,
  currentPhase: m.current_phase,
  overallCompletion: m.overall_completion,
  distributionType: m.distribution_type,
  transferAgent: m.transfer_agent,
  employeeStockPlans: m.employee_stock_plans ?? null,
  planAdministrator: m.plan_administrator ?? null,
  planAdministratorContact: m.plan_administrator_contact ?? null,
  planAdministratorContactEmail: m.plan_administrator_contact_email ?? null,
  solicitor: m.solicitor ?? null,
  solicitorEmail: m.solicitor_email ?? null,
  inspector: m.inspector ?? null,
  documentHostingSiteLabel: m.document_hosting_site_label ?? null,
  documentHostingSiteUrl: m.document_hosting_site_url ?? null,
  eVoteSiteLabel: m.e_vote_site_label ?? null,
  eVoteSiteUrl: m.e_vote_site_url ?? null,
  ivrDialInNumber: m.ivr_dial_in_number ?? null,
  totalSharesOutstanding: m.total_shares_outstanding,
  quorumRequirement: m.quorum_requirement,
  clientId: m.client_id,
  createdAt: m.created_at,
  updatedAt: m.updated_at,
})
