import type { Position } from "@/types/api-exports";

/**
 * Config for the Vote Distribution donut.
 *
 * The chart is two concentric rings: account type on the inside, voted vs not
 * voted on the outside. Both dimensions are toggled from the legend, so the
 * ids, labels and colours all live here rather than being split between the
 * chart and whatever builds its data.
 */

export type AccountTypeId = "dtc" | "non-dtc";
export type VoteStatusId = "unvoted" | "voted";

/** Slice ids used by the upstream distribution data, e.g. `dtc-voted`. */
export type VoteDistributionSliceId = `${AccountTypeId}-${VoteStatusId}`;

export interface VoteDistributionData {
  readonly color: string;
  readonly id: VoteDistributionSliceId;
  readonly label: string;
  readonly value: number;
}

export interface AccountType {
  readonly color: string;
  /** Foreground for arc labels drawn on this account's inner slice. */
  readonly contrastColor: string;
  readonly id: AccountTypeId;
  readonly label: string;
}

export interface RingStyle {
  readonly color: string;
  readonly contrastColor: string;
}

export interface VoteStatus {
  readonly id: VoteStatusId;
  readonly label: string;
  /**
   * Fill and label colour per account type. Values are semantic CSS variables
   * from the active client's dedicated chart palette.
   */
  readonly styleByAccountType: Readonly<Record<AccountTypeId, RingStyle>>;
}

/**
 * The account colors come from the client's dedicated chart palette. Each
 * account has a dark inner slice, a full-strength voted slice, and a
 * washed-out not-voted slice, all generated by the active MUI client theme.
 */
/** Inner ring. Each account has a darker version of its brand color. */
export const accountTypes: readonly AccountType[] = [
  {
    color: "var(--mui-palette-voteDistribution-dtc-inner)",
    contrastColor: "var(--mui-palette-voteDistribution-dtc-innerContrastText)",
    id: "dtc",
    label: "DTC/CDS",
  },
  {
    color: "var(--mui-palette-voteDistribution-nonDtc-inner)",
    contrastColor:
      "var(--mui-palette-voteDistribution-nonDtc-innerContrastText)",
    id: "non-dtc",
    label: "Non-DTC",
  },
];

export const voteStatuses: readonly VoteStatus[] = [
  {
    id: "voted",
    label: "Voted",
    styleByAccountType: {
      dtc: {
        color: "var(--mui-palette-voteDistribution-dtc-voted)",
        contrastColor:
          "var(--mui-palette-voteDistribution-dtc-votedContrastText)",
      },
      "non-dtc": {
        color: "var(--mui-palette-voteDistribution-nonDtc-voted)",
        contrastColor:
          "var(--mui-palette-voteDistribution-nonDtc-votedContrastText)",
      },
    },
  },
  {
    id: "unvoted",
    label: "Not Voted",
    styleByAccountType: {
      dtc: {
        color: "var(--mui-palette-voteDistribution-dtc-unvoted)",
        contrastColor:
          "var(--mui-palette-voteDistribution-dtc-unvotedContrastText)",
      },
      "non-dtc": {
        color: "var(--mui-palette-voteDistribution-nonDtc-unvoted)",
        contrastColor:
          "var(--mui-palette-voteDistribution-nonDtc-unvotedContrastText)",
      },
    },
  },
];

export const buildSliceId = (
  accountType: AccountTypeId,
  status: VoteStatusId
): VoteDistributionSliceId => `${accountType}-${status}`;

const voteDistributionSlices: readonly Omit<VoteDistributionData, "value">[] = [
  {
    color: "var(--mui-palette-voteDistribution-dtc-voted)",
    id: "dtc-voted",
    label: "DTC/CDS Voted",
  },
  {
    color: "var(--mui-palette-voteDistribution-dtc-unvoted)",
    id: "dtc-unvoted",
    label: "DTC/CDS Not Voted",
  },
  {
    color: "var(--mui-palette-voteDistribution-nonDtc-voted)",
    id: "non-dtc-voted",
    label: "Non-DTC Voted",
  },
  {
    color: "var(--mui-palette-voteDistribution-nonDtc-unvoted)",
    id: "non-dtc-unvoted",
    label: "Non-DTC Not Voted",
  },
];

/**
 * Builds the report donut from the live positions shared with Tabulation.
 * Voted positions contribute only their recorded `sharesVoted`; unvoted
 * positions contribute their full outstanding shares.
 */
export const buildVoteDistributionData = (
  positions: readonly Position[]
): VoteDistributionData[] => {
  const values: Record<VoteDistributionSliceId, number> = {
    "dtc-unvoted": 0,
    "dtc-voted": 0,
    "non-dtc-unvoted": 0,
    "non-dtc-voted": 0,
  };

  for (const position of positions) {
    let accountType: AccountTypeId | null = null;
    if (position.accountType === "DTC/CDS") {
      accountType = "dtc";
    } else if (position.accountType === "Non-DTC") {
      accountType = "non-dtc";
    }

    let status: VoteStatusId | null = null;
    if (position.voteStatus === "Voted") {
      status = "voted";
    } else if (position.voteStatus === "Unvoted") {
      status = "unvoted";
    }

    if (accountType === null || status === null) {
      continue;
    }

    const sliceId = buildSliceId(accountType, status);
    values[sliceId] +=
      status === "voted" ? (position.sharesVoted ?? 0) : (position.shares ?? 0);
  }

  return voteDistributionSlices.flatMap((slice) => {
    const value = values[slice.id];
    return value > 0 ? [{ ...slice, value }] : [];
  });
};

/**
 * Floor for an outer slice's share of its parent, so a near-zero segment stays
 * visible instead of collapsing to an invisible sliver. Matches the vote
 * breakdown donut.
 */
export const minimumStatusShare = 0.035;

/**
 * Where each ring's arc labels sit, measured from the centre. The inner ring
 * is a filled circle, so without this its labels land on top of the centre
 * total; pushing them outward keeps both readable.
 */
export const accountArcLabelRadius = 68;
export const statusArcLabelRadius = 110;

/**
 * Id of the invisible slice that holds the space left by hidden series.
 * Without it the remaining slices stretch to fill the circle, so a filtered
 * view reads as 100% no matter how little is actually selected.
 */
export const hiddenRemainderId = "__hidden-remainder";

/** Fill for that gap. Matches the quorum gauge's empty reference arc. */
export const hiddenRemainderColor = "var(--mui-palette-divider)";

/** Greyed ring shown when the legend has hidden everything. */
export const neutralRingColor = "var(--mui-palette-divider)";

/**
 * Every fill the donut can paint, mapped to the foreground its arc labels
 * should use. Built from the same definitions the rings are, so a colour
 * change cannot leave a label unreadable behind it.
 */
export const arcLabelContrastByColor: ReadonlyMap<string, string> = new Map([
  ...accountTypes.map((accountType): [string, string] => [
    accountType.color,
    accountType.contrastColor,
  ]),
  ...accountTypes.flatMap((accountType) =>
    voteStatuses.map((status): [string, string] => {
      const style = status.styleByAccountType[accountType.id];
      return [style.color, style.contrastColor];
    })
  ),
  [neutralRingColor, "var(--mui-palette-text-primary)"],
]);
