'use client'

import React from 'react'

import {
  Timeline,
  TimelineConnector,
  TimelineContent,
  TimelineDot,
  TimelineItem,
  TimelineSeparator,
  timelineItemClasses,
} from '@mui/lab'
import { Card, CardContent, CardHeader, Typography } from '@mui/material'

export type MailingStatus =
  | 'Positions Received'
  | 'Positions Loaded'
  | 'Proof Delivered'
  | 'Proof Approved'
  | 'Materials Printed'
  | 'Mailing In Progress'
  | 'Affidavit Delivered'
  | 'Mailing Complete'

interface WorkflowStep {
  label: MailingStatus
  paletteVar: string
}

interface MailingTimelineCardProps {
  currentStatus?: MailingStatus | null
}

// CSS variable names generated by MUI from jobStatusColors in theme.ts
const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    label: 'Positions Received',
    paletteVar: 'var(--mui-palette-statusReceived-main)',
  },
  {
    label: 'Positions Loaded',
    paletteVar: 'var(--mui-palette-statusUnapproved-main)',
  },
  {
    label: 'Proof Delivered',
    paletteVar: 'var(--mui-palette-statusProofing-main)',
  },
  {
    label: 'Proof Approved',
    paletteVar: 'var(--mui-palette-statusApproved-main)',
  },
  {
    label: 'Materials Printed',
    paletteVar: 'var(--mui-palette-statusProduction-main)',
  },
  {
    label: 'Mailing In Progress',
    paletteVar: 'var(--mui-palette-statusPulls-main)',
  },
  {
    label: 'Affidavit Delivered',
    paletteVar: 'var(--mui-palette-statusPending-main)',
  },
  {
    label: 'Mailing Complete',
    paletteVar: 'var(--mui-palette-statusComplete-main)',
  },
]

export default function MailingTimelineCard({ currentStatus }: MailingTimelineCardProps) {
  const activeIndex = currentStatus
    ? WORKFLOW_STEPS.findIndex((s) => s.label === currentStatus)
    : -1

  return (
    <Card sx={{ height: '100%' }}>
      <CardHeader title="Mailing Timeline" />
      <CardContent sx={{ pt: 0 }}>
        <Timeline
          sx={{
            p: 0,
            m: 0,
            [`& .${timelineItemClasses.root}:before`]: {
              flex: 0,
              padding: 0,
            },
          }}
        >
          {WORKFLOW_STEPS.map((step, index) => {
            const isCompleted = activeIndex >= 0 && index <= activeIndex
            const isLast = index === WORKFLOW_STEPS.length - 1

            return (
              <TimelineItem key={step.label}>
                <TimelineSeparator>
                  <TimelineDot
                    variant={isCompleted ? 'filled' : 'outlined'}
                    sx={{
                      my: 0.5,
                      bgcolor: isCompleted ? step.paletteVar : 'transparent',
                      borderColor: step.paletteVar,
                    }}
                  />
                  {!isLast && (
                    <TimelineConnector
                      sx={{
                        bgcolor: isCompleted
                          ? step.paletteVar
                          : (theme) => theme.vars.palette.divider,
                      }}
                    />
                  )}
                </TimelineSeparator>
                <TimelineContent sx={{ py: 0.5, px: 2 }}>
                  <Typography variant="body2" fontWeight={600}>
                    {step.label}
                  </Typography>
                </TimelineContent>
              </TimelineItem>
            )
          })}
        </Timeline>
      </CardContent>
    </Card>
  )
}
