'use client'

import React from 'react'

import {
  Timeline,
  TimelineConnector,
  TimelineContent,
  TimelineDot,
  TimelineItem,
  TimelineSeparator,
  timelineItemClasses,
} from '@mui/lab'
import { Card, CardContent, CardHeader, Chip, Typography } from '@mui/material'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'

export type MailingStatus =
  | 'Preparing for Mailing'
  | 'Proofing & Approval'
  | 'Mailing In Progress'
  | 'Mailing Completed'

interface WorkflowStep {
  label: MailingStatus
  paletteVar: string
  color?: string
}

interface MailingTimelineCardProps {
  currentStatus?: MailingStatus | null
  statusDate?: string | null
}

// CSS variable names generated by MUI from jobStatusColors in theme.ts
const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    label: 'Preparing for Mailing',
    paletteVar: 'var(--mui-palette-statusPending-main)',
    color: 'var(--mui-palette-statusPending-contrastText)',
  },
  {
    label: 'Proofing & Approval',
    paletteVar: 'var(--mui-palette-statusProofing-main)',
    color: 'var(--mui-palette-statusProofing-contrastText)',
  },
  {
    label: 'Mailing In Progress',
    paletteVar: 'var(--mui-palette-statusPulls-main)',
    color: 'var(--mui-palette-statusPulls-contrastText)',
  },
  {
    label: 'Mailing Completed',
    paletteVar: 'var(--mui-palette-statusComplete-main)',
    color: 'var(--mui-palette-statusComplete-contrastText)',
  },
]

export default function MailingTimelineCard({
  currentStatus,
  statusDate,
}: MailingTimelineCardProps) {
  const activeIndex = currentStatus
    ? WORKFLOW_STEPS.findIndex((s) => s.label === currentStatus)
    : -1

  const formattedDate = statusDate
    ? new Date(statusDate).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    })
    : null

  return (
    <Card sx={{ height: '100%' }}>
      <CardHeader title="Mailing Timeline" />
      <CardContent sx={{ pt: 0 }}>
        <Timeline
          sx={{
            p: 0,
            m: 0,
            [`& .${timelineItemClasses.root}:before`]: {
              flex: 0,
              padding: 0,
            },
          }}
        >
          {WORKFLOW_STEPS.map((step, index) => {
            const isCompleted = activeIndex >= 0 && index <= activeIndex
            const isCurrent = index === activeIndex
            const isLast = index === WORKFLOW_STEPS.length - 1

            return (
              <TimelineItem key={step.label}>
                <TimelineSeparator sx={{
                  marginBottom: '-0.5rem'
                }}>
                  <TimelineDot
                    variant={isCompleted ? 'filled' : 'outlined'}
                    sx={{
                      mt: 1,
                      bgcolor: isCompleted ? step.paletteVar : 'transparent',
                      borderColor: step.paletteVar,
                    }}
                  />
                  {!isLast && (
                    <TimelineConnector
                      sx={{
                        bgcolor: isCompleted
                          ? step.paletteVar
                          : (theme) => theme.vars.palette.divider,
                      }}
                    />
                  )}
                </TimelineSeparator>
                <TimelineContent sx={{ py: 0.8, px: 2 }}>
                  {isCurrent ? (
                    <>
                      {formattedDate && (
                        <Typography
                          variant="body3"
                          color="text.secondary"
                          sx={{ display: 'block', mb: 0.25 }}
                        >
                          {formattedDate}
                        </Typography>
                      )}
                      <Chip
                        icon={isLast && isCompleted ?
                          <CheckCircleIcon
                            sx={{
                              '--mui-palette-Chip-defaultIconColor': 'var(--mui-palette-success-contrastText)',
                              fontSize: 16,
                              boxSizing: 'content-box',
                            }}
                          /> : undefined}
                        label={step.label}
                        size="small"
                        sx={{
                          bgcolor: isLast && isCompleted ? 'var(--mui-palette-success-main)' : step.paletteVar,
                          color: isLast && isCompleted ? 'var(--mui-palette-success-contrastText)' : step.color,
                          fontWeight: 600,
                          fontSize: '0.75rem',
                        }}
                      />
                    </>
                  ) : (
                    <Typography
                      variant="body3"
                      fontWeight={500}
                      color={isCompleted ? 'text.primary' : 'text.secondary'}
                    >
                      {step.label}
                    </Typography>
                  )}
                </TimelineContent>
              </TimelineItem>
            )
          })}
        </Timeline>
      </CardContent>
    </Card>
  )
}
