#!/usr/bin/env tsx
import fs from 'fs/promises'
import { glob } from 'glob'
import path from 'path'

async function addOptionsHandlers() {

  // Find all route.ts files in the app/api directory
  const routeFiles = await glob('app/api/**/route.ts', {
    cwd: process.cwd(),
    absolute: false,
  })

  for (const file of routeFiles) {
    const filePath = path.join(process.cwd(), file)
    let content = await fs.readFile(filePath, 'utf-8')

    // Skip if already has OPTIONS handler
    if (content.includes('export async function OPTIONS')) {
      continue
    }

    // Skip auto-generated warning
    const isAutoGenerated = content.includes('AUTO-GENERATED FROM OPENAPI SPEC')

    // Add import if not present
    if (!content.includes("import { handleCors } from '@/utils/cors'")) {
      const importRegex = /import { NextRequest, NextResponse } from 'next\/server'/
      content = content.replace(
        importRegex,
        `import { NextRequest, NextResponse } from 'next/server'\nimport { handleCors } from '@/utils/cors'`
      )
    }

    // Add OPTIONS handler at the end of the file
    content =
      content.trimEnd() +
      '\n\nexport async function OPTIONS() {\n  return handleCors()\n}\n'

    await fs.writeFile(filePath, content)
  }

}

