/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { Clients } from './Clients'
import {
  ClientsFromJSON,
  ClientsFromJSONTyped,
  ClientsToJSON,
  ClientsToJSONTyped,
} from './Clients'

/**
 *
 * @export
 * @interface Account
 */
export interface Account {
  /**
   *
   * @type {string}
   * @memberof Account
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Account
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Account
   */
  primaryContact?: string
  /**
   * The client this account belongs to
   * @type {string}
   * @memberof Account
   */
  clientId?: string
  /**
   *
   * @type {Date}
   * @memberof Account
   */
  createdAt?: Date
  /**
   *
   * @type {Clients}
   * @memberof Account
   */
  client?: Clients
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
  return true
}

export function AccountFromJSON(json: any): Account {
  return AccountFromJSONTyped(json, false)
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    primaryContact: json['primaryContact'] == null ? undefined : json['primaryContact'],
    clientId: json['clientId'] == null ? undefined : json['clientId'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    client: json['client'] == null ? undefined : ClientsFromJSON(json['client']),
  }
}

export function AccountToJSON(json: any): Account {
  return AccountToJSONTyped(json, false)
}

export function AccountToJSONTyped(
  value?: Account | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    primaryContact: value['primaryContact'],
    clientId: value['clientId'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    client: ClientsToJSON(value['client']),
  }
}
