/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AddDocumentEventRequest
 */
export interface AddDocumentEventRequest {
  /**
   *
   * @type {string}
   * @memberof AddDocumentEventRequest
   */
  eventType: AddDocumentEventRequestEventTypeEnum;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof AddDocumentEventRequest
   */
  metadata?: { [key: string]: any };
}

/**
 * @export
 */
export const AddDocumentEventRequestEventTypeEnum = {
  Created: "CREATED",
  Uploaded: "UPLOADED",
  Viewed: "VIEWED",
  Downloaded: "DOWNLOADED",
  Signed: "SIGNED",
  Approved: "APPROVED",
  Rejected: "REJECTED",
  Commented: "COMMENTED",
  Updated: "UPDATED",
  Deleted: "DELETED",
} as const;
export type AddDocumentEventRequestEventTypeEnum =
  (typeof AddDocumentEventRequestEventTypeEnum)[keyof typeof AddDocumentEventRequestEventTypeEnum];

/**
 * Check if a given object implements the AddDocumentEventRequest interface.
 */
export function instanceOfAddDocumentEventRequest(value: object): value is AddDocumentEventRequest {
  if (!("eventType" in value) || value["eventType"] === undefined) return false;
  return true;
}

export function AddDocumentEventRequestFromJSON(json: any): AddDocumentEventRequest {
  return AddDocumentEventRequestFromJSONTyped(json, false);
}

export function AddDocumentEventRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddDocumentEventRequest {
  if (json == null) {
    return json;
  }
  return {
    eventType: json["eventType"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
  };
}

export function AddDocumentEventRequestToJSON(json: any): AddDocumentEventRequest {
  return AddDocumentEventRequestToJSONTyped(json, false);
}

export function AddDocumentEventRequestToJSONTyped(
  value?: AddDocumentEventRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    eventType: value["eventType"],
    metadata: value["metadata"],
  };
}
