/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ApproveDocumentVersionRequest
 */
export interface ApproveDocumentVersionRequest {
  /**
   *
   * @type {string}
   * @memberof ApproveDocumentVersionRequest
   */
  meetingId: string;
  /**
   * Optional approval comment
   * @type {string}
   * @memberof ApproveDocumentVersionRequest
   */
  comment?: string;
}

/**
 * Check if a given object implements the ApproveDocumentVersionRequest interface.
 */
export function instanceOfApproveDocumentVersionRequest(
  value: object
): value is ApproveDocumentVersionRequest {
  if (!("meetingId" in value) || value["meetingId"] === undefined) return false;
  return true;
}

export function ApproveDocumentVersionRequestFromJSON(
  json: any
): ApproveDocumentVersionRequest {
  return ApproveDocumentVersionRequestFromJSONTyped(json, false);
}

export function ApproveDocumentVersionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApproveDocumentVersionRequest {
  if (json == null) {
    return json;
  }
  return {
    meetingId: json["meetingId"],
    comment: json["comment"] == null ? undefined : json["comment"],
  };
}

export function ApproveDocumentVersionRequestToJSON(
  json: any
): ApproveDocumentVersionRequest {
  return ApproveDocumentVersionRequestToJSONTyped(json, false);
}

export function ApproveDocumentVersionRequestToJSONTyped(
  value?: ApproveDocumentVersionRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    meetingId: value["meetingId"],
    comment: value["comment"],
  };
}
