/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  DocumentFromJSON,
  DocumentFromJSONTyped,
  DocumentToJSON,
  DocumentToJSONTyped,
} from "./Document";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";
import type { User } from "./User";
import type { Document } from "./Document";

/**
 *
 * @export
 * @interface Comment
 */
export interface Comment {
  /**
   *
   * @type {number}
   * @memberof Comment
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  documentId?: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  comment?: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  lastName?: string;
  /**
   *
   * @type {Date}
   * @memberof Comment
   */
  createdAt?: Date;
  /**
   *
   * @type {Document}
   * @memberof Comment
   */
  document?: Document;
  /**
   *
   * @type {User}
   * @memberof Comment
   */
  user?: User;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
  return true;
}

export function CommentFromJSON(json: any): Comment {
  return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Comment {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    documentId: json["documentId"] == null ? undefined : json["documentId"],
    userId: json["userId"] == null ? undefined : json["userId"],
    comment: json["comment"] == null ? undefined : json["comment"],
    firstName: json["firstName"] == null ? undefined : json["firstName"],
    lastName: json["lastName"] == null ? undefined : json["lastName"],
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    document:
      json["document"] == null ? undefined : DocumentFromJSON(json["document"]),
    user: json["user"] == null ? undefined : UserFromJSON(json["user"]),
  };
}

export function CommentToJSON(json: any): Comment {
  return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(
  value?: Comment | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    documentId: value["documentId"],
    userId: value["userId"],
    comment: value["comment"],
    firstName: value["firstName"],
    lastName: value["lastName"],
    createdAt:
      value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    document: DocumentToJSON(value["document"]),
    user: UserToJSON(value["user"]),
  };
}
