/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { UserType } from './UserType'
import {
  UserTypeFromJSON,
  UserTypeFromJSONTyped,
  UserTypeToJSON,
  UserTypeToJSONTyped,
} from './UserType'

/**
 *
 * @export
 * @interface CreateAccountUserRequest
 */
export interface CreateAccountUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAccountUserRequest
   */
  username: string
  /**
   *
   * @type {string}
   * @memberof CreateAccountUserRequest
   */
  firstName: string
  /**
   *
   * @type {string}
   * @memberof CreateAccountUserRequest
   */
  lastName: string
  /**
   *
   * @type {string}
   * @memberof CreateAccountUserRequest
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof CreateAccountUserRequest
   */
  password: string
  /**
   *
   * @type {UserType}
   * @memberof CreateAccountUserRequest
   */
  type: UserType
}

/**
 * Check if a given object implements the CreateAccountUserRequest interface.
 */
export function instanceOfCreateAccountUserRequest(
  value: object
): value is CreateAccountUserRequest {
  if (!('username' in value) || value['username'] === undefined) return false
  if (!('firstName' in value) || value['firstName'] === undefined) return false
  if (!('lastName' in value) || value['lastName'] === undefined) return false
  if (!('email' in value) || value['email'] === undefined) return false
  if (!('password' in value) || value['password'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function CreateAccountUserRequestFromJSON(json: any): CreateAccountUserRequest {
  return CreateAccountUserRequestFromJSONTyped(json, false)
}

export function CreateAccountUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateAccountUserRequest {
  if (json == null) {
    return json
  }
  return {
    username: json['username'],
    firstName: json['firstName'],
    lastName: json['lastName'],
    email: json['email'],
    password: json['password'],
    type: UserTypeFromJSON(json['type']),
  }
}

export function CreateAccountUserRequestToJSON(json: any): CreateAccountUserRequest {
  return CreateAccountUserRequestToJSONTyped(json, false)
}

export function CreateAccountUserRequestToJSONTyped(
  value?: CreateAccountUserRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    username: value['username'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    email: value['email'],
    password: value['password'],
    type: UserTypeToJSON(value['type']),
  }
}
