import type { UserType } from "./UserType";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  UserTypeFromJSON,
  UserTypeFromJSONTyped,
  UserTypeToJSON,
  UserTypeToJSONTyped,
} from "./UserType";

/**
 *
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  password: string;
  /**
   *
   * @type {UserType}
   * @memberof CreateUserRequest
   */
  type: UserType;
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  accountId?: string;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(
  value: object
): value is CreateUserRequest {
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("firstName" in value) || value["firstName"] === undefined) return false;
  if (!("lastName" in value) || value["lastName"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
  return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateUserRequest {
  if (json == null) {
    return json;
  }
  return {
    username: json["username"],
    firstName: json["firstName"],
    lastName: json["lastName"],
    email: json["email"],
    password: json["password"],
    type: UserTypeFromJSON(json["type"]),
    accountId: json["accountId"] == null ? undefined : json["accountId"],
  };
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
  return CreateUserRequestToJSONTyped(json, false);
}

export function CreateUserRequestToJSONTyped(
  value?: CreateUserRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    username: value["username"],
    firstName: value["firstName"],
    lastName: value["lastName"],
    email: value["email"],
    password: value["password"],
    type: UserTypeToJSON(value["type"]),
    accountId: value["accountId"],
  };
}
