/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface CreatePhaseRequestKeyDates
 */
export interface CreatePhaseRequestKeyDates {
  /**
   *
   * @type {Date}
   * @memberof CreatePhaseRequestKeyDates
   */
  startDate?: Date
  /**
   *
   * @type {Date}
   * @memberof CreatePhaseRequestKeyDates
   */
  endDate?: Date
  /**
   *
   * @type {Date}
   * @memberof CreatePhaseRequestKeyDates
   */
  dueDate?: Date
}

/**
 * Check if a given object implements the CreatePhaseRequestKeyDates interface.
 */
export function instanceOfCreatePhaseRequestKeyDates(
  value: object
): value is CreatePhaseRequestKeyDates {
  return true
}

export function CreatePhaseRequestKeyDatesFromJSON(
  json: any
): CreatePhaseRequestKeyDates {
  return CreatePhaseRequestKeyDatesFromJSONTyped(json, false)
}

export function CreatePhaseRequestKeyDatesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreatePhaseRequestKeyDates {
  if (json == null) {
    return json
  }
  return {
    startDate: json['startDate'] == null ? undefined : new Date(json['startDate']),
    endDate: json['endDate'] == null ? undefined : new Date(json['endDate']),
    dueDate: json['dueDate'] == null ? undefined : new Date(json['dueDate']),
  }
}

export function CreatePhaseRequestKeyDatesToJSON(json: any): CreatePhaseRequestKeyDates {
  return CreatePhaseRequestKeyDatesToJSONTyped(json, false)
}

export function CreatePhaseRequestKeyDatesToJSONTyped(
  value?: CreatePhaseRequestKeyDates | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    startDate:
      value['startDate'] == null
        ? undefined
        : value['startDate'].toISOString().substring(0, 10),
    endDate:
      value['endDate'] == null
        ? undefined
        : value['endDate'].toISOString().substring(0, 10),
    dueDate:
      value['dueDate'] == null
        ? undefined
        : value['dueDate'].toISOString().substring(0, 10),
  }
}
