/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  CreatePhaseRequestKeyDatesFromJSON,
  CreatePhaseRequestKeyDatesFromJSONTyped,
  CreatePhaseRequestKeyDatesToJSON,
  CreatePhaseRequestKeyDatesToJSONTyped,
} from "./CreatePhaseRequestKeyDates";
import type { CreatePhaseRequestKeyDates } from "./CreatePhaseRequestKeyDates";

/**
 *
 * @export
 * @interface CreatePhaseRequest
 */
export interface CreatePhaseRequest {
  /**
   *
   * @type {string}
   * @memberof CreatePhaseRequest
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof CreatePhaseRequest
   */
  orderIndex: number;
  /**
   *
   * @type {CreatePhaseRequestKeyDates}
   * @memberof CreatePhaseRequest
   */
  keyDates?: CreatePhaseRequestKeyDates;
}

/**
 * Check if a given object implements the CreatePhaseRequest interface.
 */
export function instanceOfCreatePhaseRequest(
  value: object
): value is CreatePhaseRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("orderIndex" in value) || value["orderIndex"] === undefined)
    return false;
  return true;
}

export function CreatePhaseRequestFromJSON(json: any): CreatePhaseRequest {
  return CreatePhaseRequestFromJSONTyped(json, false);
}

export function CreatePhaseRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreatePhaseRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    orderIndex: json["orderIndex"],
    keyDates:
      json["keyDates"] == null
        ? undefined
        : CreatePhaseRequestKeyDatesFromJSON(json["keyDates"]),
  };
}

export function CreatePhaseRequestToJSON(json: any): CreatePhaseRequest {
  return CreatePhaseRequestToJSONTyped(json, false);
}

export function CreatePhaseRequestToJSONTyped(
  value?: CreatePhaseRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    orderIndex: value["orderIndex"],
    keyDates: CreatePhaseRequestKeyDatesToJSON(value["keyDates"]),
  };
}
