/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface CreateDigitalShareholderMeetingRequest
 */
export interface CreateDigitalShareholderMeetingRequest {
  /**
   *
   * @type {string}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  registrantType: CreateDigitalShareholderMeetingRequestRegistrantTypeEnum
  /**
   *
   * @type {string}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  firstName: string
  /**
   *
   * @type {string}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  lastName: string
  /**
   *
   * @type {string}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  emailAddress: string
  /**
   *
   * @type {string}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  registrationQuestions?: string | null
  /**
   *
   * @type {number}
   * @memberof CreateDigitalShareholderMeetingRequest
   */
  minutesAttendedMeeting?: number | null
}

/**
 * @export
 */
export const CreateDigitalShareholderMeetingRequestRegistrantTypeEnum = {
  Shareholder: 'Shareholder',
  Guest: 'Guest',
  Proxy: 'Proxy',
  Other: 'Other',
} as const
export type CreateDigitalShareholderMeetingRequestRegistrantTypeEnum =
  (typeof CreateDigitalShareholderMeetingRequestRegistrantTypeEnum)[keyof typeof CreateDigitalShareholderMeetingRequestRegistrantTypeEnum]

/**
 * Check if a given object implements the CreateDigitalShareholderMeetingRequest interface.
 */
export function instanceOfCreateDigitalShareholderMeetingRequest(
  value: object
): value is CreateDigitalShareholderMeetingRequest {
  if (!('registrantType' in value) || value['registrantType'] === undefined) return false
  if (!('firstName' in value) || value['firstName'] === undefined) return false
  if (!('lastName' in value) || value['lastName'] === undefined) return false
  if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false
  return true
}

export function CreateDigitalShareholderMeetingRequestFromJSON(
  json: any
): CreateDigitalShareholderMeetingRequest {
  return CreateDigitalShareholderMeetingRequestFromJSONTyped(json, false)
}

export function CreateDigitalShareholderMeetingRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateDigitalShareholderMeetingRequest {
  if (json == null) {
    return json
  }
  return {
    registrantType: json['registrantType'],
    firstName: json['firstName'],
    lastName: json['lastName'],
    emailAddress: json['emailAddress'],
    registrationQuestions:
      json['registrationQuestions'] == null ? undefined : json['registrationQuestions'],
    minutesAttendedMeeting:
      json['minutesAttendedMeeting'] == null ? undefined : json['minutesAttendedMeeting'],
  }
}

export function CreateDigitalShareholderMeetingRequestToJSON(
  json: any
): CreateDigitalShareholderMeetingRequest {
  return CreateDigitalShareholderMeetingRequestToJSONTyped(json, false)
}

export function CreateDigitalShareholderMeetingRequestToJSONTyped(
  value?: CreateDigitalShareholderMeetingRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    registrantType: value['registrantType'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    emailAddress: value['emailAddress'],
    registrationQuestions: value['registrationQuestions'],
    minutesAttendedMeeting: value['minutesAttendedMeeting'],
  }
}
