/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  taskId: string;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  phaseId: string;
  /**
   *
   * @type {number}
   * @memberof CreateTaskRequest
   */
  phaseNumber: number;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  type: string;
  /**
   *
   * @type {Date}
   * @memberof CreateTaskRequest
   */
  dueDate?: Date;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  owner: string;
  /**
   *
   * @type {string}
   * @memberof CreateTaskRequest
   */
  documentId?: string;
  /**
   *
   * @type {object}
   * @memberof CreateTaskRequest
   */
  links?: object;
}

/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(
  value: object
): value is CreateTaskRequest {
  if (!("taskId" in value) || value["taskId"] === undefined) return false;
  if (!("phaseId" in value) || value["phaseId"] === undefined) return false;
  if (!("phaseNumber" in value) || value["phaseNumber"] === undefined)
    return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("owner" in value) || value["owner"] === undefined) return false;
  return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
  return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateTaskRequest {
  if (json == null) {
    return json;
  }
  return {
    taskId: json["taskId"],
    phaseId: json["phaseId"],
    phaseNumber: json["phaseNumber"],
    title: json["title"],
    description: json["description"] == null ? undefined : json["description"],
    type: json["type"],
    dueDate: json["dueDate"] == null ? undefined : new Date(json["dueDate"]),
    owner: json["owner"],
    documentId: json["documentId"] == null ? undefined : json["documentId"],
    links: json["links"] == null ? undefined : json["links"],
  };
}

export function CreateTaskRequestToJSON(json: any): CreateTaskRequest {
  return CreateTaskRequestToJSONTyped(json, false);
}

export function CreateTaskRequestToJSONTyped(
  value?: CreateTaskRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    taskId: value["taskId"],
    phaseId: value["phaseId"],
    phaseNumber: value["phaseNumber"],
    title: value["title"],
    description: value["description"],
    type: value["type"],
    dueDate:
      value["dueDate"] == null
        ? undefined
        : value["dueDate"].toISOString().substring(0, 10),
    owner: value["owner"],
    documentId: value["documentId"],
    links: value["links"],
  };
}
