/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface CreateProposalRequest
 */
export interface CreateProposalRequest {
  /**
   *
   * @type {number}
   * @memberof CreateProposalRequest
   */
  proposalNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  proposalTitle: string
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  proposalType: string
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  proposalSubtype?: string | null
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  directorName?: string
  /**
   *
   * @type {number}
   * @memberof CreateProposalRequest
   */
  directorTermYears?: number
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  directorClass?: string
  /**
   *
   * @type {number}
   * @memberof CreateProposalRequest
   */
  termExpirationYear?: number
  /**
   *
   * @type {object}
   * @memberof CreateProposalRequest
   */
  frequencyOptions?: object
  /**
   *
   * @type {string}
   * @memberof CreateProposalRequest
   */
  recommendation: string
}

/**
 * Check if a given object implements the CreateProposalRequest interface.
 */
export function instanceOfCreateProposalRequest(
  value: object
): value is CreateProposalRequest {
  if (!('proposalNumber' in value) || value['proposalNumber'] === undefined) return false
  if (!('proposalTitle' in value) || value['proposalTitle'] === undefined) return false
  if (!('proposalType' in value) || value['proposalType'] === undefined) return false
  if (!('recommendation' in value) || value['recommendation'] === undefined) return false
  return true
}

export function CreateProposalRequestFromJSON(json: any): CreateProposalRequest {
  return CreateProposalRequestFromJSONTyped(json, false)
}

export function CreateProposalRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateProposalRequest {
  if (json == null) {
    return json
  }
  return {
    proposalNumber: json['proposalNumber'],
    proposalTitle: json['proposalTitle'],
    proposalType: json['proposalType'],
    proposalSubtype:
      json['proposalSubtype'] == null ? undefined : json['proposalSubtype'],
    directorName: json['directorName'] == null ? undefined : json['directorName'],
    directorTermYears:
      json['directorTermYears'] == null ? undefined : json['directorTermYears'],
    directorClass: json['directorClass'] == null ? undefined : json['directorClass'],
    termExpirationYear:
      json['termExpirationYear'] == null ? undefined : json['termExpirationYear'],
    frequencyOptions:
      json['frequencyOptions'] == null ? undefined : json['frequencyOptions'],
    recommendation: json['recommendation'],
  }
}

export function CreateProposalRequestToJSON(json: any): CreateProposalRequest {
  return CreateProposalRequestToJSONTyped(json, false)
}

export function CreateProposalRequestToJSONTyped(
  value?: CreateProposalRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    proposalNumber: value['proposalNumber'],
    proposalTitle: value['proposalTitle'],
    proposalType: value['proposalType'],
    proposalSubtype: value['proposalSubtype'],
    directorName: value['directorName'],
    directorTermYears: value['directorTermYears'],
    directorClass: value['directorClass'],
    termExpirationYear: value['termExpirationYear'],
    frequencyOptions: value['frequencyOptions'],
    recommendation: value['recommendation'],
  }
}
