/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateAccountRequest
 */
export interface CreateAccountRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAccountRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateAccountRequest
   */
  primaryContact: string;
  /**
   * The client this account belongs to
   * @type {string}
   * @memberof CreateAccountRequest
   */
  clientId: string;
}

/**
 * Check if a given object implements the CreateAccountRequest interface.
 */
export function instanceOfCreateAccountRequest(
  value: object
): value is CreateAccountRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("primaryContact" in value) || value["primaryContact"] === undefined)
    return false;
  if (!("clientId" in value) || value["clientId"] === undefined) return false;
  return true;
}

export function CreateAccountRequestFromJSON(json: any): CreateAccountRequest {
  return CreateAccountRequestFromJSONTyped(json, false);
}

export function CreateAccountRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateAccountRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    primaryContact: json["primaryContact"],
    clientId: json["clientId"],
  };
}

export function CreateAccountRequestToJSON(json: any): CreateAccountRequest {
  return CreateAccountRequestToJSONTyped(json, false);
}

export function CreateAccountRequestToJSONTyped(
  value?: CreateAccountRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    primaryContact: value["primaryContact"],
    clientId: value["clientId"],
  };
}
