/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface DigitalShareholderMeeting
 */
export interface DigitalShareholderMeeting {
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  meetingId?: string
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  registrantType?: DigitalShareholderMeetingRegistrantTypeEnum
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  firstName?: string
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  lastName?: string
  /**
   *
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  emailAddress?: string
  /**
   * Pre-meeting questions submitted during registration
   * @type {string}
   * @memberof DigitalShareholderMeeting
   */
  registrationQuestions?: string | null
  /**
   * Minutes attended in the meeting
   * @type {number}
   * @memberof DigitalShareholderMeeting
   */
  minutesAttendedMeeting?: number | null
  /**
   *
   * @type {Date}
   * @memberof DigitalShareholderMeeting
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof DigitalShareholderMeeting
   */
  updatedAt?: Date
}

/**
 * @export
 */
export const DigitalShareholderMeetingRegistrantTypeEnum = {
  Shareholder: 'Shareholder',
  Guest: 'Guest',
  Proxy: 'Proxy',
  Other: 'Other',
} as const
export type DigitalShareholderMeetingRegistrantTypeEnum =
  (typeof DigitalShareholderMeetingRegistrantTypeEnum)[keyof typeof DigitalShareholderMeetingRegistrantTypeEnum]

/**
 * Check if a given object implements the DigitalShareholderMeeting interface.
 */
export function instanceOfDigitalShareholderMeeting(
  value: object
): value is DigitalShareholderMeeting {
  return true
}

export function DigitalShareholderMeetingFromJSON(json: any): DigitalShareholderMeeting {
  return DigitalShareholderMeetingFromJSONTyped(json, false)
}

export function DigitalShareholderMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DigitalShareholderMeeting {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    registrantType: json['registrantType'] == null ? undefined : json['registrantType'],
    firstName: json['firstName'] == null ? undefined : json['firstName'],
    lastName: json['lastName'] == null ? undefined : json['lastName'],
    emailAddress: json['emailAddress'] == null ? undefined : json['emailAddress'],
    registrationQuestions:
      json['registrationQuestions'] == null ? undefined : json['registrationQuestions'],
    minutesAttendedMeeting:
      json['minutesAttendedMeeting'] == null ? undefined : json['minutesAttendedMeeting'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  }
}

export function DigitalShareholderMeetingToJSON(json: any): DigitalShareholderMeeting {
  return DigitalShareholderMeetingToJSONTyped(json, false)
}

export function DigitalShareholderMeetingToJSONTyped(
  value?: DigitalShareholderMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    meetingId: value['meetingId'],
    registrantType: value['registrantType'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    emailAddress: value['emailAddress'],
    registrationQuestions: value['registrationQuestions'],
    minutesAttendedMeeting: value['minutesAttendedMeeting'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
  }
}
