/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { Comment } from './Comment'
import {
  CommentFromJSON,
  CommentFromJSONTyped,
  CommentToJSON,
  CommentToJSONTyped,
} from './Comment'
import type { DocumentStatus } from './DocumentStatus'
import {
  DocumentStatusFromJSON,
  DocumentStatusFromJSONTyped,
  DocumentStatusToJSON,
  DocumentStatusToJSONTyped,
} from './DocumentStatus'
import type { Meeting } from './Meeting'
import {
  MeetingFromJSON,
  MeetingFromJSONTyped,
  MeetingToJSON,
  MeetingToJSONTyped,
} from './Meeting'
import type { Signature } from './Signature'
import {
  SignatureFromJSON,
  SignatureFromJSONTyped,
  SignatureToJSON,
  SignatureToJSONTyped,
} from './Signature'

/**
 *
 * @export
 * @interface Document
 */
export interface Document {
  /**
   *
   * @type {string}
   * @memberof Document
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  meetingId?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  taskId?: string | null
  /**
   *
   * @type {string}
   * @memberof Document
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof Document
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  filePath?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  fileType?: string
  /**
   *
   * @type {number}
   * @memberof Document
   */
  fileSize?: number
  /**
   *
   * @type {DocumentStatus}
   * @memberof Document
   */
  status?: DocumentStatus
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  uploadDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  uploadedDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  signedDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  authorizedDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  completedDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  inProgressDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  deadline?: Date | null
  /**
   *
   * @type {object}
   * @memberof Document
   */
  history?: object | null
  /**
   * User who approved the document
   * @type {string}
   * @memberof Document
   */
  approvedBy?: string | null
  /**
   * When the document was approved
   * @type {Date}
   * @memberof Document
   */
  approvedAt?: Date | null
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof Document
   */
  updatedAt?: Date
  /**
   * Category for filtering document display (general, dsm, proxy-materials, meeting-materials, post-meeting, internal)
   * @type {string}
   * @memberof Document
   */
  displayCategory?: DocumentDisplayCategoryEnum | null
  /**
   *
   * @type {Meeting}
   * @memberof Document
   */
  meeting?: Meeting
  /**
   *
   * @type {Array<Comment>}
   * @memberof Document
   */
  comments?: Array<Comment>
  /**
   *
   * @type {Array<Signature>}
   * @memberof Document
   */
  signatures?: Array<Signature>
}

/**
 * @export
 */
export const DocumentDisplayCategoryEnum = {
  General: 'general',
  Dsm: 'dsm',
  ProxyMaterials: 'proxy-materials',
  MeetingMaterials: 'meeting-materials',
  PostMeeting: 'post-meeting',
  Internal: 'internal',
} as const
export type DocumentDisplayCategoryEnum =
  (typeof DocumentDisplayCategoryEnum)[keyof typeof DocumentDisplayCategoryEnum]

/**
 * Check if a given object implements the Document interface.
 */
export function instanceOfDocument(value: object): value is Document {
  return true
}

export function DocumentFromJSON(json: any): Document {
  return DocumentFromJSONTyped(json, false)
}

export function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    taskId: json['taskId'] == null ? undefined : json['taskId'],
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    type: json['type'] == null ? undefined : json['type'],
    filePath: json['filePath'] == null ? undefined : json['filePath'],
    fileType: json['fileType'] == null ? undefined : json['fileType'],
    fileSize: json['fileSize'] == null ? undefined : json['fileSize'],
    status: json['status'] == null ? undefined : DocumentStatusFromJSON(json['status']),
    uploadDate: json['uploadDate'] == null ? undefined : new Date(json['uploadDate']),
    uploadedDate:
      json['uploadedDate'] == null ? undefined : new Date(json['uploadedDate']),
    signedDate: json['signedDate'] == null ? undefined : new Date(json['signedDate']),
    authorizedDate:
      json['authorizedDate'] == null ? undefined : new Date(json['authorizedDate']),
    completedDate:
      json['completedDate'] == null ? undefined : new Date(json['completedDate']),
    inProgressDate:
      json['inProgressDate'] == null ? undefined : new Date(json['inProgressDate']),
    deadline: json['deadline'] == null ? undefined : new Date(json['deadline']),
    history: json['history'] == null ? undefined : json['history'],
    approvedBy: json['approvedBy'] == null ? undefined : json['approvedBy'],
    approvedAt: json['approvedAt'] == null ? undefined : new Date(json['approvedAt']),
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    displayCategory:
      json['displayCategory'] == null ? undefined : json['displayCategory'],
    meeting: json['meeting'] == null ? undefined : MeetingFromJSON(json['meeting']),
    comments:
      json['comments'] == null
        ? undefined
        : (json['comments'] as Array<any>).map(CommentFromJSON),
    signatures:
      json['signatures'] == null
        ? undefined
        : (json['signatures'] as Array<any>).map(SignatureFromJSON),
  }
}

export function DocumentToJSON(json: any): Document {
  return DocumentToJSONTyped(json, false)
}

export function DocumentToJSONTyped(
  value?: Document | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    meetingId: value['meetingId'],
    taskId: value['taskId'],
    title: value['title'],
    description: value['description'],
    type: value['type'],
    filePath: value['filePath'],
    fileType: value['fileType'],
    fileSize: value['fileSize'],
    status: DocumentStatusToJSON(value['status']),
    uploadDate:
      value['uploadDate'] === null ? null : (value['uploadDate'] as any)?.toISOString(),
    uploadedDate:
      value['uploadedDate'] === null
        ? null
        : (value['uploadedDate'] as any)?.toISOString(),
    signedDate:
      value['signedDate'] === null ? null : (value['signedDate'] as any)?.toISOString(),
    authorizedDate:
      value['authorizedDate'] === null
        ? null
        : (value['authorizedDate'] as any)?.toISOString(),
    completedDate:
      value['completedDate'] === null
        ? null
        : (value['completedDate'] as any)?.toISOString(),
    inProgressDate:
      value['inProgressDate'] === null
        ? null
        : (value['inProgressDate'] as any)?.toISOString(),
    deadline:
      value['deadline'] === null ? null : (value['deadline'] as any)?.toISOString(),
    history: value['history'],
    approvedBy: value['approvedBy'],
    approvedAt:
      value['approvedAt'] === null ? null : (value['approvedAt'] as any)?.toISOString(),
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
    displayCategory: value['displayCategory'],
    meeting: MeetingToJSON(value['meeting']),
    comments:
      value['comments'] == null
        ? undefined
        : (value['comments'] as Array<any>).map(CommentToJSON),
    signatures:
      value['signatures'] == null
        ? undefined
        : (value['signatures'] as Array<any>).map(SignatureToJSON),
  }
}
