/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { Document } from './Document'
import {
  DocumentFromJSON,
  DocumentFromJSONTyped,
  DocumentToJSON,
  DocumentToJSONTyped,
} from './Document'
import type { User } from './User'
import { UserFromJSON, UserFromJSONTyped, UserToJSON, UserToJSONTyped } from './User'

/**
 *
 * @export
 * @interface DocumentHistory
 */
export interface DocumentHistory {
  /**
   *
   * @type {string}
   * @memberof DocumentHistory
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof DocumentHistory
   */
  documentId?: string
  /**
   *
   * @type {string}
   * @memberof DocumentHistory
   */
  eventType?: DocumentHistoryEventTypeEnum
  /**
   *
   * @type {string}
   * @memberof DocumentHistory
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof DocumentHistory
   */
  userName?: string
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof DocumentHistory
   */
  metadata?: { [key: string]: any }
  /**
   *
   * @type {Date}
   * @memberof DocumentHistory
   */
  createdAt?: Date
  /**
   *
   * @type {Document}
   * @memberof DocumentHistory
   */
  document?: Document
  /**
   *
   * @type {User}
   * @memberof DocumentHistory
   */
  user?: User
}

/**
 * @export
 */
export const DocumentHistoryEventTypeEnum = {
  Created: 'CREATED',
  Uploaded: 'UPLOADED',
  Viewed: 'VIEWED',
  Downloaded: 'DOWNLOADED',
  Signed: 'SIGNED',
  Approved: 'APPROVED',
  Rejected: 'REJECTED',
  Commented: 'COMMENTED',
  Updated: 'UPDATED',
  Deleted: 'DELETED',
} as const
export type DocumentHistoryEventTypeEnum =
  (typeof DocumentHistoryEventTypeEnum)[keyof typeof DocumentHistoryEventTypeEnum]

/**
 * Check if a given object implements the DocumentHistory interface.
 */
export function instanceOfDocumentHistory(value: object): value is DocumentHistory {
  return true
}

export function DocumentHistoryFromJSON(json: any): DocumentHistory {
  return DocumentHistoryFromJSONTyped(json, false)
}

export function DocumentHistoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentHistory {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    documentId: json['documentId'] == null ? undefined : json['documentId'],
    eventType: json['eventType'] == null ? undefined : json['eventType'],
    userId: json['userId'] == null ? undefined : json['userId'],
    userName: json['userName'] == null ? undefined : json['userName'],
    metadata: json['metadata'] == null ? undefined : json['metadata'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    document: json['document'] == null ? undefined : DocumentFromJSON(json['document']),
    user: json['user'] == null ? undefined : UserFromJSON(json['user']),
  }
}

export function DocumentHistoryToJSON(json: any): DocumentHistory {
  return DocumentHistoryToJSONTyped(json, false)
}

export function DocumentHistoryToJSONTyped(
  value?: DocumentHistory | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    documentId: value['documentId'],
    eventType: value['eventType'],
    userId: value['userId'],
    userName: value['userName'],
    metadata: value['metadata'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    document: DocumentToJSON(value['document']),
    user: UserToJSON(value['user']),
  }
}
