/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface DSMConfig
 */
export interface DSMConfig {
  /**
   *
   * @type {string}
   * @memberof DSMConfig
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof DSMConfig
   */
  meetingId?: string
  /**
   *
   * @type {boolean}
   * @memberof DSMConfig
   */
  liveQa?: boolean
  /**
   *
   * @type {boolean}
   * @memberof DSMConfig
   */
  audioOnly?: boolean
  /**
   *
   * @type {boolean}
   * @memberof DSMConfig
   */
  meetingRecording?: boolean
  /**
   *
   * @type {string}
   * @memberof DSMConfig
   */
  staticSlideDocId?: string | null
  /**
   *
   * @type {string}
   * @memberof DSMConfig
   */
  displayDocsDocId?: string | null
  /**
   *
   * @type {boolean}
   * @memberof DSMConfig
   */
  isConfirmed?: boolean
  /**
   *
   * @type {Date}
   * @memberof DSMConfig
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof DSMConfig
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the DSMConfig interface.
 */
export function instanceOfDSMConfig(value: object): value is DSMConfig {
  return true
}

export function DSMConfigFromJSON(json: any): DSMConfig {
  return DSMConfigFromJSONTyped(json, false)
}

export function DSMConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DSMConfig {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    liveQa: json['liveQa'] == null ? undefined : json['liveQa'],
    audioOnly: json['audioOnly'] == null ? undefined : json['audioOnly'],
    meetingRecording:
      json['meetingRecording'] == null ? undefined : json['meetingRecording'],
    staticSlideDocId:
      json['staticSlideDocId'] == null ? undefined : json['staticSlideDocId'],
    displayDocsDocId:
      json['displayDocsDocId'] == null ? undefined : json['displayDocsDocId'],
    isConfirmed: json['isConfirmed'] == null ? undefined : json['isConfirmed'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  }
}

export function DSMConfigToJSON(json: any): DSMConfig {
  return DSMConfigToJSONTyped(json, false)
}

export function DSMConfigToJSONTyped(
  value?: DSMConfig | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    meetingId: value['meetingId'],
    liveQa: value['liveQa'],
    audioOnly: value['audioOnly'],
    meetingRecording: value['meetingRecording'],
    staticSlideDocId: value['staticSlideDocId'],
    displayDocsDocId: value['displayDocsDocId'],
    isConfirmed: value['isConfirmed'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
  }
}
