import type { Account } from "./Account";
import type { Pagination } from "./Pagination";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  AccountFromJSON,
  AccountFromJSONTyped,
  AccountToJSON,
  AccountToJSONTyped,
} from "./Account";
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from "./Pagination";

/**
 *
 * @export
 * @interface ListAccounts200Response
 */
export interface ListAccounts200Response {
  /**
   *
   * @type {Array<Account>}
   * @memberof ListAccounts200Response
   */
  accounts?: Array<Account>;
  /**
   *
   * @type {Pagination}
   * @memberof ListAccounts200Response
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the ListAccounts200Response interface.
 */
export function instanceOfListAccounts200Response(value: object): value is ListAccounts200Response {
  return true;
}

export function ListAccounts200ResponseFromJSON(json: any): ListAccounts200Response {
  return ListAccounts200ResponseFromJSONTyped(json, false);
}

export function ListAccounts200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListAccounts200Response {
  if (json == null) {
    return json;
  }
  return {
    accounts:
      json["accounts"] == null ? undefined : (json["accounts"] as Array<any>).map(AccountFromJSON),
    pagination: json["pagination"] == null ? undefined : PaginationFromJSON(json["pagination"]),
  };
}

export function ListAccounts200ResponseToJSON(json: any): ListAccounts200Response {
  return ListAccounts200ResponseToJSONTyped(json, false);
}

export function ListAccounts200ResponseToJSONTyped(
  value?: ListAccounts200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    accounts:
      value["accounts"] == null ? undefined : (value["accounts"] as Array<any>).map(AccountToJSON),
    pagination: PaginationToJSON(value["pagination"]),
  };
}
