import type { Pagination } from "./Pagination";
import type { User } from "./User";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from "./Pagination";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 *
 * @export
 * @interface ListAccountUsers200Response
 */
export interface ListAccountUsers200Response {
  /**
   *
   * @type {Array<User>}
   * @memberof ListAccountUsers200Response
   */
  users?: Array<User>;
  /**
   *
   * @type {Pagination}
   * @memberof ListAccountUsers200Response
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the ListAccountUsers200Response interface.
 */
export function instanceOfListAccountUsers200Response(
  value: object
): value is ListAccountUsers200Response {
  return true;
}

export function ListAccountUsers200ResponseFromJSON(
  json: any
): ListAccountUsers200Response {
  return ListAccountUsers200ResponseFromJSONTyped(json, false);
}

export function ListAccountUsers200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListAccountUsers200Response {
  if (json == null) {
    return json;
  }
  return {
    users:
      json["users"] == null
        ? undefined
        : (json["users"] as Array<any>).map(UserFromJSON),
    pagination:
      json["pagination"] == null
        ? undefined
        : PaginationFromJSON(json["pagination"]),
  };
}

export function ListAccountUsers200ResponseToJSON(
  json: any
): ListAccountUsers200Response {
  return ListAccountUsers200ResponseToJSONTyped(json, false);
}

export function ListAccountUsers200ResponseToJSONTyped(
  value?: ListAccountUsers200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    users:
      value["users"] == null
        ? undefined
        : (value["users"] as Array<any>).map(UserToJSON),
    pagination: PaginationToJSON(value["pagination"]),
  };
}
