import type { Meeting } from "./Meeting";
import type { Pagination } from "./Pagination";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  MeetingFromJSON,
  MeetingFromJSONTyped,
  MeetingToJSON,
  MeetingToJSONTyped,
} from "./Meeting";
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from "./Pagination";

/**
 *
 * @export
 * @interface ListMeetings200Response
 */
export interface ListMeetings200Response {
  /**
   *
   * @type {Array<Meeting>}
   * @memberof ListMeetings200Response
   */
  meetings?: Array<Meeting>;
  /**
   *
   * @type {Pagination}
   * @memberof ListMeetings200Response
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the ListMeetings200Response interface.
 */
export function instanceOfListMeetings200Response(value: object): value is ListMeetings200Response {
  return true;
}

export function ListMeetings200ResponseFromJSON(json: any): ListMeetings200Response {
  return ListMeetings200ResponseFromJSONTyped(json, false);
}

export function ListMeetings200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListMeetings200Response {
  if (json == null) {
    return json;
  }
  return {
    meetings:
      json["meetings"] == null ? undefined : (json["meetings"] as Array<any>).map(MeetingFromJSON),
    pagination: json["pagination"] == null ? undefined : PaginationFromJSON(json["pagination"]),
  };
}

export function ListMeetings200ResponseToJSON(json: any): ListMeetings200Response {
  return ListMeetings200ResponseToJSONTyped(json, false);
}

export function ListMeetings200ResponseToJSONTyped(
  value?: ListMeetings200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meetings:
      value["meetings"] == null ? undefined : (value["meetings"] as Array<any>).map(MeetingToJSON),
    pagination: PaginationToJSON(value["pagination"]),
  };
}
