/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface LoginUserRequest
 */
export interface LoginUserRequest {
  /**
   *
   * @type {string}
   * @memberof LoginUserRequest
   */
  username: string
  /**
   *
   * @type {string}
   * @memberof LoginUserRequest
   */
  password: string
}

/**
 * Check if a given object implements the LoginUserRequest interface.
 */
export function instanceOfLoginUserRequest(value: object): value is LoginUserRequest {
  if (!('username' in value) || value['username'] === undefined) return false
  if (!('password' in value) || value['password'] === undefined) return false
  return true
}

export function LoginUserRequestFromJSON(json: any): LoginUserRequest {
  return LoginUserRequestFromJSONTyped(json, false)
}

export function LoginUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginUserRequest {
  if (json == null) {
    return json
  }
  return {
    username: json['username'],
    password: json['password'],
  }
}

export function LoginUserRequestToJSON(json: any): LoginUserRequest {
  return LoginUserRequestToJSONTyped(json, false)
}

export function LoginUserRequestToJSONTyped(
  value?: LoginUserRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    username: value['username'],
    password: value['password'],
  }
}
