/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { User } from './User'
import { UserFromJSON, UserFromJSONTyped, UserToJSON, UserToJSONTyped } from './User'

/**
 *
 * @export
 * @interface LoginUser200Response
 */
export interface LoginUser200Response {
  /**
   *
   * @type {User}
   * @memberof LoginUser200Response
   */
  user?: User
  /**
   *
   * @type {string}
   * @memberof LoginUser200Response
   */
  token?: string
}

/**
 * Check if a given object implements the LoginUser200Response interface.
 */
export function instanceOfLoginUser200Response(
  value: object
): value is LoginUser200Response {
  return true
}

export function LoginUser200ResponseFromJSON(json: any): LoginUser200Response {
  return LoginUser200ResponseFromJSONTyped(json, false)
}

export function LoginUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginUser200Response {
  if (json == null) {
    return json
  }
  return {
    user: json['user'] == null ? undefined : UserFromJSON(json['user']),
    token: json['token'] == null ? undefined : json['token'],
  }
}

export function LoginUser200ResponseToJSON(json: any): LoginUser200Response {
  return LoginUser200ResponseToJSONTyped(json, false)
}

export function LoginUser200ResponseToJSONTyped(
  value?: LoginUser200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    user: UserToJSON(value['user']),
    token: value['token'],
  }
}
