/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface LogoutUser200Response
 */
export interface LogoutUser200Response {
  /**
   *
   * @type {string}
   * @memberof LogoutUser200Response
   */
  message?: string
}

/**
 * Check if a given object implements the LogoutUser200Response interface.
 */
export function instanceOfLogoutUser200Response(
  value: object
): value is LogoutUser200Response {
  return true
}

export function LogoutUser200ResponseFromJSON(json: any): LogoutUser200Response {
  return LogoutUser200ResponseFromJSONTyped(json, false)
}

export function LogoutUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LogoutUser200Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function LogoutUser200ResponseToJSON(json: any): LogoutUser200Response {
  return LogoutUser200ResponseToJSONTyped(json, false)
}

export function LogoutUser200ResponseToJSONTyped(
  value?: LogoutUser200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
