/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface Mailing
 */
export interface Mailing {
  /**
   *
   * @type {string}
   * @memberof Mailing
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Mailing
   */
  meetingId?: string
  /**
   *
   * @type {string}
   * @memberof Mailing
   */
  ticker?: string
  /**
   * Total number of accounts
   * @type {number}
   * @memberof Mailing
   */
  totalAccounts?: number
  /**
   * Total number of positions
   * @type {number}
   * @memberof Mailing
   */
  totalPositions?: number
  /**
   * Number of retransmissions
   * @type {number}
   * @memberof Mailing
   */
  totalRetransmissions?: number | null
  /**
   * Number of rollups
   * @type {number}
   * @memberof Mailing
   */
  totalRollups?: number | null
  /**
   * Number of fullset mail positions
   * @type {number}
   * @memberof Mailing
   */
  fullsetMailPositions?: number
  /**
   * Number of NAA mail positions
   * @type {number}
   * @memberof Mailing
   */
  naaMailPositions?: number
  /**
   * Number of courtesy/other mail positions
   * @type {number}
   * @memberof Mailing
   */
  courtesyOtherMailPositions?: number | null
  /**
   * Number of electronic suppressed positions
   * @type {number}
   * @memberof Mailing
   */
  electronicSuppressedPositions?: number
  /**
   * Number of household suppressed positions
   * @type {number}
   * @memberof Mailing
   */
  householdSuppressedPositions?: number
  /**
   * Number of managed suppressed positions
   * @type {number}
   * @memberof Mailing
   */
  managedSuppressedPositions?: number | null
  /**
   * Number of consolidated suppressed positions
   * @type {number}
   * @memberof Mailing
   */
  consolidatedSuppressedPositions?: number | null
  /**
   * Number of canceled suppressed positions
   * @type {number}
   * @memberof Mailing
   */
  canceledSuppressedPositions?: number
  /**
   *
   * @type {Date}
   * @memberof Mailing
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof Mailing
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the Mailing interface.
 */
export function instanceOfMailing(value: object): value is Mailing {
  return true
}

export function MailingFromJSON(json: any): Mailing {
  return MailingFromJSONTyped(json, false)
}

export function MailingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mailing {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    ticker: json['ticker'] == null ? undefined : json['ticker'],
    totalAccounts: json['totalAccounts'] == null ? undefined : json['totalAccounts'],
    totalPositions: json['totalPositions'] == null ? undefined : json['totalPositions'],
    totalRetransmissions:
      json['totalRetransmissions'] == null ? undefined : json['totalRetransmissions'],
    totalRollups: json['totalRollups'] == null ? undefined : json['totalRollups'],
    fullsetMailPositions:
      json['fullsetMailPositions'] == null ? undefined : json['fullsetMailPositions'],
    naaMailPositions:
      json['naaMailPositions'] == null ? undefined : json['naaMailPositions'],
    courtesyOtherMailPositions:
      json['courtesyOtherMailPositions'] == null
        ? undefined
        : json['courtesyOtherMailPositions'],
    electronicSuppressedPositions:
      json['electronicSuppressedPositions'] == null
        ? undefined
        : json['electronicSuppressedPositions'],
    householdSuppressedPositions:
      json['householdSuppressedPositions'] == null
        ? undefined
        : json['householdSuppressedPositions'],
    managedSuppressedPositions:
      json['managedSuppressedPositions'] == null
        ? undefined
        : json['managedSuppressedPositions'],
    consolidatedSuppressedPositions:
      json['consolidatedSuppressedPositions'] == null
        ? undefined
        : json['consolidatedSuppressedPositions'],
    canceledSuppressedPositions:
      json['canceledSuppressedPositions'] == null
        ? undefined
        : json['canceledSuppressedPositions'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  }
}

export function MailingToJSON(json: any): Mailing {
  return MailingToJSONTyped(json, false)
}

export function MailingToJSONTyped(
  value?: Mailing | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    meetingId: value['meetingId'],
    ticker: value['ticker'],
    totalAccounts: value['totalAccounts'],
    totalPositions: value['totalPositions'],
    totalRetransmissions: value['totalRetransmissions'],
    totalRollups: value['totalRollups'],
    fullsetMailPositions: value['fullsetMailPositions'],
    naaMailPositions: value['naaMailPositions'],
    courtesyOtherMailPositions: value['courtesyOtherMailPositions'],
    electronicSuppressedPositions: value['electronicSuppressedPositions'],
    householdSuppressedPositions: value['householdSuppressedPositions'],
    managedSuppressedPositions: value['managedSuppressedPositions'],
    consolidatedSuppressedPositions: value['consolidatedSuppressedPositions'],
    canceledSuppressedPositions: value['canceledSuppressedPositions'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
  }
}
