/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MeetingStatus = {
  Active: "ACTIVE",
  Complete: "COMPLETE",
  Adjourned: "ADJOURNED",
} as const;
export type MeetingStatus = (typeof MeetingStatus)[keyof typeof MeetingStatus];

export function instanceOfMeetingStatus(value: any): boolean {
  for (const key in MeetingStatus) {
    if (Object.prototype.hasOwnProperty.call(MeetingStatus, key)) {
      if (MeetingStatus[key as keyof typeof MeetingStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function MeetingStatusFromJSON(json: any): MeetingStatus {
  return MeetingStatusFromJSONTyped(json, false);
}

export function MeetingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingStatus {
  return json as MeetingStatus;
}

export function MeetingStatusToJSON(value?: MeetingStatus | null): any {
  return value as any;
}

export function MeetingStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): MeetingStatus {
  return value as MeetingStatus;
}
