/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  type?: NotificationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  priority?: NotificationPriorityEnum;
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  read?: boolean;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  meetingId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  taskId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  actionUrl?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  readAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  expiresAt?: Date | null;
}

/**
 * @export
 */
export const NotificationTypeEnum = {
  Info: "info",
  Warning: "warning",
  Error: "error",
  Success: "success",
} as const;
export type NotificationTypeEnum =
  (typeof NotificationTypeEnum)[keyof typeof NotificationTypeEnum];

/**
 * @export
 */
export const NotificationPriorityEnum = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Critical: "critical",
} as const;
export type NotificationPriorityEnum =
  (typeof NotificationPriorityEnum)[keyof typeof NotificationPriorityEnum];

/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
  return true;
}

export function NotificationFromJSON(json: any): Notification {
  return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Notification {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["title"] == null ? undefined : json["title"],
    message: json["message"] == null ? undefined : json["message"],
    type: json["type"] == null ? undefined : json["type"],
    priority: json["priority"] == null ? undefined : json["priority"],
    read: json["read"] == null ? undefined : json["read"],
    userId: json["userId"] == null ? undefined : json["userId"],
    meetingId: json["meetingId"] == null ? undefined : json["meetingId"],
    taskId: json["taskId"] == null ? undefined : json["taskId"],
    actionUrl: json["actionUrl"] == null ? undefined : json["actionUrl"],
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    readAt: json["readAt"] == null ? undefined : new Date(json["readAt"]),
    expiresAt:
      json["expiresAt"] == null ? undefined : new Date(json["expiresAt"]),
  };
}

export function NotificationToJSON(json: any): Notification {
  return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(
  value?: Notification | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    message: value["message"],
    type: value["type"],
    priority: value["priority"],
    read: value["read"],
    userId: value["userId"],
    meetingId: value["meetingId"],
    taskId: value["taskId"],
    actionUrl: value["actionUrl"],
    createdAt:
      value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    readAt:
      value["readAt"] === null ? null : (value["readAt"] as any)?.toISOString(),
    expiresAt:
      value["expiresAt"] === null
        ? null
        : (value["expiresAt"] as any)?.toISOString(),
  };
}
