/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  page?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  total?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  pages?: number;
}

/**
 * Check if a given object implements the Pagination interface.
 */
export function instanceOfPagination(value: object): value is Pagination {
  return true;
}

export function PaginationFromJSON(json: any): Pagination {
  return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Pagination {
  if (json == null) {
    return json;
  }
  return {
    page: json["page"] == null ? undefined : json["page"],
    limit: json["limit"] == null ? undefined : json["limit"],
    total: json["total"] == null ? undefined : json["total"],
    pages: json["pages"] == null ? undefined : json["pages"],
  };
}

export function PaginationToJSON(json: any): Pagination {
  return PaginationToJSONTyped(json, false);
}

export function PaginationToJSONTyped(
  value?: Pagination | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    page: value["page"],
    limit: value["limit"],
    total: value["total"],
    pages: value["pages"],
  };
}
