/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PhaseStatus = {
  InProgress: "IN_PROGRESS",
  Complete: "COMPLETE",
} as const;
export type PhaseStatus = (typeof PhaseStatus)[keyof typeof PhaseStatus];

export function instanceOfPhaseStatus(value: any): boolean {
  for (const key in PhaseStatus) {
    if (Object.prototype.hasOwnProperty.call(PhaseStatus, key)) {
      if (PhaseStatus[key as keyof typeof PhaseStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function PhaseStatusFromJSON(json: any): PhaseStatus {
  return PhaseStatusFromJSONTyped(json, false);
}

export function PhaseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhaseStatus {
  return json as PhaseStatus;
}

export function PhaseStatusToJSON(value?: PhaseStatus | null): any {
  return value as any;
}

export function PhaseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PhaseStatus {
  return value as PhaseStatus;
}
