/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { PhaseKeyDates } from './PhaseKeyDates'
import {
  PhaseKeyDatesFromJSON,
  PhaseKeyDatesFromJSONTyped,
  PhaseKeyDatesToJSON,
  PhaseKeyDatesToJSONTyped,
} from './PhaseKeyDates'
import type { PhaseStatus } from './PhaseStatus'
import {
  PhaseStatusFromJSON,
  PhaseStatusFromJSONTyped,
  PhaseStatusToJSON,
  PhaseStatusToJSONTyped,
} from './PhaseStatus'

/**
 *
 * @export
 * @interface Phase
 */
export interface Phase {
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  meetingId?: string
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  orderIndex?: number
  /**
   *
   * @type {PhaseStatus}
   * @memberof Phase
   */
  status?: PhaseStatus
  /**
   *
   * @type {PhaseKeyDates}
   * @memberof Phase
   */
  keyDates?: PhaseKeyDates | null
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the Phase interface.
 */
export function instanceOfPhase(value: object): value is Phase {
  return true
}

export function PhaseFromJSON(json: any): Phase {
  return PhaseFromJSONTyped(json, false)
}

export function PhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Phase {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    name: json['name'] == null ? undefined : json['name'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
    status: json['status'] == null ? undefined : PhaseStatusFromJSON(json['status']),
    keyDates:
      json['keyDates'] == null ? undefined : PhaseKeyDatesFromJSON(json['keyDates']),
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  }
}

export function PhaseToJSON(json: any): Phase {
  return PhaseToJSONTyped(json, false)
}

export function PhaseToJSONTyped(
  value?: Phase | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    meetingId: value['meetingId'],
    name: value['name'],
    orderIndex: value['orderIndex'],
    status: PhaseStatusToJSON(value['status']),
    keyDates: PhaseKeyDatesToJSON(value['keyDates']),
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
  }
}
