/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface PositionVote
 */
export interface PositionVote {
  /**
   *
   * @type {string}
   * @memberof PositionVote
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof PositionVote
   */
  positionId?: string
  /**
   *
   * @type {string}
   * @memberof PositionVote
   */
  proposalId?: string
  /**
   *
   * @type {string}
   * @memberof PositionVote
   */
  vote?: string
  /**
   *
   * @type {string}
   * @memberof PositionVote
   */
  sharesVoting?: string
  /**
   *
   * @type {Date}
   * @memberof PositionVote
   */
  createdAt?: Date
}

/**
 * Check if a given object implements the PositionVote interface.
 */
export function instanceOfPositionVote(value: object): value is PositionVote {
  return true
}

export function PositionVoteFromJSON(json: any): PositionVote {
  return PositionVoteFromJSONTyped(json, false)
}

export function PositionVoteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PositionVote {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    positionId: json['positionId'] == null ? undefined : json['positionId'],
    proposalId: json['proposalId'] == null ? undefined : json['proposalId'],
    vote: json['vote'] == null ? undefined : json['vote'],
    sharesVoting: json['sharesVoting'] == null ? undefined : json['sharesVoting'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
  }
}

export function PositionVoteToJSON(json: any): PositionVote {
  return PositionVoteToJSONTyped(json, false)
}

export function PositionVoteToJSONTyped(
  value?: PositionVote | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    positionId: value['positionId'],
    proposalId: value['proposalId'],
    vote: value['vote'],
    sharesVoting: value['sharesVoting'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
  }
}
