/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SignFormDigitalRequest
 */
export interface SignFormDigitalRequest {
  /**
   *
   * @type {string}
   * @memberof SignFormDigitalRequest
   */
  meetingId: string;
  /**
   * User performing the digital signature
   * @type {string}
   * @memberof SignFormDigitalRequest
   */
  signerUserId: string;
  /**
   * Optional reason or context for the signature
   * @type {string}
   * @memberof SignFormDigitalRequest
   */
  signatureReason?: string;
  /**
   * If true, replaces any existing signature artifact
   * @type {boolean}
   * @memberof SignFormDigitalRequest
   */
  replaceExisting?: boolean;
}

/**
 * Check if a given object implements the SignFormDigitalRequest interface.
 */
export function instanceOfSignFormDigitalRequest(
  value: object
): value is SignFormDigitalRequest {
  if (!("meetingId" in value) || value["meetingId"] === undefined) return false;
  if (!("signerUserId" in value) || value["signerUserId"] === undefined)
    return false;
  return true;
}

export function SignFormDigitalRequestFromJSON(
  json: any
): SignFormDigitalRequest {
  return SignFormDigitalRequestFromJSONTyped(json, false);
}

export function SignFormDigitalRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SignFormDigitalRequest {
  if (json == null) {
    return json;
  }
  return {
    meetingId: json["meetingId"],
    signerUserId: json["signerUserId"],
    signatureReason:
      json["signatureReason"] == null ? undefined : json["signatureReason"],
    replaceExisting:
      json["replaceExisting"] == null ? undefined : json["replaceExisting"],
  };
}

export function SignFormDigitalRequestToJSON(
  json: any
): SignFormDigitalRequest {
  return SignFormDigitalRequestToJSONTyped(json, false);
}

export function SignFormDigitalRequestToJSONTyped(
  value?: SignFormDigitalRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    meetingId: value["meetingId"],
    signerUserId: value["signerUserId"],
    signatureReason: value["signatureReason"],
    replaceExisting: value["replaceExisting"],
  };
}
