/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 * Non-DTC shareholder vote status breakdown
 * @export
 * @interface TabulationReportNonDtcVoteStatus
 */
export interface TabulationReportNonDtcVoteStatus {
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  unvotedShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  unvotedShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  printShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  printShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  ivrShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  ivrShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  webShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  webShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  votedSubtotalShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  votedSubtotalShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  grandTotalShareholders?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportNonDtcVoteStatus
   */
  grandTotalShares?: number
}

/**
 * Check if a given object implements the TabulationReportNonDtcVoteStatus interface.
 */
export function instanceOfTabulationReportNonDtcVoteStatus(
  value: object
): value is TabulationReportNonDtcVoteStatus {
  return true
}

export function TabulationReportNonDtcVoteStatusFromJSON(
  json: any
): TabulationReportNonDtcVoteStatus {
  return TabulationReportNonDtcVoteStatusFromJSONTyped(json, false)
}

export function TabulationReportNonDtcVoteStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TabulationReportNonDtcVoteStatus {
  if (json == null) {
    return json
  }
  return {
    unvotedShareholders:
      json['unvotedShareholders'] == null ? undefined : json['unvotedShareholders'],
    unvotedShares: json['unvotedShares'] == null ? undefined : json['unvotedShares'],
    printShareholders:
      json['printShareholders'] == null ? undefined : json['printShareholders'],
    printShares: json['printShares'] == null ? undefined : json['printShares'],
    ivrShareholders:
      json['ivrShareholders'] == null ? undefined : json['ivrShareholders'],
    ivrShares: json['ivrShares'] == null ? undefined : json['ivrShares'],
    webShareholders:
      json['webShareholders'] == null ? undefined : json['webShareholders'],
    webShares: json['webShares'] == null ? undefined : json['webShares'],
    votedSubtotalShareholders:
      json['votedSubtotalShareholders'] == null
        ? undefined
        : json['votedSubtotalShareholders'],
    votedSubtotalShares:
      json['votedSubtotalShares'] == null ? undefined : json['votedSubtotalShares'],
    grandTotalShareholders:
      json['grandTotalShareholders'] == null ? undefined : json['grandTotalShareholders'],
    grandTotalShares:
      json['grandTotalShares'] == null ? undefined : json['grandTotalShares'],
  }
}

export function TabulationReportNonDtcVoteStatusToJSON(
  json: any
): TabulationReportNonDtcVoteStatus {
  return TabulationReportNonDtcVoteStatusToJSONTyped(json, false)
}

export function TabulationReportNonDtcVoteStatusToJSONTyped(
  value?: TabulationReportNonDtcVoteStatus | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    unvotedShareholders: value['unvotedShareholders'],
    unvotedShares: value['unvotedShares'],
    printShareholders: value['printShareholders'],
    printShares: value['printShares'],
    ivrShareholders: value['ivrShareholders'],
    ivrShares: value['ivrShares'],
    webShareholders: value['webShareholders'],
    webShares: value['webShares'],
    votedSubtotalShareholders: value['votedSubtotalShareholders'],
    votedSubtotalShares: value['votedSubtotalShares'],
    grandTotalShareholders: value['grandTotalShareholders'],
    grandTotalShares: value['grandTotalShares'],
  }
}
