/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TabulationReportBrokerVotingInner
 */
export interface TabulationReportBrokerVotingInner {
  /**
   *
   * @type {string}
   * @memberof TabulationReportBrokerVotingInner
   */
  broker?: string;
  /**
   *
   * @type {number}
   * @memberof TabulationReportBrokerVotingInner
   */
  sharesFor?: number;
  /**
   *
   * @type {number}
   * @memberof TabulationReportBrokerVotingInner
   */
  sharesAgainst?: number;
  /**
   *
   * @type {number}
   * @memberof TabulationReportBrokerVotingInner
   */
  sharesAbstain?: number;
}

/**
 * Check if a given object implements the TabulationReportBrokerVotingInner interface.
 */
export function instanceOfTabulationReportBrokerVotingInner(
  value: object
): value is TabulationReportBrokerVotingInner {
  return true;
}

export function TabulationReportBrokerVotingInnerFromJSON(
  json: any
): TabulationReportBrokerVotingInner {
  return TabulationReportBrokerVotingInnerFromJSONTyped(json, false);
}

export function TabulationReportBrokerVotingInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TabulationReportBrokerVotingInner {
  if (json == null) {
    return json;
  }
  return {
    broker: json["broker"] == null ? undefined : json["broker"],
    sharesFor: json["sharesFor"] == null ? undefined : json["sharesFor"],
    sharesAgainst:
      json["sharesAgainst"] == null ? undefined : json["sharesAgainst"],
    sharesAbstain:
      json["sharesAbstain"] == null ? undefined : json["sharesAbstain"],
  };
}

export function TabulationReportBrokerVotingInnerToJSON(
  json: any
): TabulationReportBrokerVotingInner {
  return TabulationReportBrokerVotingInnerToJSONTyped(json, false);
}

export function TabulationReportBrokerVotingInnerToJSONTyped(
  value?: TabulationReportBrokerVotingInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    broker: value["broker"],
    sharesFor: value["sharesFor"],
    sharesAgainst: value["sharesAgainst"],
    sharesAbstain: value["sharesAbstain"],
  };
}
