/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface TabulationReportShareRangePerformanceInner
 */
export interface TabulationReportShareRangePerformanceInner {
  /**
   *
   * @type {string}
   * @memberof TabulationReportShareRangePerformanceInner
   */
  rangeLabel?: string
  /**
   *
   * @type {number}
   * @memberof TabulationReportShareRangePerformanceInner
   */
  positionCount?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportShareRangePerformanceInner
   */
  totalShares?: number
  /**
   *
   * @type {number}
   * @memberof TabulationReportShareRangePerformanceInner
   */
  percentVoted?: number
}

/**
 * Check if a given object implements the TabulationReportShareRangePerformanceInner interface.
 */
export function instanceOfTabulationReportShareRangePerformanceInner(
  value: object
): value is TabulationReportShareRangePerformanceInner {
  return true
}

export function TabulationReportShareRangePerformanceInnerFromJSON(
  json: any
): TabulationReportShareRangePerformanceInner {
  return TabulationReportShareRangePerformanceInnerFromJSONTyped(json, false)
}

export function TabulationReportShareRangePerformanceInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TabulationReportShareRangePerformanceInner {
  if (json == null) {
    return json
  }
  return {
    rangeLabel: json['rangeLabel'] == null ? undefined : json['rangeLabel'],
    positionCount: json['positionCount'] == null ? undefined : json['positionCount'],
    totalShares: json['totalShares'] == null ? undefined : json['totalShares'],
    percentVoted: json['percentVoted'] == null ? undefined : json['percentVoted'],
  }
}

export function TabulationReportShareRangePerformanceInnerToJSON(
  json: any
): TabulationReportShareRangePerformanceInner {
  return TabulationReportShareRangePerformanceInnerToJSONTyped(json, false)
}

export function TabulationReportShareRangePerformanceInnerToJSONTyped(
  value?: TabulationReportShareRangePerformanceInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    rangeLabel: value['rangeLabel'],
    positionCount: value['positionCount'],
    totalShares: value['totalShares'],
    percentVoted: value['percentVoted'],
  }
}
