/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TaskStatus = {
  Incomplete: "INCOMPLETE",
  Complete: "COMPLETE",
  Cancelled: "CANCELLED",
  NeedsAuthorization: "NEEDS_AUTHORIZATION",
  Authorized: "AUTHORIZED",
  PendingAuthorization: "PENDING_AUTHORIZATION",
  WaitingForFormReturn: "WAITING_FOR_FORM_RETURN",
  AuthorizationNeeded: "AUTHORIZATION_NEEDED",
  SubmittedAwaitingRecordDate: "SUBMITTED_AWAITING_RECORD_DATE",
  RequestFormToFollow: "REQUEST_FORM_TO_FOLLOW",
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export function instanceOfTaskStatus(value: any): boolean {
  for (const key in TaskStatus) {
    if (Object.prototype.hasOwnProperty.call(TaskStatus, key)) {
      if (TaskStatus[key as keyof typeof TaskStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function TaskStatusFromJSON(json: any): TaskStatus {
  return TaskStatusFromJSONTyped(json, false);
}

export function TaskStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TaskStatus {
  return json as TaskStatus;
}

export function TaskStatusToJSON(value?: TaskStatus | null): any {
  return value as any;
}

export function TaskStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): TaskStatus {
  return value as TaskStatus;
}
