import type { TaskStatus } from "./TaskStatus";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  TaskStatusFromJSON,
  TaskStatusFromJSONTyped,
  TaskStatusToJSON,
  TaskStatusToJSONTyped,
} from "./TaskStatus";

/**
 *
 * @export
 * @interface Task
 */
export interface Task {
  /**
   *
   * @type {string}
   * @memberof Task
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  taskId?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  phaseId?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  meetingId?: string;
  /**
   *
   * @type {number}
   * @memberof Task
   */
  phaseNumber?: number;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  type?: string;
  /**
   *
   * @type {TaskStatus}
   * @memberof Task
   */
  status?: TaskStatus;
  /**
   *
   * @type {Date}
   * @memberof Task
   */
  dueDate?: Date | null;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  owner?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  documentId?: string | null;
  /**
   *
   * @type {object}
   * @memberof Task
   */
  links?: object | null;
  /**
   *
   * @type {Date}
   * @memberof Task
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof Task
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
  return true;
}

export function TaskFromJSON(json: any): Task {
  return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    taskId: json["taskId"] == null ? undefined : json["taskId"],
    phaseId: json["phaseId"] == null ? undefined : json["phaseId"],
    meetingId: json["meetingId"] == null ? undefined : json["meetingId"],
    phaseNumber: json["phaseNumber"] == null ? undefined : json["phaseNumber"],
    title: json["title"] == null ? undefined : json["title"],
    description: json["description"] == null ? undefined : json["description"],
    type: json["type"] == null ? undefined : json["type"],
    status: json["status"] == null ? undefined : TaskStatusFromJSON(json["status"]),
    dueDate: json["dueDate"] == null ? undefined : new Date(json["dueDate"]),
    owner: json["owner"] == null ? undefined : json["owner"],
    documentId: json["documentId"] == null ? undefined : json["documentId"],
    links: json["links"] == null ? undefined : json["links"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt: json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
  };
}

export function TaskToJSON(json: any): Task {
  return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    taskId: value["taskId"],
    phaseId: value["phaseId"],
    meetingId: value["meetingId"],
    phaseNumber: value["phaseNumber"],
    title: value["title"],
    description: value["description"],
    type: value["type"],
    status: TaskStatusToJSON(value["status"]),
    dueDate:
      value["dueDate"] === null ? null : (value["dueDate"] as any)?.toISOString().substring(0, 10),
    owner: value["owner"],
    documentId: value["documentId"],
    links: value["links"],
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"] == null ? undefined : value["updatedAt"].toISOString(),
  };
}
