/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { DocumentStatus } from './DocumentStatus'
import {
  DocumentStatusFromJSON,
  DocumentStatusFromJSONTyped,
  DocumentStatusToJSON,
  DocumentStatusToJSONTyped,
} from './DocumentStatus'

/**
 *
 * @export
 * @interface UpdateDocumentRequest
 */
export interface UpdateDocumentRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateDocumentRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof UpdateDocumentRequest
   */
  description?: string
  /**
   *
   * @type {DocumentStatus}
   * @memberof UpdateDocumentRequest
   */
  status?: DocumentStatus
}

/**
 * Check if a given object implements the UpdateDocumentRequest interface.
 */
export function instanceOfUpdateDocumentRequest(
  value: object
): value is UpdateDocumentRequest {
  return true
}

export function UpdateDocumentRequestFromJSON(json: any): UpdateDocumentRequest {
  return UpdateDocumentRequestFromJSONTyped(json, false)
}

export function UpdateDocumentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateDocumentRequest {
  if (json == null) {
    return json
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    status: json['status'] == null ? undefined : DocumentStatusFromJSON(json['status']),
  }
}

export function UpdateDocumentRequestToJSON(json: any): UpdateDocumentRequest {
  return UpdateDocumentRequestToJSONTyped(json, false)
}

export function UpdateDocumentRequestToJSONTyped(
  value?: UpdateDocumentRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    title: value['title'],
    description: value['description'],
    status: DocumentStatusToJSON(value['status']),
  }
}
