/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface UpdateAccountRequest
 */
export interface UpdateAccountRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateAccountRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateAccountRequest
   */
  primaryContact?: string;
  /**
   * The client this account belongs to
   * @type {string}
   * @memberof UpdateAccountRequest
   */
  clientId?: string;
}

/**
 * Check if a given object implements the UpdateAccountRequest interface.
 */
export function instanceOfUpdateAccountRequest(
  value: object
): value is UpdateAccountRequest {
  return true;
}

export function UpdateAccountRequestFromJSON(json: any): UpdateAccountRequest {
  return UpdateAccountRequestFromJSONTyped(json, false);
}

export function UpdateAccountRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateAccountRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    primaryContact:
      json["primaryContact"] == null ? undefined : json["primaryContact"],
    clientId: json["clientId"] == null ? undefined : json["clientId"],
  };
}

export function UpdateAccountRequestToJSON(json: any): UpdateAccountRequest {
  return UpdateAccountRequestToJSONTyped(json, false);
}

export function UpdateAccountRequestToJSONTyped(
  value?: UpdateAccountRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    primaryContact: value["primaryContact"],
    clientId: value["clientId"],
  };
}
