/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { PhaseStatus } from './PhaseStatus'
import {
  PhaseStatusFromJSON,
  PhaseStatusFromJSONTyped,
  PhaseStatusToJSON,
  PhaseStatusToJSONTyped,
} from './PhaseStatus'
import type { UpdatePhaseRequestKeyDates } from './UpdatePhaseRequestKeyDates'
import {
  UpdatePhaseRequestKeyDatesFromJSON,
  UpdatePhaseRequestKeyDatesFromJSONTyped,
  UpdatePhaseRequestKeyDatesToJSON,
  UpdatePhaseRequestKeyDatesToJSONTyped,
} from './UpdatePhaseRequestKeyDates'

/**
 *
 * @export
 * @interface UpdatePhaseRequest
 */
export interface UpdatePhaseRequest {
  /**
   *
   * @type {string}
   * @memberof UpdatePhaseRequest
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof UpdatePhaseRequest
   */
  orderIndex?: number
  /**
   *
   * @type {PhaseStatus}
   * @memberof UpdatePhaseRequest
   */
  status?: PhaseStatus
  /**
   *
   * @type {UpdatePhaseRequestKeyDates}
   * @memberof UpdatePhaseRequest
   */
  keyDates?: UpdatePhaseRequestKeyDates
}

/**
 * Check if a given object implements the UpdatePhaseRequest interface.
 */
export function instanceOfUpdatePhaseRequest(value: object): value is UpdatePhaseRequest {
  return true
}

export function UpdatePhaseRequestFromJSON(json: any): UpdatePhaseRequest {
  return UpdatePhaseRequestFromJSONTyped(json, false)
}

export function UpdatePhaseRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdatePhaseRequest {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    orderIndex: json['orderIndex'] == null ? undefined : json['orderIndex'],
    status: json['status'] == null ? undefined : PhaseStatusFromJSON(json['status']),
    keyDates:
      json['keyDates'] == null
        ? undefined
        : UpdatePhaseRequestKeyDatesFromJSON(json['keyDates']),
  }
}

export function UpdatePhaseRequestToJSON(json: any): UpdatePhaseRequest {
  return UpdatePhaseRequestToJSONTyped(json, false)
}

export function UpdatePhaseRequestToJSONTyped(
  value?: UpdatePhaseRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    orderIndex: value['orderIndex'],
    status: PhaseStatusToJSON(value['status']),
    keyDates: UpdatePhaseRequestKeyDatesToJSON(value['keyDates']),
  }
}
