/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { MeetingStatus } from './MeetingStatus'
import {
  MeetingStatusFromJSON,
  MeetingStatusFromJSONTyped,
  MeetingStatusToJSON,
  MeetingStatusToJSONTyped,
} from './MeetingStatus'

/**
 *
 * @export
 * @interface UpdateMeetingRequest
 */
export interface UpdateMeetingRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  title?: string
  /**
   *
   * @type {Date}
   * @memberof UpdateMeetingRequest
   */
  recordDate?: Date
  /**
   *
   * @type {Date}
   * @memberof UpdateMeetingRequest
   */
  mailingDate?: Date
  /**
   *
   * @type {Date}
   * @memberof UpdateMeetingRequest
   */
  meetingDate?: Date
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  meetingType?: string
  /**
   *
   * @type {MeetingStatus}
   * @memberof UpdateMeetingRequest
   */
  status?: MeetingStatus
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  currentPhase?: string
  /**
   *
   * @type {number}
   * @memberof UpdateMeetingRequest
   */
  overallCompletion?: number
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  distributionType?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  transferAgent?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  employeeStockPlans?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  planAdministrator?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  planAdministratorContact?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  planAdministratorContactEmail?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  solicitor?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  solicitorEmail?: string
  /**
   * IVR dial-in voting number
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  ivrDialInNumber?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingRequest
   */
  totalSharesOutstanding?: string
  /**
   *
   * @type {number}
   * @memberof UpdateMeetingRequest
   */
  quorumRequirement?: number
}

/**
 * Check if a given object implements the UpdateMeetingRequest interface.
 */
export function instanceOfUpdateMeetingRequest(
  value: object
): value is UpdateMeetingRequest {
  return true
}

export function UpdateMeetingRequestFromJSON(json: any): UpdateMeetingRequest {
  return UpdateMeetingRequestFromJSONTyped(json, false)
}

export function UpdateMeetingRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMeetingRequest {
  if (json == null) {
    return json
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    recordDate: json['recordDate'] == null ? undefined : new Date(json['recordDate']),
    mailingDate: json['mailingDate'] == null ? undefined : new Date(json['mailingDate']),
    meetingDate: json['meetingDate'] == null ? undefined : new Date(json['meetingDate']),
    meetingType: json['meetingType'] == null ? undefined : json['meetingType'],
    status: json['status'] == null ? undefined : MeetingStatusFromJSON(json['status']),
    currentPhase: json['currentPhase'] == null ? undefined : json['currentPhase'],
    overallCompletion:
      json['overallCompletion'] == null ? undefined : json['overallCompletion'],
    distributionType:
      json['distributionType'] == null ? undefined : json['distributionType'],
    transferAgent: json['transferAgent'] == null ? undefined : json['transferAgent'],
    employeeStockPlans:
      json['employeeStockPlans'] == null ? undefined : json['employeeStockPlans'],
    planAdministrator:
      json['planAdministrator'] == null ? undefined : json['planAdministrator'],
    planAdministratorContact:
      json['planAdministratorContact'] == null
        ? undefined
        : json['planAdministratorContact'],
    planAdministratorContactEmail:
      json['planAdministratorContactEmail'] == null
        ? undefined
        : json['planAdministratorContactEmail'],
    solicitor: json['solicitor'] == null ? undefined : json['solicitor'],
    solicitorEmail: json['solicitorEmail'] == null ? undefined : json['solicitorEmail'],
    ivrDialInNumber:
      json['ivrDialInNumber'] == null ? undefined : json['ivrDialInNumber'],
    totalSharesOutstanding:
      json['totalSharesOutstanding'] == null ? undefined : json['totalSharesOutstanding'],
    quorumRequirement:
      json['quorumRequirement'] == null ? undefined : json['quorumRequirement'],
  }
}

export function UpdateMeetingRequestToJSON(json: any): UpdateMeetingRequest {
  return UpdateMeetingRequestToJSONTyped(json, false)
}

export function UpdateMeetingRequestToJSONTyped(
  value?: UpdateMeetingRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    title: value['title'],
    recordDate:
      value['recordDate'] == null
        ? undefined
        : value['recordDate'].toISOString().substring(0, 10),
    mailingDate:
      value['mailingDate'] == null
        ? undefined
        : value['mailingDate'].toISOString().substring(0, 10),
    meetingDate:
      value['meetingDate'] == null
        ? undefined
        : value['meetingDate'].toISOString().substring(0, 10),
    meetingType: value['meetingType'],
    status: MeetingStatusToJSON(value['status']),
    currentPhase: value['currentPhase'],
    overallCompletion: value['overallCompletion'],
    distributionType: value['distributionType'],
    transferAgent: value['transferAgent'],
    employeeStockPlans: value['employeeStockPlans'],
    planAdministrator: value['planAdministrator'],
    planAdministratorContact: value['planAdministratorContact'],
    planAdministratorContactEmail: value['planAdministratorContactEmail'],
    solicitor: value['solicitor'],
    solicitorEmail: value['solicitorEmail'],
    ivrDialInNumber: value['ivrDialInNumber'],
    totalSharesOutstanding: value['totalSharesOutstanding'],
    quorumRequirement: value['quorumRequirement'],
  }
}
