import type { UserType } from "./UserType";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  UserTypeFromJSON,
  UserTypeFromJSONTyped,
  UserTypeToJSON,
  UserTypeToJSONTyped,
} from "./UserType";

/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  email?: string;
  /**
   *
   * @type {UserType}
   * @memberof UpdateUserRequest
   */
  type?: UserType;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  accountId?: string;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
  return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserRequest {
  if (json == null) {
    return json;
  }
  return {
    firstName: json["firstName"] == null ? undefined : json["firstName"],
    lastName: json["lastName"] == null ? undefined : json["lastName"],
    email: json["email"] == null ? undefined : json["email"],
    type: json["type"] == null ? undefined : UserTypeFromJSON(json["type"]),
    accountId: json["accountId"] == null ? undefined : json["accountId"],
  };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(
  value?: UpdateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    firstName: value["firstName"],
    lastName: value["lastName"],
    email: value["email"],
    type: UserTypeToJSON(value["type"]),
    accountId: value["accountId"],
  };
}
