/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { TaskStatus } from './TaskStatus'
import {
  TaskStatusFromJSON,
  TaskStatusFromJSONTyped,
  TaskStatusToJSON,
  TaskStatusToJSONTyped,
} from './TaskStatus'

/**
 *
 * @export
 * @interface UpdateTaskRequest
 */
export interface UpdateTaskRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateTaskRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof UpdateTaskRequest
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof UpdateTaskRequest
   */
  type?: string
  /**
   *
   * @type {TaskStatus}
   * @memberof UpdateTaskRequest
   */
  status?: TaskStatus
  /**
   *
   * @type {number}
   * @memberof UpdateTaskRequest
   */
  phaseNumber?: number
  /**
   *
   * @type {Date}
   * @memberof UpdateTaskRequest
   */
  dueDate?: Date
  /**
   *
   * @type {string}
   * @memberof UpdateTaskRequest
   */
  owner?: string
  /**
   *
   * @type {string}
   * @memberof UpdateTaskRequest
   */
  documentId?: string
  /**
   *
   * @type {object}
   * @memberof UpdateTaskRequest
   */
  links?: object
}

/**
 * Check if a given object implements the UpdateTaskRequest interface.
 */
export function instanceOfUpdateTaskRequest(value: object): value is UpdateTaskRequest {
  return true
}

export function UpdateTaskRequestFromJSON(json: any): UpdateTaskRequest {
  return UpdateTaskRequestFromJSONTyped(json, false)
}

export function UpdateTaskRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateTaskRequest {
  if (json == null) {
    return json
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    type: json['type'] == null ? undefined : json['type'],
    status: json['status'] == null ? undefined : TaskStatusFromJSON(json['status']),
    phaseNumber: json['phaseNumber'] == null ? undefined : json['phaseNumber'],
    dueDate: json['dueDate'] == null ? undefined : new Date(json['dueDate']),
    owner: json['owner'] == null ? undefined : json['owner'],
    documentId: json['documentId'] == null ? undefined : json['documentId'],
    links: json['links'] == null ? undefined : json['links'],
  }
}

export function UpdateTaskRequestToJSON(json: any): UpdateTaskRequest {
  return UpdateTaskRequestToJSONTyped(json, false)
}

export function UpdateTaskRequestToJSONTyped(
  value?: UpdateTaskRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    title: value['title'],
    description: value['description'],
    type: value['type'],
    status: TaskStatusToJSON(value['status']),
    phaseNumber: value['phaseNumber'],
    dueDate:
      value['dueDate'] == null
        ? undefined
        : value['dueDate'].toISOString().substring(0, 10),
    owner: value['owner'],
    documentId: value['documentId'],
    links: value['links'],
  }
}
