/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface UpdatePhaseRequestKeyDates
 */
export interface UpdatePhaseRequestKeyDates {
  /**
   *
   * @type {Date}
   * @memberof UpdatePhaseRequestKeyDates
   */
  startDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdatePhaseRequestKeyDates
   */
  endDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdatePhaseRequestKeyDates
   */
  dueDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdatePhaseRequestKeyDates
   */
  completionDate?: Date;
}

/**
 * Check if a given object implements the UpdatePhaseRequestKeyDates interface.
 */
export function instanceOfUpdatePhaseRequestKeyDates(
  value: object,
): value is UpdatePhaseRequestKeyDates {
  return true;
}

export function UpdatePhaseRequestKeyDatesFromJSON(json: any): UpdatePhaseRequestKeyDates {
  return UpdatePhaseRequestKeyDatesFromJSONTyped(json, false);
}

export function UpdatePhaseRequestKeyDatesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePhaseRequestKeyDates {
  if (json == null) {
    return json;
  }
  return {
    startDate: json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    dueDate: json["dueDate"] == null ? undefined : new Date(json["dueDate"]),
    completionDate: json["completionDate"] == null ? undefined : new Date(json["completionDate"]),
  };
}

export function UpdatePhaseRequestKeyDatesToJSON(json: any): UpdatePhaseRequestKeyDates {
  return UpdatePhaseRequestKeyDatesToJSONTyped(json, false);
}

export function UpdatePhaseRequestKeyDatesToJSONTyped(
  value?: UpdatePhaseRequestKeyDates | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    startDate:
      value["startDate"] == null ? undefined : value["startDate"].toISOString().substring(0, 10),
    endDate: value["endDate"] == null ? undefined : value["endDate"].toISOString().substring(0, 10),
    dueDate: value["dueDate"] == null ? undefined : value["dueDate"].toISOString().substring(0, 10),
    completionDate:
      value["completionDate"] == null
        ? undefined
        : value["completionDate"].toISOString().substring(0, 10),
  };
}
