import type { Account } from "./Account";
import type { UserType } from "./UserType";

/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import {
  AccountFromJSON,
  AccountFromJSONTyped,
  AccountToJSON,
  AccountToJSONTyped,
} from "./Account";
import {
  UserTypeFromJSON,
  UserTypeFromJSONTyped,
  UserTypeToJSON,
  UserTypeToJSONTyped,
} from "./UserType";

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string;
  /**
   * Legacy password field for seed data - not used with NextAuth
   * @type {string}
   * @memberof User
   */
  password?: string | null;
  /**
   *
   * @type {UserType}
   * @memberof User
   */
  type?: UserType;
  /**
   *
   * @type {string}
   * @memberof User
   */
  accountId?: string | null;
  /**
   *
   * @type {Account}
   * @memberof User
   */
  account?: Account;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    username: json["username"] == null ? undefined : json["username"],
    firstName: json["firstName"] == null ? undefined : json["firstName"],
    lastName: json["lastName"] == null ? undefined : json["lastName"],
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"] == null ? undefined : json["password"],
    type: json["type"] == null ? undefined : UserTypeFromJSON(json["type"]),
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    account: json["account"] == null ? undefined : AccountFromJSON(json["account"]),
  };
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    username: value["username"],
    firstName: value["firstName"],
    lastName: value["lastName"],
    email: value["email"],
    password: value["password"],
    type: UserTypeToJSON(value["type"]),
    accountId: value["accountId"],
    account: AccountToJSON(value["account"]),
  };
}
