/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  Account,
  CreateAccountRequest,
  CreateAccountUserRequest,
  ListAccountUsers200Response,
  ListAccounts200Response,
  ListUserAccounts200Response,
  UpdateAccountRequest,
  User,
  UserType,
} from "../models/index";

import {
  AccountFromJSON,
  AccountToJSON,
  CreateAccountRequestFromJSON,
  CreateAccountRequestToJSON,
  CreateAccountUserRequestFromJSON,
  CreateAccountUserRequestToJSON,
  ListAccountUsers200ResponseFromJSON,
  ListAccountUsers200ResponseToJSON,
  ListAccounts200ResponseFromJSON,
  ListAccounts200ResponseToJSON,
  ListUserAccounts200ResponseFromJSON,
  ListUserAccounts200ResponseToJSON,
  UpdateAccountRequestFromJSON,
  UpdateAccountRequestToJSON,
  UserFromJSON,
  UserToJSON,
  UserTypeFromJSON,
  UserTypeToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreateAccountOperationRequest {
  createAccountRequest: CreateAccountRequest;
}

export interface CreateAccountUserOperationRequest {
  accountId: string;
  createAccountUserRequest: CreateAccountUserRequest;
}

export interface DeleteAccountRequest {
  accountId: string;
}

export interface GetAccountByIdRequest {
  accountId: string;
}

export interface ListAccountUsersRequest {
  accountId: string;
  page?: number;
  limit?: number;
  type?: UserType;
}

export interface ListAccountsRequest {
  page?: number;
  limit?: number;
}

export interface ListClientAccountsRequest {
  ticker: string;
  page?: number;
  limit?: number;
}

export interface ListUserAccountsRequest {
  id: string;
}

export interface UpdateAccountOperationRequest {
  accountId: string;
  updateAccountRequest: UpdateAccountRequest;
}

/**
 *
 */
export class AccountsApi extends runtime.BaseAPI {
  /**
   * Create new account
   */
  async createAccountRaw(
    requestParameters: CreateAccountOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Account>> {
    if (requestParameters["createAccountRequest"] == null) {
      throw new runtime.RequiredError(
        "createAccountRequest",
        'Required parameter "createAccountRequest" was null or undefined when calling createAccount().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateAccountRequestToJSON(requestParameters["createAccountRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
  }

  /**
   * Create new account
   */
  async createAccount(
    requestParameters: CreateAccountOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Account> {
    const response = await this.createAccountRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Create new user for an account
   */
  async createAccountUserRaw(
    requestParameters: CreateAccountUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError(
        "accountId",
        'Required parameter "accountId" was null or undefined when calling createAccountUser().',
      );
    }

    if (requestParameters["createAccountUserRequest"] == null) {
      throw new runtime.RequiredError(
        "createAccountUserRequest",
        'Required parameter "createAccountUserRequest" was null or undefined when calling createAccountUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts/{accountId}/users`;
    urlPath = urlPath.replace(
      `{${"accountId"}}`,
      encodeURIComponent(String(requestParameters["accountId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateAccountUserRequestToJSON(requestParameters["createAccountUserRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Create new user for an account
   */
  async createAccountUser(
    requestParameters: CreateAccountUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<User> {
    const response = await this.createAccountUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete account
   */
  async deleteAccountRaw(
    requestParameters: DeleteAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError(
        "accountId",
        'Required parameter "accountId" was null or undefined when calling deleteAccount().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts/{accountId}`;
    urlPath = urlPath.replace(
      `{${"accountId"}}`,
      encodeURIComponent(String(requestParameters["accountId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete account
   */
  async deleteAccount(
    requestParameters: DeleteAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteAccountRaw(requestParameters, initOverrides);
  }

  /**
   * Get account by ID
   */
  async getAccountByIdRaw(
    requestParameters: GetAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Account>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError(
        "accountId",
        'Required parameter "accountId" was null or undefined when calling getAccountById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts/{accountId}`;
    urlPath = urlPath.replace(
      `{${"accountId"}}`,
      encodeURIComponent(String(requestParameters["accountId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
  }

  /**
   * Get account by ID
   */
  async getAccountById(
    requestParameters: GetAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Account> {
    const response = await this.getAccountByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List users for an account
   */
  async listAccountUsersRaw(
    requestParameters: ListAccountUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListAccountUsers200Response>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError(
        "accountId",
        'Required parameter "accountId" was null or undefined when calling listAccountUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts/{accountId}/users`;
    urlPath = urlPath.replace(
      `{${"accountId"}}`,
      encodeURIComponent(String(requestParameters["accountId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccountUsers200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List users for an account
   */
  async listAccountUsers(
    requestParameters: ListAccountUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListAccountUsers200Response> {
    const response = await this.listAccountUsersRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List accounts
   */
  async listAccountsRaw(
    requestParameters: ListAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListAccounts200Response>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccounts200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List accounts
   */
  async listAccounts(
    requestParameters: ListAccountsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListAccounts200Response> {
    const response = await this.listAccountsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List accounts for a client
   */
  async listClientAccountsRaw(
    requestParameters: ListClientAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListAccounts200Response>> {
    if (requestParameters["ticker"] == null) {
      throw new runtime.RequiredError(
        "ticker",
        'Required parameter "ticker" was null or undefined when calling listClientAccounts().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients/{ticker}/accounts`;
    urlPath = urlPath.replace(
      `{${"ticker"}}`,
      encodeURIComponent(String(requestParameters["ticker"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccounts200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List accounts for a client
   */
  async listClientAccounts(
    requestParameters: ListClientAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListAccounts200Response> {
    const response = await this.listClientAccountsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Returns accounts that a user has access to based on their role and relationships
   * Get accounts accessible by user
   */
  async listUserAccountsRaw(
    requestParameters: ListUserAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListUserAccounts200Response>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling listUserAccounts().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/users/{id}/accounts`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListUserAccounts200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Returns accounts that a user has access to based on their role and relationships
   * Get accounts accessible by user
   */
  async listUserAccounts(
    requestParameters: ListUserAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListUserAccounts200Response> {
    const response = await this.listUserAccountsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update account
   */
  async updateAccountRaw(
    requestParameters: UpdateAccountOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Account>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError(
        "accountId",
        'Required parameter "accountId" was null or undefined when calling updateAccount().',
      );
    }

    if (requestParameters["updateAccountRequest"] == null) {
      throw new runtime.RequiredError(
        "updateAccountRequest",
        'Required parameter "updateAccountRequest" was null or undefined when calling updateAccount().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/accounts/{accountId}`;
    urlPath = urlPath.replace(
      `{${"accountId"}}`,
      encodeURIComponent(String(requestParameters["accountId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateAccountRequestToJSON(requestParameters["updateAccountRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
  }

  /**
   * Update account
   */
  async updateAccount(
    requestParameters: UpdateAccountOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Account> {
    const response = await this.updateAccountRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
