/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  LoginUser200Response,
  LoginUserRequest,
  LogoutUser200Response,
  User,
} from '../models/index'
import {
  LoginUser200ResponseFromJSON,
  LoginUser200ResponseToJSON,
  LoginUserRequestFromJSON,
  LoginUserRequestToJSON,
  LogoutUser200ResponseFromJSON,
  LogoutUser200ResponseToJSON,
  UserFromJSON,
  UserToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface LoginUserOperationRequest {
  loginUserRequest: LoginUserRequest
}

/**
 *
 */
export class AuthenticationApi extends runtime.BaseAPI {
  /**
   * Get current user profile
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/auth/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue))
  }

  /**
   * Get current user profile
   */
  async getCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.getCurrentUserRaw(initOverrides)
    return await response.value()
  }

  /**
   * User login
   */
  async loginUserRaw(
    requestParameters: LoginUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginUser200Response>> {
    if (requestParameters['loginUserRequest'] == null) {
      throw new runtime.RequiredError(
        'loginUserRequest',
        'Required parameter "loginUserRequest" was null or undefined when calling loginUser().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    let urlPath = `/auth/login`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LoginUserRequestToJSON(requestParameters['loginUserRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LoginUser200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * User login
   */
  async loginUser(
    requestParameters: LoginUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginUser200Response> {
    const response = await this.loginUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * User logout
   */
  async logoutUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LogoutUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/auth/logout`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LogoutUser200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * User logout
   */
  async logoutUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LogoutUser200Response> {
    const response = await this.logoutUserRaw(initOverrides)
    return await response.value()
  }
}
