/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  Clients,
  CreateClientRequest,
  ListAccounts200Response,
  ListClients200Response,
  UpdateClientRequest,
} from "../models/index";

import {
  ClientsFromJSON,
  ClientsToJSON,
  CreateClientRequestFromJSON,
  CreateClientRequestToJSON,
  ListAccounts200ResponseFromJSON,
  ListAccounts200ResponseToJSON,
  ListClients200ResponseFromJSON,
  ListClients200ResponseToJSON,
  UpdateClientRequestFromJSON,
  UpdateClientRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreateClientOperationRequest {
  createClientRequest: CreateClientRequest;
}

export interface DeleteClientRequest {
  ticker: string;
}

export interface GetClientByTickerRequest {
  ticker: string;
}

export interface ListClientAccountsRequest {
  ticker: string;
  page?: number;
  limit?: number;
}

export interface ListClientsRequest {
  page?: number;
  limit?: number;
  ticker?: string;
}

export interface UpdateClientOperationRequest {
  ticker: string;
  updateClientRequest: UpdateClientRequest;
}

/**
 *
 */
export class ClientsApi extends runtime.BaseAPI {
  /**
   * Create new client
   */
  async createClientRaw(
    requestParameters: CreateClientOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Clients>> {
    if (requestParameters["createClientRequest"] == null) {
      throw new runtime.RequiredError(
        "createClientRequest",
        'Required parameter "createClientRequest" was null or undefined when calling createClient().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateClientRequestToJSON(
          requestParameters["createClientRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClientsFromJSON(jsonValue)
    );
  }

  /**
   * Create new client
   */
  async createClient(
    requestParameters: CreateClientOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Clients> {
    const response = await this.createClientRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Delete client
   */
  async deleteClientRaw(
    requestParameters: DeleteClientRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ticker"] == null) {
      throw new runtime.RequiredError(
        "ticker",
        'Required parameter "ticker" was null or undefined when calling deleteClient().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients/{ticker}`;
    urlPath = urlPath.replace(
      `{${"ticker"}}`,
      encodeURIComponent(String(requestParameters["ticker"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete client
   */
  async deleteClient(
    requestParameters: DeleteClientRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteClientRaw(requestParameters, initOverrides);
  }

  /**
   * Get client by ticker
   */
  async getClientByTickerRaw(
    requestParameters: GetClientByTickerRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Clients>> {
    if (requestParameters["ticker"] == null) {
      throw new runtime.RequiredError(
        "ticker",
        'Required parameter "ticker" was null or undefined when calling getClientByTicker().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients/{ticker}`;
    urlPath = urlPath.replace(
      `{${"ticker"}}`,
      encodeURIComponent(String(requestParameters["ticker"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClientsFromJSON(jsonValue)
    );
  }

  /**
   * Get client by ticker
   */
  async getClientByTicker(
    requestParameters: GetClientByTickerRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Clients> {
    const response = await this.getClientByTickerRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * List accounts for a client
   */
  async listClientAccountsRaw(
    requestParameters: ListClientAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListAccounts200Response>> {
    if (requestParameters["ticker"] == null) {
      throw new runtime.RequiredError(
        "ticker",
        'Required parameter "ticker" was null or undefined when calling listClientAccounts().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients/{ticker}/accounts`;
    urlPath = urlPath.replace(
      `{${"ticker"}}`,
      encodeURIComponent(String(requestParameters["ticker"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccounts200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * List accounts for a client
   */
  async listClientAccounts(
    requestParameters: ListClientAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListAccounts200Response> {
    const response = await this.listClientAccountsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * List clients
   */
  async listClientsRaw(
    requestParameters: ListClientsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListClients200Response>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["ticker"] != null) {
      queryParameters["ticker"] = requestParameters["ticker"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListClients200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * List clients
   */
  async listClients(
    requestParameters: ListClientsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListClients200Response> {
    const response = await this.listClientsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Update client
   */
  async updateClientRaw(
    requestParameters: UpdateClientOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Clients>> {
    if (requestParameters["ticker"] == null) {
      throw new runtime.RequiredError(
        "ticker",
        'Required parameter "ticker" was null or undefined when calling updateClient().'
      );
    }

    if (requestParameters["updateClientRequest"] == null) {
      throw new runtime.RequiredError(
        "updateClientRequest",
        'Required parameter "updateClientRequest" was null or undefined when calling updateClient().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/clients/{ticker}`;
    urlPath = urlPath.replace(
      `{${"ticker"}}`,
      encodeURIComponent(String(requestParameters["ticker"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateClientRequestToJSON(
          requestParameters["updateClientRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClientsFromJSON(jsonValue)
    );
  }

  /**
   * Update client
   */
  async updateClient(
    requestParameters: UpdateClientOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Clients> {
    const response = await this.updateClientRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
