/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Comment, CreateCommentRequest } from "../models/index";

import {
  CommentFromJSON,
  CommentToJSON,
  CreateCommentRequestFromJSON,
  CreateCommentRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface AddCommentRequest {
  id: string;
  createCommentRequest: CreateCommentRequest;
}

export interface GetDocumentCommentsRequest {
  id: string;
}

/**
 *
 */
export class CommentsApi extends runtime.BaseAPI {
  /**
   * Add comment to a document
   */
  async addCommentRaw(
    requestParameters: AddCommentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Comment>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling addComment().',
      );
    }

    if (requestParameters["createCommentRequest"] == null) {
      throw new runtime.RequiredError(
        "createCommentRequest",
        'Required parameter "createCommentRequest" was null or undefined when calling addComment().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}/comments`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateCommentRequestToJSON(requestParameters["createCommentRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => CommentFromJSON(jsonValue));
  }

  /**
   * Add comment to a document
   */
  async addComment(
    requestParameters: AddCommentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Comment> {
    const response = await this.addCommentRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get comments for a document
   */
  async getDocumentCommentsRaw(
    requestParameters: GetDocumentCommentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Comment>>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getDocumentComments().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}/comments`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentFromJSON));
  }

  /**
   * Get comments for a document
   */
  async getDocumentComments(
    requestParameters: GetDocumentCommentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Comment>> {
    const response = await this.getDocumentCommentsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
