/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  AddDocumentEventRequest,
  ApproveDocumentVersionRequest,
  Document,
  DocumentHistory,
  DocumentStatus,
  GetDocumentsReadiness200Response,
  SignFormDigitalRequest,
  UpdateDocumentRequest,
} from "../models/index";

import {
  AddDocumentEventRequestFromJSON,
  AddDocumentEventRequestToJSON,
  ApproveDocumentVersionRequestFromJSON,
  ApproveDocumentVersionRequestToJSON,
  DocumentFromJSON,
  DocumentHistoryFromJSON,
  DocumentHistoryToJSON,
  DocumentStatusFromJSON,
  DocumentStatusToJSON,
  DocumentToJSON,
  GetDocumentsReadiness200ResponseFromJSON,
  GetDocumentsReadiness200ResponseToJSON,
  SignFormDigitalRequestFromJSON,
  SignFormDigitalRequestToJSON,
  UpdateDocumentRequestFromJSON,
  UpdateDocumentRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface AddDocumentEventOperationRequest {
  id: string;
  addDocumentEventRequest: AddDocumentEventRequest;
}

export interface ApproveDocumentVersionOperationRequest {
  documentType: string;
  versionId: string;
  approveDocumentVersionRequest: ApproveDocumentVersionRequest;
}

export interface CreateDocumentRequest {
  meetingId: string;
  title: string;
  type: string;
  file: Blob;
  description?: string | null;
  taskId?: string | null;
}

export interface DownloadDocumentRequest {
  id: string;
}

export interface GetDocumentByIdRequest {
  id: string;
}

export interface GetDocumentEventsRequest {
  id: string;
}

export interface GetDocumentHistoryRequest {
  documentType: string;
  meetingId: string;
}

export interface GetDocumentsReadinessRequest {
  meetingId: string;
}

export interface ListDocumentsRequest {
  meetingId: string;
  status?: DocumentStatus;
  type?: string;
}

export interface ReplaceApprovedVersionRequest {
  documentType: string;
  versionId: string;
  meetingId: string;
  reason: string;
  file: Blob;
}

export interface SignFormDigitalOperationRequest {
  formType: SignFormDigitalOperationFormTypeEnum;
  signFormDigitalRequest: SignFormDigitalRequest;
}

export interface UpdateDocumentOperationRequest {
  id: string;
  updateDocumentRequest: UpdateDocumentRequest;
}

export interface UploadDocumentVersionRequest {
  documentType: string;
  meetingId: string;
  file: Blob;
  versionNotes?: string;
}

export interface UploadExecutedFormRequest {
  formType: UploadExecutedFormFormTypeEnum;
  meetingId: string;
  file: Blob;
  originalGeneratedId?: string;
}

/**
 *
 */
export class DocumentsApi extends runtime.BaseAPI {
  /**
   * Add event to document history
   */
  async addDocumentEventRaw(
    requestParameters: AddDocumentEventOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DocumentHistory>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling addDocumentEvent().'
      );
    }

    if (requestParameters["addDocumentEventRequest"] == null) {
      throw new runtime.RequiredError(
        "addDocumentEventRequest",
        'Required parameter "addDocumentEventRequest" was null or undefined when calling addDocumentEvent().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}/events`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: AddDocumentEventRequestToJSON(
          requestParameters["addDocumentEventRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentHistoryFromJSON(jsonValue)
    );
  }

  /**
   * Add event to document history
   */
  async addDocumentEvent(
    requestParameters: AddDocumentEventOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DocumentHistory> {
    const response = await this.addDocumentEventRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Approve a pending proxy material version
   */
  async approveDocumentVersionRaw(
    requestParameters: ApproveDocumentVersionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["documentType"] == null) {
      throw new runtime.RequiredError(
        "documentType",
        'Required parameter "documentType" was null or undefined when calling approveDocumentVersion().'
      );
    }

    if (requestParameters["versionId"] == null) {
      throw new runtime.RequiredError(
        "versionId",
        'Required parameter "versionId" was null or undefined when calling approveDocumentVersion().'
      );
    }

    if (requestParameters["approveDocumentVersionRequest"] == null) {
      throw new runtime.RequiredError(
        "approveDocumentVersionRequest",
        'Required parameter "approveDocumentVersionRequest" was null or undefined when calling approveDocumentVersion().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/types/{documentType}/{versionId}/approve`;
    urlPath = urlPath.replace(
      `{${"documentType"}}`,
      encodeURIComponent(String(requestParameters["documentType"]))
    );
    urlPath = urlPath.replace(
      `{${"versionId"}}`,
      encodeURIComponent(String(requestParameters["versionId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ApproveDocumentVersionRequestToJSON(
          requestParameters["approveDocumentVersionRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Approve a pending proxy material version
   */
  async approveDocumentVersion(
    requestParameters: ApproveDocumentVersionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.approveDocumentVersionRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Create new document
   */
  async createDocumentRaw(
    requestParameters: CreateDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling createDocument().'
      );
    }

    if (requestParameters["title"] == null) {
      throw new runtime.RequiredError(
        "title",
        'Required parameter "title" was null or undefined when calling createDocument().'
      );
    }

    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling createDocument().'
      );
    }

    if (requestParameters["file"] == null) {
      throw new runtime.RequiredError(
        "file",
        'Required parameter "file" was null or undefined when calling createDocument().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [
      { contentType: "multipart/form-data" },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["title"] != null) {
      formParams.append("title", requestParameters["title"] as any);
    }

    if (requestParameters["description"] != null) {
      formParams.append("description", requestParameters["description"] as any);
    }

    if (requestParameters["type"] != null) {
      formParams.append("type", requestParameters["type"] as any);
    }

    if (requestParameters["taskId"] != null) {
      formParams.append("taskId", requestParameters["taskId"] as any);
    }

    if (requestParameters["file"] != null) {
      formParams.append("file", requestParameters["file"] as any);
    }

    let urlPath = `/meetings/{meetingId}/documents`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Create new document
   */
  async createDocument(
    requestParameters: CreateDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.createDocumentRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Download document file
   */
  async downloadDocumentRaw(
    requestParameters: DownloadDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling downloadDocument().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}/download`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Download document file
   */
  async downloadDocument(
    requestParameters: DownloadDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob> {
    const response = await this.downloadDocumentRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get document by ID
   */
  async getDocumentByIdRaw(
    requestParameters: GetDocumentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getDocumentById().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Get document by ID
   */
  async getDocumentById(
    requestParameters: GetDocumentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.getDocumentByIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get event history for a specific document
   */
  async getDocumentEventsRaw(
    requestParameters: GetDocumentEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<DocumentHistory>>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getDocumentEvents().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}/events`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DocumentHistoryFromJSON)
    );
  }

  /**
   * Get event history for a specific document
   */
  async getDocumentEvents(
    requestParameters: GetDocumentEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<DocumentHistory>> {
    const response = await this.getDocumentEventsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get version history for a document type within a meeting
   */
  async getDocumentHistoryRaw(
    requestParameters: GetDocumentHistoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Document>>> {
    if (requestParameters["documentType"] == null) {
      throw new runtime.RequiredError(
        "documentType",
        'Required parameter "documentType" was null or undefined when calling getDocumentHistory().'
      );
    }

    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling getDocumentHistory().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["meetingId"] != null) {
      queryParameters["meetingId"] = requestParameters["meetingId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/types/{documentType}/history`;
    urlPath = urlPath.replace(
      `{${"documentType"}}`,
      encodeURIComponent(String(requestParameters["documentType"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DocumentFromJSON)
    );
  }

  /**
   * Get version history for a document type within a meeting
   */
  async getDocumentHistory(
    requestParameters: GetDocumentHistoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Document>> {
    const response = await this.getDocumentHistoryRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get readiness aggregation for a meeting
   */
  async getDocumentsReadinessRaw(
    requestParameters: GetDocumentsReadinessRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetDocumentsReadiness200Response>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling getDocumentsReadiness().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["meetingId"] != null) {
      queryParameters["meetingId"] = requestParameters["meetingId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/readiness`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetDocumentsReadiness200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get readiness aggregation for a meeting
   */
  async getDocumentsReadiness(
    requestParameters: GetDocumentsReadinessRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetDocumentsReadiness200Response> {
    const response = await this.getDocumentsReadinessRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * List documents for a meeting
   */
  async listDocumentsRaw(
    requestParameters: ListDocumentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Document>>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling listDocuments().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/documents`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DocumentFromJSON)
    );
  }

  /**
   * List documents for a meeting
   */
  async listDocuments(
    requestParameters: ListDocumentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Document>> {
    const response = await this.listDocumentsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Replace an approved proxy material (creates new pending version)
   */
  async replaceApprovedVersionRaw(
    requestParameters: ReplaceApprovedVersionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["documentType"] == null) {
      throw new runtime.RequiredError(
        "documentType",
        'Required parameter "documentType" was null or undefined when calling replaceApprovedVersion().'
      );
    }

    if (requestParameters["versionId"] == null) {
      throw new runtime.RequiredError(
        "versionId",
        'Required parameter "versionId" was null or undefined when calling replaceApprovedVersion().'
      );
    }

    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling replaceApprovedVersion().'
      );
    }

    if (requestParameters["reason"] == null) {
      throw new runtime.RequiredError(
        "reason",
        'Required parameter "reason" was null or undefined when calling replaceApprovedVersion().'
      );
    }

    if (requestParameters["file"] == null) {
      throw new runtime.RequiredError(
        "file",
        'Required parameter "file" was null or undefined when calling replaceApprovedVersion().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [
      { contentType: "multipart/form-data" },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["meetingId"] != null) {
      formParams.append("meetingId", requestParameters["meetingId"] as any);
    }

    if (requestParameters["reason"] != null) {
      formParams.append("reason", requestParameters["reason"] as any);
    }

    if (requestParameters["file"] != null) {
      formParams.append("file", requestParameters["file"] as any);
    }

    let urlPath = `/documents/types/{documentType}/{versionId}/replace`;
    urlPath = urlPath.replace(
      `{${"documentType"}}`,
      encodeURIComponent(String(requestParameters["documentType"]))
    );
    urlPath = urlPath.replace(
      `{${"versionId"}}`,
      encodeURIComponent(String(requestParameters["versionId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Replace an approved proxy material (creates new pending version)
   */
  async replaceApprovedVersion(
    requestParameters: ReplaceApprovedVersionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.replaceApprovedVersionRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Digitally sign a generated form
   */
  async signFormDigitalRaw(
    requestParameters: SignFormDigitalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["formType"] == null) {
      throw new runtime.RequiredError(
        "formType",
        'Required parameter "formType" was null or undefined when calling signFormDigital().'
      );
    }

    if (requestParameters["signFormDigitalRequest"] == null) {
      throw new runtime.RequiredError(
        "signFormDigitalRequest",
        'Required parameter "signFormDigitalRequest" was null or undefined when calling signFormDigital().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/forms/{formType}/sign-digital`;
    urlPath = urlPath.replace(
      `{${"formType"}}`,
      encodeURIComponent(String(requestParameters["formType"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SignFormDigitalRequestToJSON(
          requestParameters["signFormDigitalRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Digitally sign a generated form
   */
  async signFormDigital(
    requestParameters: SignFormDigitalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.signFormDigitalRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Update document
   */
  async updateDocumentRaw(
    requestParameters: UpdateDocumentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling updateDocument().'
      );
    }

    if (requestParameters["updateDocumentRequest"] == null) {
      throw new runtime.RequiredError(
        "updateDocumentRequest",
        'Required parameter "updateDocumentRequest" was null or undefined when calling updateDocument().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/documents/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateDocumentRequestToJSON(
          requestParameters["updateDocumentRequest"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Update document
   */
  async updateDocument(
    requestParameters: UpdateDocumentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.updateDocumentRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Upload or create a new document version (proxy or supporting)
   */
  async uploadDocumentVersionRaw(
    requestParameters: UploadDocumentVersionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["documentType"] == null) {
      throw new runtime.RequiredError(
        "documentType",
        'Required parameter "documentType" was null or undefined when calling uploadDocumentVersion().'
      );
    }

    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling uploadDocumentVersion().'
      );
    }

    if (requestParameters["file"] == null) {
      throw new runtime.RequiredError(
        "file",
        'Required parameter "file" was null or undefined when calling uploadDocumentVersion().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [
      { contentType: "multipart/form-data" },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["meetingId"] != null) {
      formParams.append("meetingId", requestParameters["meetingId"] as any);
    }

    if (requestParameters["file"] != null) {
      formParams.append("file", requestParameters["file"] as any);
    }

    if (requestParameters["versionNotes"] != null) {
      formParams.append(
        "versionNotes",
        requestParameters["versionNotes"] as any
      );
    }

    let urlPath = `/documents/types/{documentType}/upload`;
    urlPath = urlPath.replace(
      `{${"documentType"}}`,
      encodeURIComponent(String(requestParameters["documentType"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Upload or create a new document version (proxy or supporting)
   */
  async uploadDocumentVersion(
    requestParameters: UploadDocumentVersionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.uploadDocumentVersionRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Upload executed (wet-signed) form PDF
   */
  async uploadExecutedFormRaw(
    requestParameters: UploadExecutedFormRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Document>> {
    if (requestParameters["formType"] == null) {
      throw new runtime.RequiredError(
        "formType",
        'Required parameter "formType" was null or undefined when calling uploadExecutedForm().'
      );
    }

    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling uploadExecutedForm().'
      );
    }

    if (requestParameters["file"] == null) {
      throw new runtime.RequiredError(
        "file",
        'Required parameter "file" was null or undefined when calling uploadExecutedForm().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [
      { contentType: "multipart/form-data" },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["meetingId"] != null) {
      formParams.append("meetingId", requestParameters["meetingId"] as any);
    }

    if (requestParameters["file"] != null) {
      formParams.append("file", requestParameters["file"] as any);
    }

    if (requestParameters["originalGeneratedId"] != null) {
      formParams.append(
        "originalGeneratedId",
        requestParameters["originalGeneratedId"] as any
      );
    }

    let urlPath = `/documents/forms/{formType}/upload-executed`;
    urlPath = urlPath.replace(
      `{${"formType"}}`,
      encodeURIComponent(String(requestParameters["formType"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentFromJSON(jsonValue)
    );
  }

  /**
   * Upload executed (wet-signed) form PDF
   */
  async uploadExecutedForm(
    requestParameters: UploadExecutedFormRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Document> {
    const response = await this.uploadExecutedFormRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}

/**
 * @export
 */
export const SignFormDigitalOperationFormTypeEnum = {
  FormOfProxy: "FORM_OF_PROXY",
  Vif: "VIF",
  ControlledAccountReport: "CONTROLLED_ACCOUNT_REPORT",
} as const;
export type SignFormDigitalOperationFormTypeEnum =
  (typeof SignFormDigitalOperationFormTypeEnum)[keyof typeof SignFormDigitalOperationFormTypeEnum];
/**
 * @export
 */
export const UploadExecutedFormFormTypeEnum = {
  FormOfProxy: "FORM_OF_PROXY",
  Vif: "VIF",
  ControlledAccountReport: "CONTROLLED_ACCOUNT_REPORT",
} as const;
export type UploadExecutedFormFormTypeEnum =
  (typeof UploadExecutedFormFormTypeEnum)[keyof typeof UploadExecutedFormFormTypeEnum];
