/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  CreateDigitalShareholderMeetingRequest,
  CreateMeetingRequest,
  DSMConfig,
  DigitalShareholderMeeting,
  ListMeetings200Response,
  Meeting,
  MeetingStatus,
  UpdateMeetingRequest,
} from "../models/index";

import {
  CreateDigitalShareholderMeetingRequestFromJSON,
  CreateDigitalShareholderMeetingRequestToJSON,
  CreateMeetingRequestFromJSON,
  CreateMeetingRequestToJSON,
  DSMConfigFromJSON,
  DSMConfigToJSON,
  DigitalShareholderMeetingFromJSON,
  DigitalShareholderMeetingToJSON,
  ListMeetings200ResponseFromJSON,
  ListMeetings200ResponseToJSON,
  MeetingFromJSON,
  MeetingStatusFromJSON,
  MeetingStatusToJSON,
  MeetingToJSON,
  UpdateMeetingRequestFromJSON,
  UpdateMeetingRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreateDigitalShareholderMeetingAttendeesRequest {
  meetingId: string;
  createDigitalShareholderMeetingRequest: Array<CreateDigitalShareholderMeetingRequest>;
}

export interface CreateMeetingOperationRequest {
  createMeetingRequest: CreateMeetingRequest;
}

export interface CreateOrUpdateDSMConfigRequest {
  meetingId: string;
  dSMConfig: DSMConfig;
}

export interface DeleteMeetingRequest {
  meetingId: string;
}

export interface GetDSMConfigRequest {
  meetingId: string;
}

export interface GetDigitalShareholderMeetingRequest {
  meetingId: string;
}

export interface GetMeetingByIdRequest {
  meetingId: string;
}

export interface ListMeetingsRequest {
  page?: number;
  limit?: number;
  status?: MeetingStatus;
  clientId?: string;
  meetingYear?: number;
  cusip?: string;
  ticker?: string;
}

export interface UpdateDSMConfigRequest {
  meetingId: string;
  dSMConfig: DSMConfig;
}

export interface UpdateMeetingOperationRequest {
  meetingId: string;
  updateMeetingRequest: UpdateMeetingRequest;
}

/**
 *
 */
export class MeetingsApi extends runtime.BaseAPI {
  /**
   * Bulk create digital shareholder meeting attendees
   */
  async createDigitalShareholderMeetingAttendeesRaw(
    requestParameters: CreateDigitalShareholderMeetingAttendeesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<DigitalShareholderMeeting>>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling createDigitalShareholderMeetingAttendees().',
      );
    }

    if (requestParameters["createDigitalShareholderMeetingRequest"] == null) {
      throw new runtime.RequiredError(
        "createDigitalShareholderMeetingRequest",
        'Required parameter "createDigitalShareholderMeetingRequest" was null or undefined when calling createDigitalShareholderMeetingAttendees().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/digital-shareholder-meeting`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["createDigitalShareholderMeetingRequest"]!.map(
          CreateDigitalShareholderMeetingRequestToJSON,
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DigitalShareholderMeetingFromJSON),
    );
  }

  /**
   * Bulk create digital shareholder meeting attendees
   */
  async createDigitalShareholderMeetingAttendees(
    requestParameters: CreateDigitalShareholderMeetingAttendeesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<DigitalShareholderMeeting>> {
    const response = await this.createDigitalShareholderMeetingAttendeesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Create new meeting
   */
  async createMeetingRaw(
    requestParameters: CreateMeetingOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Meeting>> {
    if (requestParameters["createMeetingRequest"] == null) {
      throw new runtime.RequiredError(
        "createMeetingRequest",
        'Required parameter "createMeetingRequest" was null or undefined when calling createMeeting().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateMeetingRequestToJSON(requestParameters["createMeetingRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingFromJSON(jsonValue));
  }

  /**
   * Create new meeting
   */
  async createMeeting(
    requestParameters: CreateMeetingOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Meeting> {
    const response = await this.createMeetingRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Create or update DSM configuration
   */
  async createOrUpdateDSMConfigRaw(
    requestParameters: CreateOrUpdateDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DSMConfig>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling createOrUpdateDSMConfig().',
      );
    }

    if (requestParameters["dSMConfig"] == null) {
      throw new runtime.RequiredError(
        "dSMConfig",
        'Required parameter "dSMConfig" was null or undefined when calling createOrUpdateDSMConfig().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/dsm-config`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: DSMConfigToJSON(requestParameters["dSMConfig"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DSMConfigFromJSON(jsonValue));
  }

  /**
   * Create or update DSM configuration
   */
  async createOrUpdateDSMConfig(
    requestParameters: CreateOrUpdateDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DSMConfig> {
    const response = await this.createOrUpdateDSMConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete meeting
   */
  async deleteMeetingRaw(
    requestParameters: DeleteMeetingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling deleteMeeting().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete meeting
   */
  async deleteMeeting(
    requestParameters: DeleteMeetingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteMeetingRaw(requestParameters, initOverrides);
  }

  /**
   * Get DSM configuration for a meeting
   */
  async getDSMConfigRaw(
    requestParameters: GetDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DSMConfig>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling getDSMConfig().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/dsm-config`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DSMConfigFromJSON(jsonValue));
  }

  /**
   * Get DSM configuration for a meeting
   */
  async getDSMConfig(
    requestParameters: GetDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DSMConfig> {
    const response = await this.getDSMConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get digital shareholder meeting attendees
   */
  async getDigitalShareholderMeetingRaw(
    requestParameters: GetDigitalShareholderMeetingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<DigitalShareholderMeeting>>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling getDigitalShareholderMeeting().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/digital-shareholder-meeting`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DigitalShareholderMeetingFromJSON),
    );
  }

  /**
   * Get digital shareholder meeting attendees
   */
  async getDigitalShareholderMeeting(
    requestParameters: GetDigitalShareholderMeetingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<DigitalShareholderMeeting>> {
    const response = await this.getDigitalShareholderMeetingRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get meeting by ID
   */
  async getMeetingByIdRaw(
    requestParameters: GetMeetingByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Meeting>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling getMeetingById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingFromJSON(jsonValue));
  }

  /**
   * Get meeting by ID
   */
  async getMeetingById(
    requestParameters: GetMeetingByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Meeting> {
    const response = await this.getMeetingByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List meetings
   */
  async listMeetingsRaw(
    requestParameters: ListMeetingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListMeetings200Response>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["clientId"] != null) {
      queryParameters["clientId"] = requestParameters["clientId"];
    }

    if (requestParameters["meetingYear"] != null) {
      queryParameters["meetingYear"] = requestParameters["meetingYear"];
    }

    if (requestParameters["cusip"] != null) {
      queryParameters["cusip"] = requestParameters["cusip"];
    }

    if (requestParameters["ticker"] != null) {
      queryParameters["ticker"] = requestParameters["ticker"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListMeetings200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List meetings
   */
  async listMeetings(
    requestParameters: ListMeetingsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListMeetings200Response> {
    const response = await this.listMeetingsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update DSM configuration
   */
  async updateDSMConfigRaw(
    requestParameters: UpdateDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DSMConfig>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling updateDSMConfig().',
      );
    }

    if (requestParameters["dSMConfig"] == null) {
      throw new runtime.RequiredError(
        "dSMConfig",
        'Required parameter "dSMConfig" was null or undefined when calling updateDSMConfig().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/dsm-config`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: DSMConfigToJSON(requestParameters["dSMConfig"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DSMConfigFromJSON(jsonValue));
  }

  /**
   * Update DSM configuration
   */
  async updateDSMConfig(
    requestParameters: UpdateDSMConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DSMConfig> {
    const response = await this.updateDSMConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update meeting
   */
  async updateMeetingRaw(
    requestParameters: UpdateMeetingOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Meeting>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling updateMeeting().',
      );
    }

    if (requestParameters["updateMeetingRequest"] == null) {
      throw new runtime.RequiredError(
        "updateMeetingRequest",
        'Required parameter "updateMeetingRequest" was null or undefined when calling updateMeeting().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateMeetingRequestToJSON(requestParameters["updateMeetingRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingFromJSON(jsonValue));
  }

  /**
   * Update meeting
   */
  async updateMeeting(
    requestParameters: UpdateMeetingOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Meeting> {
    const response = await this.updateMeetingRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
