/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ListNotifications200Response, Notification } from "../models/index";

import {
  ListNotifications200ResponseFromJSON,
  ListNotifications200ResponseToJSON,
  NotificationFromJSON,
  NotificationToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ListNotificationsRequest {
  read?: boolean;
  type?: ListNotificationsTypeEnum;
  priority?: ListNotificationsPriorityEnum;
  page?: number;
  limit?: number;
}

export interface MarkNotificationReadRequest {
  notificationId: string;
}

/**
 *
 */
export class NotificationsApi extends runtime.BaseAPI {
  /**
   * List user notifications
   */
  async listNotificationsRaw(
    requestParameters: ListNotificationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListNotifications200Response>> {
    const queryParameters: any = {};

    if (requestParameters["read"] != null) {
      queryParameters["read"] = requestParameters["read"];
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["priority"] != null) {
      queryParameters["priority"] = requestParameters["priority"];
    }

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/notifications`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListNotifications200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List user notifications
   */
  async listNotifications(
    requestParameters: ListNotificationsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListNotifications200Response> {
    const response = await this.listNotificationsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Mark notification as read
   */
  async markNotificationReadRaw(
    requestParameters: MarkNotificationReadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Notification>> {
    if (requestParameters["notificationId"] == null) {
      throw new runtime.RequiredError(
        "notificationId",
        'Required parameter "notificationId" was null or undefined when calling markNotificationRead().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/notifications/{notificationId}/mark-read`;
    urlPath = urlPath.replace(
      `{${"notificationId"}}`,
      encodeURIComponent(String(requestParameters["notificationId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
  }

  /**
   * Mark notification as read
   */
  async markNotificationRead(
    requestParameters: MarkNotificationReadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Notification> {
    const response = await this.markNotificationReadRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ListNotificationsTypeEnum = {
  Info: "info",
  Warning: "warning",
  Error: "error",
  Success: "success",
} as const;
export type ListNotificationsTypeEnum =
  (typeof ListNotificationsTypeEnum)[keyof typeof ListNotificationsTypeEnum];
/**
 * @export
 */
export const ListNotificationsPriorityEnum = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Critical: "critical",
} as const;
export type ListNotificationsPriorityEnum =
  (typeof ListNotificationsPriorityEnum)[keyof typeof ListNotificationsPriorityEnum];
