/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  CreatePhaseRequest,
  Phase,
  PhaseStatus,
  UpdatePhaseRequest,
} from '../models/index'
import {
  CreatePhaseRequestFromJSON,
  CreatePhaseRequestToJSON,
  PhaseFromJSON,
  PhaseStatusFromJSON,
  PhaseStatusToJSON,
  PhaseToJSON,
  UpdatePhaseRequestFromJSON,
  UpdatePhaseRequestToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface CreatePhaseOperationRequest {
  meetingId: string
  createPhaseRequest: CreatePhaseRequest
}

export interface GetPhaseByIdRequest {
  id: string
}

export interface ListPhasesRequest {
  meetingId: string
  status?: PhaseStatus
}

export interface UpdatePhaseOperationRequest {
  id: string
  updatePhaseRequest: UpdatePhaseRequest
}

/**
 *
 */
export class PhasesApi extends runtime.BaseAPI {
  /**
   * Create new phase
   */
  async createPhaseRaw(
    requestParameters: CreatePhaseOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Phase>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling createPhase().'
      )
    }

    if (requestParameters['createPhaseRequest'] == null) {
      throw new runtime.RequiredError(
        'createPhaseRequest',
        'Required parameter "createPhaseRequest" was null or undefined when calling createPhase().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/phases`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreatePhaseRequestToJSON(requestParameters['createPhaseRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue))
  }

  /**
   * Create new phase
   */
  async createPhase(
    requestParameters: CreatePhaseOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Phase> {
    const response = await this.createPhaseRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get phase by ID
   */
  async getPhaseByIdRaw(
    requestParameters: GetPhaseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Phase>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getPhaseById().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/phases/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue))
  }

  /**
   * Get phase by ID
   */
  async getPhaseById(
    requestParameters: GetPhaseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Phase> {
    const response = await this.getPhaseByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List phases for a meeting
   */
  async listPhasesRaw(
    requestParameters: ListPhasesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Phase>>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling listPhases().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['status'] != null) {
      queryParameters['status'] = requestParameters['status']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/phases`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PhaseFromJSON)
    )
  }

  /**
   * List phases for a meeting
   */
  async listPhases(
    requestParameters: ListPhasesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Phase>> {
    const response = await this.listPhasesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Update phase
   */
  async updatePhaseRaw(
    requestParameters: UpdatePhaseOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Phase>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updatePhase().'
      )
    }

    if (requestParameters['updatePhaseRequest'] == null) {
      throw new runtime.RequiredError(
        'updatePhaseRequest',
        'Required parameter "updatePhaseRequest" was null or undefined when calling updatePhase().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/phases/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePhaseRequestToJSON(requestParameters['updatePhaseRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue))
  }

  /**
   * Update phase
   */
  async updatePhase(
    requestParameters: UpdatePhaseOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Phase> {
    const response = await this.updatePhaseRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
