/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreatePositionRequest, Position, UpdatePositionRequest } from "../models/index";

import {
  CreatePositionRequestFromJSON,
  CreatePositionRequestToJSON,
  PositionFromJSON,
  PositionToJSON,
  UpdatePositionRequestFromJSON,
  UpdatePositionRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreatePositionOperationRequest {
  createPositionRequest: CreatePositionRequest;
}

export interface GetPositionByIdRequest {
  id: string;
}

export interface ListPositionsRequest {
  meetingId?: string;
  voteStatus?: string;
  accountType?: string;
  select?: string;
  order?: string;
  limit?: number;
  offset?: number;
}

export interface UpdatePositionOperationRequest {
  id: string;
  updatePositionRequest: UpdatePositionRequest;
}

/**
 *
 */
export class PositionsApi extends runtime.BaseAPI {
  /**
   * Create new position
   */
  async createPositionRaw(
    requestParameters: CreatePositionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Position>> {
    if (requestParameters["createPositionRequest"] == null) {
      throw new runtime.RequiredError(
        "createPositionRequest",
        'Required parameter "createPositionRequest" was null or undefined when calling createPosition().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/positions`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreatePositionRequestToJSON(requestParameters["createPositionRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => PositionFromJSON(jsonValue));
  }

  /**
   * Create new position
   */
  async createPosition(
    requestParameters: CreatePositionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Position> {
    const response = await this.createPositionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get position by ID
   */
  async getPositionByIdRaw(
    requestParameters: GetPositionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Position>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getPositionById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/positions/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => PositionFromJSON(jsonValue));
  }

  /**
   * Get position by ID
   */
  async getPositionById(
    requestParameters: GetPositionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Position> {
    const response = await this.getPositionByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List positions with Supabase PostgREST filters.  Common usage: - Filter by meeting: `?meetingId=eq.WEN-2024-AGM` - Filter by vote status: `?voteStatus=eq.Voted` or `?voteStatus=eq.Unvoted` - Filter by account type: `?accountType=eq.CEDE%20%26%20CO%20%2F%20CTC%20%26%20CO` - Include meeting data: `?select=*,meetings(*)` - Include position votes: `?select=*,position_votes(*)` - Order by shares: `?order=shares.desc` - Pagination: `?limit=20&offset=40`
   * List positions
   */
  async listPositionsRaw(
    requestParameters: ListPositionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Position>>> {
    const queryParameters: any = {};

    if (requestParameters["meetingId"] != null) {
      queryParameters["meetingId"] = requestParameters["meetingId"];
    }

    if (requestParameters["voteStatus"] != null) {
      queryParameters["voteStatus"] = requestParameters["voteStatus"];
    }

    if (requestParameters["accountType"] != null) {
      queryParameters["accountType"] = requestParameters["accountType"];
    }

    if (requestParameters["select"] != null) {
      queryParameters["select"] = requestParameters["select"];
    }

    if (requestParameters["order"] != null) {
      queryParameters["order"] = requestParameters["order"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/positions`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PositionFromJSON));
  }

  /**
   * List positions with Supabase PostgREST filters.  Common usage: - Filter by meeting: `?meetingId=eq.WEN-2024-AGM` - Filter by vote status: `?voteStatus=eq.Voted` or `?voteStatus=eq.Unvoted` - Filter by account type: `?accountType=eq.CEDE%20%26%20CO%20%2F%20CTC%20%26%20CO` - Include meeting data: `?select=*,meetings(*)` - Include position votes: `?select=*,position_votes(*)` - Order by shares: `?order=shares.desc` - Pagination: `?limit=20&offset=40`
   * List positions
   */
  async listPositions(
    requestParameters: ListPositionsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Position>> {
    const response = await this.listPositionsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update position
   */
  async updatePositionRaw(
    requestParameters: UpdatePositionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Position>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling updatePosition().',
      );
    }

    if (requestParameters["updatePositionRequest"] == null) {
      throw new runtime.RequiredError(
        "updatePositionRequest",
        'Required parameter "updatePositionRequest" was null or undefined when calling updatePosition().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/positions/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePositionRequestToJSON(requestParameters["updatePositionRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => PositionFromJSON(jsonValue));
  }

  /**
   * Update position
   */
  async updatePosition(
    requestParameters: UpdatePositionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Position> {
    const response = await this.updatePositionRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
