/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  CreateProposalRequest,
  Proposal,
  UpdateProposalRequest,
} from '../models/index'
import {
  CreateProposalRequestFromJSON,
  CreateProposalRequestToJSON,
  ProposalFromJSON,
  ProposalToJSON,
  UpdateProposalRequestFromJSON,
  UpdateProposalRequestToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface CreateProposalOperationRequest {
  meetingId: string
  createProposalRequest: CreateProposalRequest
}

export interface GetProposalByIdRequest {
  id: string
}

export interface ListProposalsRequest {
  meetingId: string
  proposalType?: string
}

export interface UpdateProposalOperationRequest {
  id: string
  updateProposalRequest: UpdateProposalRequest
}

/**
 *
 */
export class ProposalsApi extends runtime.BaseAPI {
  /**
   * Create new proposal
   */
  async createProposalRaw(
    requestParameters: CreateProposalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Proposal>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling createProposal().'
      )
    }

    if (requestParameters['createProposalRequest'] == null) {
      throw new runtime.RequiredError(
        'createProposalRequest',
        'Required parameter "createProposalRequest" was null or undefined when calling createProposal().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/proposals`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateProposalRequestToJSON(requestParameters['createProposalRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProposalFromJSON(jsonValue)
    )
  }

  /**
   * Create new proposal
   */
  async createProposal(
    requestParameters: CreateProposalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Proposal> {
    const response = await this.createProposalRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get proposal by ID
   */
  async getProposalByIdRaw(
    requestParameters: GetProposalByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Proposal>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getProposalById().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/proposals/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProposalFromJSON(jsonValue)
    )
  }

  /**
   * Get proposal by ID
   */
  async getProposalById(
    requestParameters: GetProposalByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Proposal> {
    const response = await this.getProposalByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List proposals for a meeting
   */
  async listProposalsRaw(
    requestParameters: ListProposalsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Proposal>>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling listProposals().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['proposalType'] != null) {
      queryParameters['proposalType'] = requestParameters['proposalType']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/proposals`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ProposalFromJSON)
    )
  }

  /**
   * List proposals for a meeting
   */
  async listProposals(
    requestParameters: ListProposalsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Proposal>> {
    const response = await this.listProposalsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Update proposal
   */
  async updateProposalRaw(
    requestParameters: UpdateProposalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Proposal>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateProposal().'
      )
    }

    if (requestParameters['updateProposalRequest'] == null) {
      throw new runtime.RequiredError(
        'updateProposalRequest',
        'Required parameter "updateProposalRequest" was null or undefined when calling updateProposal().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/proposals/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateProposalRequestToJSON(requestParameters['updateProposalRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProposalFromJSON(jsonValue)
    )
  }

  /**
   * Update proposal
   */
  async updateProposal(
    requestParameters: UpdateProposalOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Proposal> {
    const response = await this.updateProposalRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
