/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Mailing, TabulationReport } from '../models/index'
import {
  MailingFromJSON,
  MailingToJSON,
  TabulationReportFromJSON,
  TabulationReportToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface GetMailingStatisticsRequest {
  meetingId: string
}

export interface GetTabulationReportRequest {
  meetingId: string
}

/**
 *
 */
export class ReportsApi extends runtime.BaseAPI {
  /**
   * Get mailing statistics for a meeting
   */
  async getMailingStatisticsRaw(
    requestParameters: GetMailingStatisticsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Mailing>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling getMailingStatistics().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/mailing`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MailingFromJSON(jsonValue)
    )
  }

  /**
   * Get mailing statistics for a meeting
   */
  async getMailingStatistics(
    requestParameters: GetMailingStatisticsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Mailing> {
    const response = await this.getMailingStatisticsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get pre-calculated tabulation report for a meeting
   */
  async getTabulationReportRaw(
    requestParameters: GetTabulationReportRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TabulationReport>> {
    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling getTabulationReport().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/meetings/{meetingId}/tabulation-report`
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TabulationReportFromJSON(jsonValue)
    )
  }

  /**
   * Get pre-calculated tabulation report for a meeting
   */
  async getTabulationReport(
    requestParameters: GetTabulationReportRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TabulationReport> {
    const response = await this.getTabulationReportRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
