/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  CreateTaskRequest,
  Task,
  TaskStatus,
  UpdateTaskRequest,
} from "../models/index";

import {
  CreateTaskRequestFromJSON,
  CreateTaskRequestToJSON,
  TaskFromJSON,
  TaskStatusFromJSON,
  TaskStatusToJSON,
  TaskToJSON,
  UpdateTaskRequestFromJSON,
  UpdateTaskRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CreateTaskOperationRequest {
  meetingId: string;
  createTaskRequest: CreateTaskRequest;
}

export interface GetTaskByIdRequest {
  id: string;
}

export interface ListTasksRequest {
  meetingId: string;
  phaseId?: string;
  status?: TaskStatus;
  owner?: string;
}

export interface UpdateTaskOperationRequest {
  id: string;
  updateTaskRequest: UpdateTaskRequest;
}

/**
 *
 */
export class TasksApi extends runtime.BaseAPI {
  /**
   * Create new task
   */
  async createTaskRaw(
    requestParameters: CreateTaskOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling createTask().'
      );
    }

    if (requestParameters["createTaskRequest"] == null) {
      throw new runtime.RequiredError(
        "createTaskRequest",
        'Required parameter "createTaskRequest" was null or undefined when calling createTask().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/tasks`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateTaskRequestToJSON(requestParameters["createTaskRequest"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskFromJSON(jsonValue)
    );
  }

  /**
   * Create new task
   */
  async createTask(
    requestParameters: CreateTaskOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Task> {
    const response = await this.createTaskRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get task by ID
   */
  async getTaskByIdRaw(
    requestParameters: GetTaskByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getTaskById().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskFromJSON(jsonValue)
    );
  }

  /**
   * Get task by ID
   */
  async getTaskById(
    requestParameters: GetTaskByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Task> {
    const response = await this.getTaskByIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * List tasks for a meeting
   */
  async listTasksRaw(
    requestParameters: ListTasksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Task>>> {
    if (requestParameters["meetingId"] == null) {
      throw new runtime.RequiredError(
        "meetingId",
        'Required parameter "meetingId" was null or undefined when calling listTasks().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["phaseId"] != null) {
      queryParameters["phaseId"] = requestParameters["phaseId"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["owner"] != null) {
      queryParameters["owner"] = requestParameters["owner"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/meetings/{meetingId}/tasks`;
    urlPath = urlPath.replace(
      `{${"meetingId"}}`,
      encodeURIComponent(String(requestParameters["meetingId"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TaskFromJSON)
    );
  }

  /**
   * List tasks for a meeting
   */
  async listTasks(
    requestParameters: ListTasksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Task>> {
    const response = await this.listTasksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update task
   */
  async updateTaskRaw(
    requestParameters: UpdateTaskOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling updateTask().'
      );
    }

    if (requestParameters["updateTaskRequest"] == null) {
      throw new runtime.RequiredError(
        "updateTaskRequest",
        'Required parameter "updateTaskRequest" was null or undefined when calling updateTask().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateTaskRequestToJSON(requestParameters["updateTaskRequest"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskFromJSON(jsonValue)
    );
  }

  /**
   * Update task
   */
  async updateTask(
    requestParameters: UpdateTaskOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Task> {
    const response = await this.updateTaskRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
