/* tslint:disable */
/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
  CreateAccountUserRequest,
  CreateUserRequest,
  ListAccountUsers200Response,
  ListUserAccounts200Response,
  UpdateUserRequest,
  User,
  UserType,
} from '../models/index'
import {
  CreateAccountUserRequestFromJSON,
  CreateAccountUserRequestToJSON,
  CreateUserRequestFromJSON,
  CreateUserRequestToJSON,
  ListAccountUsers200ResponseFromJSON,
  ListAccountUsers200ResponseToJSON,
  ListUserAccounts200ResponseFromJSON,
  ListUserAccounts200ResponseToJSON,
  UpdateUserRequestFromJSON,
  UpdateUserRequestToJSON,
  UserFromJSON,
  UserToJSON,
  UserTypeFromJSON,
  UserTypeToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface CreateAccountUserOperationRequest {
  accountId: string
  createAccountUserRequest: CreateAccountUserRequest
}

export interface CreateUserOperationRequest {
  createUserRequest: CreateUserRequest
}

export interface DeleteUserRequest {
  id: string
}

export interface GetUserByIdRequest {
  id: string
}

export interface ListAccountUsersRequest {
  accountId: string
  page?: number
  limit?: number
  type?: UserType
}

export interface ListUserAccountsRequest {
  id: string
}

export interface ListUsersRequest {
  page?: number
  limit?: number
  type?: UserType
  accountId?: string
}

export interface UpdateUserOperationRequest {
  id: string
  updateUserRequest: UpdateUserRequest
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   * Create new user for an account
   */
  async createAccountUserRaw(
    requestParameters: CreateAccountUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling createAccountUser().'
      )
    }

    if (requestParameters['createAccountUserRequest'] == null) {
      throw new runtime.RequiredError(
        'createAccountUserRequest',
        'Required parameter "createAccountUserRequest" was null or undefined when calling createAccountUser().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/accounts/{accountId}/users`
    urlPath = urlPath.replace(
      `{${'accountId'}}`,
      encodeURIComponent(String(requestParameters['accountId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateAccountUserRequestToJSON(
          requestParameters['createAccountUserRequest']
        ),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue))
  }

  /**
   * Create new user for an account
   */
  async createAccountUser(
    requestParameters: CreateAccountUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.createAccountUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create new user
   */
  async createUserRaw(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['createUserRequest'] == null) {
      throw new runtime.RequiredError(
        'createUserRequest',
        'Required parameter "createUserRequest" was null or undefined when calling createUser().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue))
  }

  /**
   * Create new user
   */
  async createUser(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.createUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Delete user
   */
  async deleteUserRaw(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteUser().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete user
   */
  async deleteUser(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteUserRaw(requestParameters, initOverrides)
  }

  /**
   * Get user by ID
   */
  async getUserByIdRaw(
    requestParameters: GetUserByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getUserById().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue))
  }

  /**
   * Get user by ID
   */
  async getUserById(
    requestParameters: GetUserByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.getUserByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List users for an account
   */
  async listAccountUsersRaw(
    requestParameters: ListAccountUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListAccountUsers200Response>> {
    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling listAccountUsers().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/accounts/{accountId}/users`
    urlPath = urlPath.replace(
      `{${'accountId'}}`,
      encodeURIComponent(String(requestParameters['accountId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccountUsers200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * List users for an account
   */
  async listAccountUsers(
    requestParameters: ListAccountUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListAccountUsers200Response> {
    const response = await this.listAccountUsersRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns accounts that a user has access to based on their role and relationships
   * Get accounts accessible by user
   */
  async listUserAccountsRaw(
    requestParameters: ListUserAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListUserAccounts200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling listUserAccounts().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{id}/accounts`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListUserAccounts200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * Returns accounts that a user has access to based on their role and relationships
   * Get accounts accessible by user
   */
  async listUserAccounts(
    requestParameters: ListUserAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListUserAccounts200Response> {
    const response = await this.listUserAccountsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List users
   */
  async listUsersRaw(
    requestParameters: ListUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListAccountUsers200Response>> {
    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type']
    }

    if (requestParameters['accountId'] != null) {
      queryParameters['accountId'] = requestParameters['accountId']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListAccountUsers200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * List users
   */
  async listUsers(
    requestParameters: ListUsersRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListAccountUsers200Response> {
    const response = await this.listUsersRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Update user
   */
  async updateUserRaw(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateUser().'
      )
    }

    if (requestParameters['updateUserRequest'] == null) {
      throw new runtime.RequiredError(
        'updateUserRequest',
        'Required parameter "updateUserRequest" was null or undefined when calling updateUser().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{id}`
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue))
  }

  /**
   * Update user
   */
  async updateUser(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.updateUserRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
