/* eslint-disable */
/**
 * BetaNXT Issuer Portal API
 * API for the BetaNXT Issuer Portal - Proxy Voting & Shareholder Meeting Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@betanxt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CastVoteRequest, PositionVote } from '../models/index'
import {
  CastVoteRequestFromJSON,
  CastVoteRequestToJSON,
  PositionVoteFromJSON,
  PositionVoteToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface CreatePositionVoteRequest {
  castVoteRequest: CastVoteRequest
}

export interface GetPositionVotesRequest {
  positionId?: string
  proposalId?: string
  vote?: string
  select?: string
  order?: string
  limit?: number
  offset?: number
}

/**
 *
 */
export class VotingApi extends runtime.BaseAPI {
  /**
   * Create a new position vote record.  Note: In Supabase PostgREST, you POST directly to the table endpoint. The positionId should be included in the request body, not the URL path.
   * Create a position vote
   */
  async createPositionVoteRaw(
    requestParameters: CreatePositionVoteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PositionVote>> {
    if (requestParameters['castVoteRequest'] == null) {
      throw new runtime.RequiredError(
        'castVoteRequest',
        'Required parameter "castVoteRequest" was null or undefined when calling createPositionVote().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/position_votes`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CastVoteRequestToJSON(requestParameters['castVoteRequest']),
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PositionVoteFromJSON(jsonValue)
    )
  }

  /**
   * Create a new position vote record.  Note: In Supabase PostgREST, you POST directly to the table endpoint. The positionId should be included in the request body, not the URL path.
   * Create a position vote
   */
  async createPositionVote(
    requestParameters: CreatePositionVoteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PositionVote> {
    const response = await this.createPositionVoteRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get position votes using Supabase PostgREST filters.  Common usage examples: - Get votes for a position: `?positionId=eq.{uuid}` - Get votes for a proposal: `?proposalId=eq.{uuid}` - Include related data: `?select=*,positions(*),proposals(*)` - Order by date: `?order=createdAt.desc`  Supabase operators: - `eq` - equals - `neq` - not equals - `gt` - greater than - `gte` - greater than or equal - `lt` - less than - `lte` - less than or equal - `like` - LIKE operator - `ilike` - ILIKE operator - `in` - one of a list of values - `is` - checking for null/not null
   * Get position votes
   */
  async getPositionVotesRaw(
    requestParameters: GetPositionVotesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<PositionVote>>> {
    const queryParameters: any = {}

    if (requestParameters['positionId'] != null) {
      queryParameters['positionId'] = requestParameters['positionId']
    }

    if (requestParameters['proposalId'] != null) {
      queryParameters['proposalId'] = requestParameters['proposalId']
    }

    if (requestParameters['vote'] != null) {
      queryParameters['vote'] = requestParameters['vote']
    }

    if (requestParameters['select'] != null) {
      queryParameters['select'] = requestParameters['select']
    }

    if (requestParameters['order'] != null) {
      queryParameters['order'] = requestParameters['order']
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/position_votes`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PositionVoteFromJSON)
    )
  }

  /**
   * Get position votes using Supabase PostgREST filters.  Common usage examples: - Get votes for a position: `?positionId=eq.{uuid}` - Get votes for a proposal: `?proposalId=eq.{uuid}` - Include related data: `?select=*,positions(*),proposals(*)` - Order by date: `?order=createdAt.desc`  Supabase operators: - `eq` - equals - `neq` - not equals - `gt` - greater than - `gte` - greater than or equal - `lt` - less than - `lte` - less than or equal - `like` - LIKE operator - `ilike` - ILIKE operator - `in` - one of a list of values - `is` - checking for null/not null
   * Get position votes
   */
  async getPositionVotes(
    requestParameters: GetPositionVotesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<PositionVote>> {
    const response = await this.getPositionVotesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
